/* NETLab — Lab 6 (RIP v1) data, ported 1:1 from
   public/labnetwork1/lab06-rip-v1/lab6.html's inline <STEPS>/<NODES>/<LINKS>/
   <PRETEST> globals. Second Config Lab built on the shared <ConfigLab/> engine
   (see src/labs/lab05 for the template notes). */
import {
  CONFT_PAT,
  ENABLE_PAT,
  END_OR_EXIT_PAT,
  EXIT_PAT,
  NOSHUT_PAT,
  ROUTERRIP_PAT,
  VERSION1_PAT,
  hostnamePat,
  ifpat,
  ipAddrPat,
  networkPat,
  writeMemPat,
} from '../../lib/ciscoPatterns';
import type { PretestQuestion, Step, TopoLink, TopoNode } from '../../types/configLab';

export const NODES: TopoNode[] = [
  { id: 'PC-A', x: 60, role: 'host' },
  { id: 'R1', x: 260, role: 'router' },
  { id: 'R2', x: 460, role: 'router' },
  { id: 'R3', x: 660, role: 'router' },
  { id: 'PC-C', x: 860, role: 'host' },
];

export const LINKS: TopoLink[] = [
  { from: 'PC-A', to: 'R1', subnet: '172.16.1.0/24', if1: '', if2: 'g0/0', activateOnSteps: [2, 200] },
  { from: 'R1', to: 'R2', subnet: '172.16.2.0/24', if1: 'g0/1', if2: 'g0/0', activateOnSteps: [3, 5] },
  { from: 'R2', to: 'R3', subnet: '172.16.3.0/24', if1: 'g0/1', if2: 'g0/0', activateOnSteps: [6, 8] },
  { from: 'R3', to: 'PC-C', subnet: '172.16.4.0/24', if1: 'g0/1', if2: '', activateOnSteps: [9, 201] },
];

export const NODE_IP_LABELS: Record<string, string> = {
  'PC-A': '172.16.1.10',
  R1: '172.16.1.1',
  R2: '172.16.3.1',
  R3: '172.16.4.1',
  'PC-C': '172.16.4.10',
};

export const CONFIG_ROUTER_WORDS = ['version', 'network', 'exit'];

const SHOW_IP_PROTOCOLS_PAT = /^do\s+sh(ow)?\s+ip\s+prot(o(c(o(l(s)?)?)?)?)?$/i;

export const STEPS: Step[] = [
  {
    id: 1,
    router: 'R1',
    name: 'R1 — enable & configure terminal',
    short: 'R1 enable',
    mode: 'exec',
    prompt: 'Router>',
    cmdHint: { cmd: 'Router> enable', desc: 'เข้า Privileged EXEC ก่อน แล้วพิมพ์ configure terminal' },
    hints: [
      { cmd: 'Router> enable', desc: 'เข้าสู่ Privileged EXEC mode ก่อน' },
      { cmd: 'Router# configure terminal', desc: 'เข้าสู่ Global Configuration mode' },
    ],
    answer: 'enable\nconfigure terminal',
    commands: [
      { mode: 'exec', pat: ENABLE_PAT, next: 'exec-priv', pr: 'Router#', adv: false, msg: '' },
      { mode: 'exec-priv', pat: CONFT_PAT, next: 'config', pr: 'Router(config)#', adv: true, msg: 'Enter configuration commands, one per line.\nRouter(config)#' },
    ],
  },
  {
    id: 21,
    router: 'R1',
    name: 'R1 — ตั้งชื่อ hostname',
    short: 'hostname R1',
    mode: 'config',
    prompt: 'Router(config)#',
    cmdHint: { cmd: 'Router(config)# hostname R1', desc: 'ตั้งชื่ออุปกรณ์เป็น R1 — ควรทำเป็นอย่างแรกก่อนตั้งค่าอื่น' },
    hints: [{ cmd: 'Router(config)# hostname R1', desc: 'ตั้งชื่ออุปกรณ์เป็น R1' }],
    answer: 'hostname R1',
    commands: [{ mode: 'config', pat: hostnamePat('R1'), next: 'config', pr: 'R1(config)#', adv: true, msg: '✓ Hostname เปลี่ยนเป็น R1 แล้วครับ (สังเกต prompt ที่เปลี่ยนไป)' }],
  },
  {
    id: 2,
    router: 'R1',
    name: 'R1 — g0/0 LAN 172.16.1.1/24',
    short: 'g0/0 LAN',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# interface g0/0', desc: 'LAN ฝั่ง PC-A: 172.16.1.1/24 — เส้น PC-A—R1 จะเขียว' },
    hints: [
      { cmd: 'R1(config)# interface g0/0', desc: 'LAN ฝั่ง PC-A: 172.16.1.1/24 — เส้น PC-A—R1 จะเขียว' },
      { cmd: 'R1(config-if)# ip address 172.16.1.1 255.255.255.0', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R1(config-if)# no shutdown', desc: 'เปิดใช้งาน interface (ไม่งั้นจะ down ตลอด)' },
      { cmd: 'R1(config-if)# exit', desc: 'ออกจาก interface mode กลับสู่ config mode' },
    ],
    answer: 'interface g0/0\nip address 172.16.1.1 255.255.255.0\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('0'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('172.16.1.1', '255.255.255.0'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to up' },
      { mode: 'config-if', pat: EXIT_PAT, next: 'config', pr: 'R1(config)#', adv: true, msg: '✓ g0/0 → 172.16.1.1/24 UP\n  เส้น PC-A—R1 เขียวครึ่งเดียว รอ PC-A ตั้ง IP ด้วยครับ' },
    ],
  },
  {
    id: 3,
    router: 'R1',
    name: 'R1 — g0/1 WAN 172.16.2.1/24',
    short: 'g0/1 WAN',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# interface g0/1', desc: 'WAN ฝั่ง R2: 172.16.2.1/24 — เส้น R1—R2 จะเขียว' },
    hints: [
      { cmd: 'R1(config)# interface g0/1', desc: 'WAN ฝั่ง R2: 172.16.2.1/24 — เส้น R1—R2 จะเขียว' },
      { cmd: 'R1(config-if)# ip address 172.16.2.1 255.255.255.0', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R1(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R1(config-if)# exit', desc: 'ออกจาก interface mode กลับสู่ config mode' },
    ],
    answer: 'interface g0/1\nip address 172.16.2.1 255.255.255.0\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('1'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('172.16.2.1', '255.255.255.0'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to up' },
      {
        mode: 'config-if',
        pat: EXIT_PAT,
        next: 'config',
        pr: 'R1(config)#',
        adv: true,
        msg: '✓ g0/1 → 172.16.2.1/24 UP\n  เส้น R1—R2 เขียวแล้วครับ — ต่อไปตั้งค่า PC-A ก่อน แล้วค่อยไปตั้ง IP ของ R2',
      },
    ],
  },
  {
    id: 200,
    router: 'PC-A',
    type: 'pcconfig',
    name: 'PC-A — ตั้งค่า IP / Subnet / Gateway',
    short: 'PC-A config',
    mode: 'pcconfig',
    prompt: '(คลิก PC-A)',
    expected: { ip: '172.16.1.10', mask: '255.255.255.0', gateway: '172.16.1.1' },
    cmdHint: { cmd: '(คลิกที่ไอคอน PC-A บนแผนภาพด้านบน)', desc: 'กำหนด IP/Subnet/Gateway ให้ PC-A ผ่านหน้าต่างตั้งค่า' },
  },
  {
    id: 4,
    router: 'R2',
    name: 'R2 — enable & configure terminal',
    short: 'R2 enable',
    mode: 'exec',
    prompt: 'Router>',
    cmdHint: { cmd: 'Router> enable', desc: 'สลับไปทำ R2 — enable แล้ว configure terminal' },
    hints: [
      { cmd: 'Router> enable', desc: 'สลับไปทำ R2 — เข้าสู่ Privileged EXEC' },
      { cmd: 'Router# configure terminal', desc: 'เข้าสู่ Global Configuration mode' },
    ],
    answer: 'enable\nconfigure terminal',
    commands: [
      { mode: 'exec', pat: ENABLE_PAT, next: 'exec-priv', pr: 'Router#', adv: false, msg: '' },
      { mode: 'exec-priv', pat: CONFT_PAT, next: 'config', pr: 'Router(config)#', adv: true, msg: 'Enter configuration commands, one per line.\nRouter(config)#' },
    ],
  },
  {
    id: 22,
    router: 'R2',
    name: 'R2 — ตั้งชื่อ hostname',
    short: 'hostname R2',
    mode: 'config',
    prompt: 'Router(config)#',
    cmdHint: { cmd: 'Router(config)# hostname R2', desc: 'ตั้งชื่ออุปกรณ์เป็น R2' },
    hints: [{ cmd: 'Router(config)# hostname R2', desc: 'ตั้งชื่ออุปกรณ์เป็น R2' }],
    answer: 'hostname R2',
    commands: [{ mode: 'config', pat: hostnamePat('R2'), next: 'config', pr: 'R2(config)#', adv: true, msg: '✓ Hostname เปลี่ยนเป็น R2 แล้วครับ' }],
  },
  {
    id: 5,
    router: 'R2',
    name: 'R2 — g0/0 (←R1) 172.16.2.2/24',
    short: 'g0/0 ←R1',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# interface g0/0', desc: 'ฝั่ง R1: 172.16.2.2/24' },
    hints: [
      { cmd: 'R2(config)# interface g0/0', desc: 'ฝั่ง R1: 172.16.2.2/24' },
      { cmd: 'R2(config-if)# ip address 172.16.2.2 255.255.255.0', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R2(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R2(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/0\nip address 172.16.2.2 255.255.255.0\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('0'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('172.16.2.2', '255.255.255.0'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to up' },
      { mode: 'config-if', pat: EXIT_PAT, next: 'config', pr: 'R2(config)#', adv: true, msg: '✓ g0/0 → 172.16.2.2/24 UP' },
    ],
  },
  {
    id: 6,
    router: 'R2',
    name: 'R2 — g0/1 (→R3) 172.16.3.1/24',
    short: 'g0/1 →R3',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# interface g0/1', desc: 'ฝั่ง R3: 172.16.3.1/24 — เส้น R2—R3 จะเขียว' },
    hints: [
      { cmd: 'R2(config)# interface g0/1', desc: 'ฝั่ง R3: 172.16.3.1/24 — เส้น R2—R3 จะเขียว' },
      { cmd: 'R2(config-if)# ip address 172.16.3.1 255.255.255.0', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R2(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R2(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/1\nip address 172.16.3.1 255.255.255.0\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('1'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('172.16.3.1', '255.255.255.0'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to up' },
      {
        mode: 'config-if',
        pat: EXIT_PAT,
        next: 'config',
        pr: 'R2(config)#',
        adv: true,
        msg: '✓ g0/1 → 172.16.3.1/24 UP\n  เส้น R2—R3 เขียวแล้วครับ — สลับไปตั้ง IP ของ R3 ต่อได้เลยครับ',
      },
    ],
  },
  {
    id: 7,
    router: 'R3',
    name: 'R3 — enable & configure terminal',
    short: 'R3 enable',
    mode: 'exec',
    prompt: 'Router>',
    cmdHint: { cmd: 'Router> enable', desc: 'สลับไปทำ R3 — enable แล้ว configure terminal' },
    hints: [
      { cmd: 'Router> enable', desc: 'สลับไปทำ R3 — เข้าสู่ Privileged EXEC' },
      { cmd: 'Router# configure terminal', desc: 'เข้าสู่ Global Configuration mode' },
    ],
    answer: 'enable\nconfigure terminal',
    commands: [
      { mode: 'exec', pat: ENABLE_PAT, next: 'exec-priv', pr: 'Router#', adv: false, msg: '' },
      { mode: 'exec-priv', pat: CONFT_PAT, next: 'config', pr: 'Router(config)#', adv: true, msg: 'Enter configuration commands, one per line.\nRouter(config)#' },
    ],
  },
  {
    id: 23,
    router: 'R3',
    name: 'R3 — ตั้งชื่อ hostname',
    short: 'hostname R3',
    mode: 'config',
    prompt: 'Router(config)#',
    cmdHint: { cmd: 'Router(config)# hostname R3', desc: 'ตั้งชื่ออุปกรณ์เป็น R3' },
    hints: [{ cmd: 'Router(config)# hostname R3', desc: 'ตั้งชื่ออุปกรณ์เป็น R3' }],
    answer: 'hostname R3',
    commands: [{ mode: 'config', pat: hostnamePat('R3'), next: 'config', pr: 'R3(config)#', adv: true, msg: '✓ Hostname เปลี่ยนเป็น R3 แล้วครับ' }],
  },
  {
    id: 8,
    router: 'R3',
    name: 'R3 — g0/0 (←R2) 172.16.3.2/24',
    short: 'g0/0 ←R2',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# interface g0/0', desc: 'ฝั่ง R2: 172.16.3.2/24' },
    hints: [
      { cmd: 'R3(config)# interface g0/0', desc: 'ฝั่ง R2: 172.16.3.2/24' },
      { cmd: 'R3(config-if)# ip address 172.16.3.2 255.255.255.0', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R3(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R3(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/0\nip address 172.16.3.2 255.255.255.0\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('0'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('172.16.3.2', '255.255.255.0'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to up' },
      { mode: 'config-if', pat: EXIT_PAT, next: 'config', pr: 'R3(config)#', adv: true, msg: '✓ g0/0 → 172.16.3.2/24 UP' },
    ],
  },
  {
    id: 9,
    router: 'R3',
    name: 'R3 — g0/1 LAN 172.16.4.1/24',
    short: 'g0/1 LAN',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# interface g0/1', desc: 'LAN ฝั่ง PC-C: 172.16.4.1/24 — เส้น R3—PC-C จะเขียว' },
    hints: [
      { cmd: 'R3(config)# interface g0/1', desc: 'LAN ฝั่ง PC-C: 172.16.4.1/24 — เส้น R3—PC-C จะเขียว' },
      { cmd: 'R3(config-if)# ip address 172.16.4.1 255.255.255.0', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R3(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R3(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/1\nip address 172.16.4.1 255.255.255.0\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('1'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('172.16.4.1', '255.255.255.0'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to up' },
      {
        mode: 'config-if',
        pat: EXIT_PAT,
        next: 'config',
        pr: 'R3(config)#',
        adv: true,
        msg: '✓ g0/1 → 172.16.4.1/24 UP\n  ต่อไปตั้งค่า PC-C ให้ครบตามหลักการก่อนครับ',
      },
    ],
  },
  {
    id: 201,
    router: 'PC-C',
    type: 'pcconfig',
    name: 'PC-C — ตั้งค่า IP / Subnet / Gateway',
    short: 'PC-C config',
    mode: 'pcconfig',
    prompt: '(คลิก PC-C)',
    expected: { ip: '172.16.4.10', mask: '255.255.255.0', gateway: '172.16.4.1' },
    cmdHint: { cmd: '(คลิกที่ไอคอน PC-C บนแผนภาพด้านบน)', desc: 'กำหนด IP/Subnet/Gateway ให้ PC-C ผ่านหน้าต่างตั้งค่า' },
  },

  // ── เฟส 2: ที่เหลือของ R3 (เปิด RIP, ตรวจสอบ, save) ──
  {
    id: 10,
    router: 'R3',
    name: 'R3 — เปิดใช้งาน RIPv1',
    short: 'RIP setup',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# router rip', desc: 'เข้าสู่โหมดตั้งค่า RIP' },
    hints: [
      { cmd: 'R3(config)# router rip', desc: 'เข้าสู่โหมดตั้งค่า Routing Protocol RIP' },
      { cmd: 'R3(config-router)# version 1', desc: 'บังคับใช้ RIP เวอร์ชัน 1 (classful, ไม่ส่ง subnet mask)' },
      { cmd: 'R3(config-router)# network 172.16.0.0', desc: 'ประกาศ major network 172.16.0.0 — ครอบคลุมทุก interface ของ R3 ที่อยู่ใน network นี้ในคำสั่งเดียว' },
    ],
    answer: 'router rip\nversion 1\nnetwork 172.16.0.0',
    commands: [
      { mode: 'config', pat: ROUTERRIP_PAT, next: 'config-router', pr: 'R3(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: VERSION1_PAT, next: 'config-router', pr: 'R3(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: networkPat('172.16.0.0'), next: 'config', pr: 'R3(config)#', adv: true, msg: '✓ เปิด RIPv1 บน R3 แล้วครับ — ประกาศ network 172.16.0.0 ครอบคลุมทุก interface' },
    ],
  },
  {
    id: 11,
    router: 'R3',
    name: 'R3 — ตรวจสอบด้วย show ip protocols (Checkpoint)',
    short: 'show protocols',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# do show ip protocols', desc: 'ตรวจสอบว่า RIP process กำลังทำงานอยู่ก่อน save' },
    answer: 'do show ip protocols',
    commands: [
      {
        mode: 'config',
        pat: SHOW_IP_PROTOCOLS_PAT,
        next: 'config',
        pr: 'R3(config)#',
        adv: true,
        msg: 'Routing Protocol is "rip"\n  Sending updates every 30 seconds\n  Default version control: send version 1, receive version 1\n  Routing for Networks:\n    172.16.0.0\n  Distance: (default is 120)\n\n✓ RIP process กำลังทำงานอยู่ครับ — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },
  {
    id: 12,
    router: 'R3',
    name: 'R3 — end & write memory',
    short: 'save R3',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# end  →  write memory', desc: 'บันทึก config R3 ที่ตั้งค่าไว้ให้ถาวร' },
    hints: [
      { cmd: 'R3(config)# end', desc: 'ออกจาก config mode (end หรือ exit ก็ได้)' },
      { cmd: 'R3# write memory', desc: 'บันทึก config R3 ที่ตั้งค่าไว้ให้ถาวร' },
    ],
    answer: 'end\nwrite memory',
    commands: [
      { mode: 'config', pat: END_OR_EXIT_PAT, next: 'exec-priv', pr: 'R3#', adv: false, msg: 'R3#' },
      { mode: 'exec-priv', pat: writeMemPat(), next: 'exec-priv', pr: 'R3#', adv: true, msg: 'Building configuration...\n[OK]\n✓ R3 config บันทึกแล้วครับ — สลับไปทำ R2 ต่อครับ' },
    ],
  },

  // ── เฟส 2 (ต่อ): ที่เหลือของ R2 (เปิด RIP, ตรวจสอบ, save) ──
  {
    id: 13,
    router: 'R2',
    name: 'R2 — เปิดใช้งาน RIPv1',
    short: 'RIP setup',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# router rip', desc: 'เข้าสู่โหมดตั้งค่า RIP' },
    hints: [
      { cmd: 'R2(config)# router rip', desc: 'เข้าสู่โหมดตั้งค่า Routing Protocol RIP' },
      { cmd: 'R2(config-router)# version 1', desc: 'บังคับใช้ RIP เวอร์ชัน 1' },
      { cmd: 'R2(config-router)# network 172.16.0.0', desc: 'ประกาศ major network 172.16.0.0 — ครอบคลุมทั้ง 2 interface ของ R2' },
    ],
    answer: 'router rip\nversion 1\nnetwork 172.16.0.0',
    commands: [
      { mode: 'config', pat: ROUTERRIP_PAT, next: 'config-router', pr: 'R2(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: VERSION1_PAT, next: 'config-router', pr: 'R2(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: networkPat('172.16.0.0'), next: 'config', pr: 'R2(config)#', adv: true, msg: '✓ เปิด RIPv1 บน R2 แล้วครับ — ประกาศ network 172.16.0.0 ครอบคลุมทุก interface' },
    ],
  },
  {
    id: 14,
    router: 'R2',
    name: 'R2 — ตรวจสอบด้วย show ip protocols (Checkpoint)',
    short: 'show protocols',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# do show ip protocols', desc: 'ตรวจสอบว่า RIP process กำลังทำงานอยู่ก่อน save' },
    answer: 'do show ip protocols',
    commands: [
      {
        mode: 'config',
        pat: SHOW_IP_PROTOCOLS_PAT,
        next: 'config',
        pr: 'R2(config)#',
        adv: true,
        msg: 'Routing Protocol is "rip"\n  Sending updates every 30 seconds\n  Default version control: send version 1, receive version 1\n  Routing for Networks:\n    172.16.0.0\n  Distance: (default is 120)\n\n✓ RIP process กำลังทำงานอยู่ครับ — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },
  {
    id: 15,
    router: 'R2',
    name: 'R2 — end & write memory',
    short: 'save R2',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# end  →  write memory', desc: 'บันทึก config R2' },
    hints: [
      { cmd: 'R2(config)# end', desc: 'ออกจาก config mode (end หรือ exit ก็ได้)' },
      { cmd: 'R2# write memory', desc: 'บันทึก config R2 ที่ตั้งค่าไว้ให้ถาวร' },
    ],
    answer: 'end\nwrite memory',
    commands: [
      { mode: 'config', pat: END_OR_EXIT_PAT, next: 'exec-priv', pr: 'R2#', adv: false, msg: 'R2#' },
      { mode: 'exec-priv', pat: writeMemPat(), next: 'exec-priv', pr: 'R2#', adv: true, msg: 'Building configuration...\n[OK]\n✓ R2 config บันทึกแล้วครับ — สลับไปทำ R1 ต่อครับ' },
    ],
  },

  // ── เฟส 3: ที่เหลือของ R1 (เปิด RIP, ตรวจสอบ, save) แล้วตรวจสอบผลลัพธ์รวม ──
  {
    id: 16,
    router: 'R1',
    name: 'R1 — เปิดใช้งาน RIPv1',
    short: 'RIP setup',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# router rip', desc: 'เข้าสู่โหมดตั้งค่า RIP' },
    hints: [
      { cmd: 'R1(config)# router rip', desc: 'เข้าสู่โหมดตั้งค่า Routing Protocol RIP' },
      { cmd: 'R1(config-router)# version 1', desc: 'บังคับใช้ RIP เวอร์ชัน 1' },
      { cmd: 'R1(config-router)# network 172.16.0.0', desc: 'ประกาศ major network 172.16.0.0 — ครอบคลุมทั้ง 2 interface ของ R1' },
    ],
    answer: 'router rip\nversion 1\nnetwork 172.16.0.0',
    commands: [
      { mode: 'config', pat: ROUTERRIP_PAT, next: 'config-router', pr: 'R1(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: VERSION1_PAT, next: 'config-router', pr: 'R1(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: networkPat('172.16.0.0'), next: 'config', pr: 'R1(config)#', adv: true, msg: '✓ เปิด RIPv1 บน R1 แล้วครับ — ประกาศ network 172.16.0.0 ครอบคลุมทุก interface' },
    ],
  },
  {
    id: 17,
    router: 'R1',
    name: 'R1 — ตรวจสอบด้วย show ip protocols (Checkpoint)',
    short: 'show protocols',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# do show ip protocols', desc: 'ตรวจสอบว่า RIP process กำลังทำงานอยู่ก่อน save — ใช้ do นำหน้าเพื่อรันคำสั่ง show จาก config mode ได้เลยโดยไม่ต้อง exit' },
    answer: 'do show ip protocols',
    commands: [
      {
        mode: 'config',
        pat: SHOW_IP_PROTOCOLS_PAT,
        next: 'config',
        pr: 'R1(config)#',
        adv: true,
        msg: 'Routing Protocol is "rip"\n  Sending updates every 30 seconds\n  Default version control: send version 1, receive version 1\n  Routing for Networks:\n    172.16.0.0\n  Distance: (default is 120)\n\n✓ RIP process กำลังทำงานอยู่ครับ — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },
  {
    id: 18,
    router: 'R1',
    name: 'R1 — end & write memory',
    short: 'save R1',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# end  →  write memory', desc: 'บันทึก config R1 ไปยัง NVRAM' },
    hints: [
      { cmd: 'R1(config)# end', desc: 'ออกจาก config mode กลับสู่ Privileged EXEC (end หรือ exit ก็ได้)' },
      { cmd: 'R1# write memory', desc: 'บันทึก config ที่ตั้งค่าไว้ให้ถาวรไปยังหน่วยความจำของ Router' },
    ],
    answer: 'end\nwrite memory',
    commands: [
      { mode: 'config', pat: END_OR_EXIT_PAT, next: 'exec-priv', pr: 'R1#', adv: false, msg: 'R1#' },
      { mode: 'exec-priv', pat: writeMemPat(), next: 'exec-priv', pr: 'R1#', adv: true, msg: 'Building configuration...\n[OK]\n✓ R1 config บันทึกแล้วครับ' },
    ],
  },
  {
    id: 19,
    router: 'R1',
    name: 'R1 — ตรวจสอบ Routing Table รวม (show ip route)',
    short: 'show route',
    mode: 'exec-priv',
    prompt: 'R1#',
    cmdHint: { cmd: 'R1# show ip route', desc: 'ดู network ที่ R1 เรียนรู้มาจาก RIP โดยอัตโนมัติ (ไม่ต้องพิมพ์ ip route เองเลย)' },
    answer: 'show ip route',
    commands: [
      {
        mode: 'exec-priv',
        pat: /^sh(ow)?\s+ip\s+route$/i,
        next: 'exec-priv',
        pr: 'R1#',
        adv: true,
        msg: 'Codes: L - local, C - connected, R - RIP\n\nC    172.16.1.0/24 is directly connected, GigabitEthernet0/0\nC    172.16.2.0/24 is directly connected, GigabitEthernet0/1\nR    172.16.3.0/24 [120/1] via 172.16.2.2, 00:00:12, GigabitEthernet0/1\nR    172.16.4.0/24 [120/2] via 172.16.2.2, 00:00:12, GigabitEthernet0/1\n\n✓ เห็น network 172.16.3.0/24 และ 172.16.4.0/24 ที่เรียนรู้มาจาก RIP (R) แล้วครับ — ไม่ต้องพิมพ์ ip route เอง',
      },
    ],
  },
  {
    id: 20,
    router: 'PC-A',
    type: 'pcping',
    name: 'PC-A — ทดสอบ ping ไปยัง PC-C ผ่าน Command Prompt',
    short: 'ping PC-C (PC)',
    mode: 'pcping',
    prompt: '(คลิก PC-A)',
    target: { ip: '172.16.4.10', label: 'PC-C' },
    cmdHint: {
      cmd: '(คลิกที่ไอคอน PC-A บนแผนภาพด้านบน แล้วพิมพ์ ping 172.16.4.10 ในหน้า Command Prompt)',
      desc: 'ทดสอบว่า PC-A คุยกับ PC-C ได้จริงจากมุมมองผู้ใช้งานทั่วไป (ไม่ผ่าน Router) — ยืนยันว่า RIP พาไปถึงปลายทางได้จริง',
    },
  },
];

export const PRETEST: PretestQuestion[] = [
  {
    id: 'q1',
    type: 'mcq',
    q: 'RIP เป็น Routing Protocol ประเภทไหน?',
    opts: ['Link-State', 'Distance Vector', 'Path-Vector', 'Hybrid'],
    ans: 1,
    exp: 'RIP เป็น Distance Vector Protocol ที่แชร์ routing table ทั้งหมดให้เพื่อนบ้านเป็นระยะ ต่างจาก Link-State (เช่น OSPF) ที่แชร์แค่สถานะของลิงก์',
  },
  {
    id: 'q2',
    type: 'mcq',
    q: 'RIP ใช้ metric อะไรในการเลือกเส้นทาง?',
    opts: ['Bandwidth', 'Hop Count', 'Delay', 'Cost'],
    ans: 1,
    exp: 'RIP ใช้ Hop Count (จำนวน Router ที่ต้องผ่าน) เป็น metric เพียงอย่างเดียว เส้นทางที่ hop น้อยกว่าจะถูกเลือกเสมอ แม้ bandwidth จะต่ำกว่าก็ตาม',
  },
  {
    id: 'q3',
    type: 'mcq',
    q: 'คำสั่งใดใช้เปิดใช้งาน RIP และประกาศ network?',
    opts: ['ip route rip [network]', 'router rip ตามด้วย network [major-network]', 'enable rip [network] [mask]', 'rip network [network]/[prefix]'],
    ans: 1,
    exp: 'ต้องเข้าโหมด router rip ก่อน แล้วตามด้วย network [major-network] เช่น router rip แล้ว network 172.16.0.0 — RIPv1 รับแค่ major network แบบ classful เท่านั้น ไม่รับ subnet mask',
  },
  {
    id: 'q4',
    type: 'dragdrop',
    q: 'จับคู่คำสั่งกับหน้าที่ของมัน',
    pairs: [
      { left: 'router rip', right: 'เข้าสู่โหมดตั้งค่า Routing Protocol RIP' },
      { left: 'version 1', right: 'บังคับใช้ RIP เวอร์ชัน 1 (classful)' },
      { left: 'network 172.16.0.0', right: 'ประกาศ major network ให้ RIP ทำงานบนทุก interface ที่อยู่ในนั้น' },
      { left: 'show ip protocols', right: 'ตรวจสอบว่า RIP process กำลังทำงานอยู่' },
    ],
  },
];

export const INTRO_LINES = [
  { text: '# Ch.6 RIP v1 — NETLab', cls: 't-info' },
  { text: '# อ้างอิง: Cisco Networking Academy W6', cls: 't-hint' },
  { text: '# Topology: PC-A—R1—R2—R3—PC-C', cls: 't-dim' },
  { text: '# R1: g0/0=172.16.1.1/24  g0/1=172.16.2.1/24', cls: 't-dim' },
  { text: '# R2: g0/0=172.16.2.2/24  g0/1=172.16.3.1/24', cls: 't-dim' },
  { text: '# R3: g0/0=172.16.3.2/24  g0/1=172.16.4.1/24', cls: 't-dim' },
  { text: '' },
  { text: '# เริ่มที่ R1 — พิมพ์: enable', cls: 't-hint' },
];

export const WELCOME_MSG =
  'สวัสดีครับ! Ch.6 RIP v1\n\nTopology: PC-A—R1—R2—R3—PC-C\nขั้นตอนแรก: ตั้งชื่อ hostname และ IP ให้ครบทุกอุปกรณ์ก่อน (รวม PC-A, PC-C ด้วย — คลิกที่ไอคอน PC บนแผนภาพเพื่อกรอก IP) แล้วค่อยเปิด RIPv1 ให้ Router เรียนรู้เส้นทางกันเองอัตโนมัติ รวม 25 steps (มีจุด Checkpoint ตรวจสอบด้วย show ก่อน save ทุก Router)\nแต่ละเส้นจะเขียวเมื่อทั้งสองฝั่งตั้งค่าเสร็จครับ\n\nทำ Pre-test ก่อนหรือข้ามไป Lab เลยก็ได้ครับ';

export const COMPLETE_CHAT_SUMMARY =
  'ยินดีด้วยครับ! Lab Ch.6 เสร็จสมบูรณ์!\n\nสรุป:\n• R1, R2, R3: ตั้ง IP ครบทุก interface แล้วเปิด RIPv1 (router rip + network 172.16.0.0)\n• Router ทั้ง 3 ตัวเรียนรู้เส้นทางกันเองอัตโนมัติ ไม่ต้องพิมพ์ ip route เลย\n• Ping PC-A→PC-C สำเร็จผ่าน route ที่ RIP เรียนรู้เอง';
