/* NETLab — Lab 10 (Redistribution) data, ported 1:1 from
   public/labnetwork1/lab10-redistribution/lab10.html's inline <STEPS>/<NODES>/
   <LINKS>/<PRETEST> globals. R1-R2 runs OSPF, R2-R3 runs EIGRP, and R2 is the
   ASBR that must redistribute both directions — the lab deliberately shows a
   "before" show ip route (step 100) with the PC-C network missing, so the
   "after" result (step 102, O E2) actually demonstrates what redistribution
   did. Same shared <ConfigLab/> engine as lab05-09. */
import {
  CONFT_PAT,
  ENABLE_PAT,
  END_OR_EXIT_PAT,
  EXIT_PAT,
  NOAUTOSUM_PAT,
  NOSHUT_PAT,
  hostnamePat,
  ifpat,
  ipAddrPat,
  networkAreaPat,
  networkWildcardPat,
  redistributeIntoEigrpPat,
  redistributeIntoOspfPat,
  routerEigrpPat,
  routerOspfPat,
  writeMemPat,
} from '../../lib/ciscoPatterns';
import type { PretestQuestion, Step, TopoLink, TopoNode } from '../../types/configLab';

export const NODES: TopoNode[] = [
  { id: 'PC-A', x: 60, role: 'host' },
  { id: 'R1', x: 260, role: 'router' },
  { id: 'R2', x: 460, role: 'router' },
  { id: 'R3', x: 660, role: 'router' },
  { id: 'PC-C', x: 860, role: 'host' },
];

export const LINKS: TopoLink[] = [
  { from: 'PC-A', to: 'R1', subnet: '172.25.1.0/24', if1: '', if2: 'g0/0', activateOnSteps: [2, 200] },
  { from: 'R1', to: 'R2', subnet: '172.25.2.0/30', if1: 'g0/1', if2: 'g0/0', activateOnSteps: [3, 5] },
  { from: 'R2', to: 'R3', subnet: '172.25.2.4/30', if1: 'g0/1', if2: 'g0/0', activateOnSteps: [6, 8] },
  { from: 'R3', to: 'PC-C', subnet: '172.25.3.0/24', if1: 'g0/1', if2: '', activateOnSteps: [9, 201] },
];

export const NODE_IP_LABELS: Record<string, string> = {
  'PC-A': '172.25.1.10',
  R1: '172.25.1.1',
  R2: '172.25.2.5',
  R3: '172.25.3.1',
  'PC-C': '172.25.3.10',
};

export const CONFIG_ROUTER_WORDS = ['network', 'area', 'exit', 'redistribute', 'no', 'auto-summary', 'eigrp', 'ospf', 'subnets', 'metric'];

const SHOW_IP_PROTOCOLS_PAT = /^do\s+sh(ow)?\s+ip\s+prot(o(c(o(l(s)?)?)?)?)?$/i;
const SHOW_OSPF_NEIGHBOR_PAT = /^do\s+sh(ow)?\s+ip\s+ospf\s+neigh(b(o(r)?)?)?$/i;
const SHOW_EIGRP_NEIGHBORS_PAT = /^do\s+sh(ow)?\s+ip\s+eigrp\s+neigh(b(o(r(s)?)?)?)?$/i;
const SHOW_IP_ROUTE_PAT = /^sh(ow)?\s+ip\s+route$/i;

export const STEPS: Step[] = [
  {
    id: 1,
    router: 'R1',
    name: 'R1 — enable & configure terminal',
    short: 'R1 enable',
    mode: 'exec',
    prompt: 'Router>',
    cmdHint: { cmd: 'Router> enable', desc: 'เข้า Privileged EXEC ก่อน แล้วพิมพ์ configure terminal' },
    hints: [
      { cmd: 'Router> enable', desc: 'เข้าสู่ Privileged EXEC mode ก่อน' },
      { cmd: 'Router# configure terminal', desc: 'เข้าสู่ Global Configuration mode' },
    ],
    answer: 'enable\nconfigure terminal',
    commands: [
      { mode: 'exec', pat: ENABLE_PAT, next: 'exec-priv', pr: 'Router#', adv: false, msg: '' },
      { mode: 'exec-priv', pat: CONFT_PAT, next: 'config', pr: 'Router(config)#', adv: true, msg: 'Enter configuration commands, one per line.\nRouter(config)#' },
    ],
  },
  {
    id: 21,
    router: 'R1',
    name: 'R1 — ตั้งชื่อ hostname',
    short: 'hostname R1',
    mode: 'config',
    prompt: 'Router(config)#',
    cmdHint: { cmd: 'Router(config)# hostname R1', desc: 'ตั้งชื่ออุปกรณ์เป็น R1 — ควรทำเป็นอย่างแรกก่อนตั้งค่าอื่น' },
    hints: [{ cmd: 'Router(config)# hostname R1', desc: 'ตั้งชื่ออุปกรณ์เป็น R1' }],
    answer: 'hostname R1',
    commands: [{ mode: 'config', pat: hostnamePat('R1'), next: 'config', pr: 'R1(config)#', adv: true, msg: '✓ Hostname เปลี่ยนเป็น R1 แล้วครับ (สังเกต prompt ที่เปลี่ยนไป)' }],
  },
  {
    id: 2,
    router: 'R1',
    name: 'R1 — g0/0 LAN 172.25.1.1/24',
    short: 'g0/0 LAN',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# interface g0/0', desc: 'LAN ฝั่ง PC-A: 172.25.1.1/24 — เส้น PC-A—R1 จะเขียว' },
    hints: [
      { cmd: 'R1(config)# interface g0/0', desc: 'LAN ฝั่ง PC-A: 172.25.1.1/24 — เส้น PC-A—R1 จะเขียว' },
      { cmd: 'R1(config-if)# ip address 172.25.1.1 255.255.255.0', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R1(config-if)# no shutdown', desc: 'เปิดใช้งาน interface (ไม่งั้นจะ down ตลอด)' },
      { cmd: 'R1(config-if)# exit', desc: 'ออกจาก interface mode กลับสู่ config mode' },
    ],
    answer: 'interface g0/0\nip address 172.25.1.1 255.255.255.0\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('0'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('172.25.1.1', '255.255.255.0'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to up' },
      { mode: 'config-if', pat: EXIT_PAT, next: 'config', pr: 'R1(config)#', adv: true, msg: '✓ g0/0 → 172.25.1.1/24 UP\n  เส้น PC-A—R1 เขียวครึ่งเดียว รอ PC-A ตั้ง IP ด้วยครับ' },
    ],
  },
  {
    id: 3,
    router: 'R1',
    name: 'R1 — g0/1 WAN 172.25.2.1/30 (ฝั่ง OSPF)',
    short: 'g0/1 WAN',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# interface g0/1', desc: 'WAN ฝั่ง R2 (โซนที่จะใช้ OSPF): 172.25.2.1/30 — เส้น R1—R2 จะเขียว' },
    hints: [
      { cmd: 'R1(config)# interface g0/1', desc: 'WAN ฝั่ง R2: 172.25.2.1/30 — เส้น R1—R2 จะเขียว' },
      { cmd: 'R1(config-if)# ip address 172.25.2.1 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้ (VLSM /30 สำหรับลิงก์จุดต่อจุด)' },
      { cmd: 'R1(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R1(config-if)# exit', desc: 'ออกจาก interface mode กลับสู่ config mode' },
    ],
    answer: 'interface g0/1\nip address 172.25.2.1 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('1'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('172.25.2.1', '255.255.255.252'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to up' },
      {
        mode: 'config-if',
        pat: EXIT_PAT,
        next: 'config',
        pr: 'R1(config)#',
        adv: true,
        msg: '✓ g0/1 → 172.25.2.1/30 UP\n  เส้น R1—R2 เขียวแล้วครับ — ต่อไปตั้งค่า PC-A ก่อน แล้วค่อยไปตั้ง IP ของ R2',
      },
    ],
  },
  {
    id: 200,
    router: 'PC-A',
    type: 'pcconfig',
    name: 'PC-A — ตั้งค่า IP / Subnet / Gateway',
    short: 'PC-A config',
    mode: 'pcconfig',
    prompt: '(คลิก PC-A)',
    expected: { ip: '172.25.1.10', mask: '255.255.255.0', gateway: '172.25.1.1' },
    cmdHint: { cmd: '(คลิกที่ไอคอน PC-A บนแผนภาพด้านบน)', desc: 'กำหนด IP/Subnet/Gateway ให้ PC-A ผ่านหน้าต่างตั้งค่า' },
  },
  {
    id: 4,
    router: 'R2',
    name: 'R2 — enable & configure terminal',
    short: 'R2 enable',
    mode: 'exec',
    prompt: 'Router>',
    cmdHint: { cmd: 'Router> enable', desc: 'สลับไปทำ R2 — enable แล้ว configure terminal' },
    hints: [
      { cmd: 'Router> enable', desc: 'สลับไปทำ R2 — เข้าสู่ Privileged EXEC' },
      { cmd: 'Router# configure terminal', desc: 'เข้าสู่ Global Configuration mode' },
    ],
    answer: 'enable\nconfigure terminal',
    commands: [
      { mode: 'exec', pat: ENABLE_PAT, next: 'exec-priv', pr: 'Router#', adv: false, msg: '' },
      { mode: 'exec-priv', pat: CONFT_PAT, next: 'config', pr: 'Router(config)#', adv: true, msg: 'Enter configuration commands, one per line.\nRouter(config)#' },
    ],
  },
  {
    id: 22,
    router: 'R2',
    name: 'R2 — ตั้งชื่อ hostname',
    short: 'hostname R2',
    mode: 'config',
    prompt: 'Router(config)#',
    cmdHint: { cmd: 'Router(config)# hostname R2', desc: 'ตั้งชื่ออุปกรณ์เป็น R2 — Router ตัวนี้จะเป็น ASBR ที่ต้องคุยทั้ง OSPF และ EIGRP' },
    hints: [{ cmd: 'Router(config)# hostname R2', desc: 'ตั้งชื่ออุปกรณ์เป็น R2' }],
    answer: 'hostname R2',
    commands: [{ mode: 'config', pat: hostnamePat('R2'), next: 'config', pr: 'R2(config)#', adv: true, msg: '✓ Hostname เปลี่ยนเป็น R2 แล้วครับ' }],
  },
  {
    id: 5,
    router: 'R2',
    name: 'R2 — g0/0 (←R1) 172.25.2.2/30 (ฝั่ง OSPF)',
    short: 'g0/0 ←R1',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# interface g0/0', desc: 'ฝั่ง R1 (โซน OSPF): 172.25.2.2/30' },
    hints: [
      { cmd: 'R2(config)# interface g0/0', desc: 'ฝั่ง R1: 172.25.2.2/30' },
      { cmd: 'R2(config-if)# ip address 172.25.2.2 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R2(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R2(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/0\nip address 172.25.2.2 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('0'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('172.25.2.2', '255.255.255.252'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to up' },
      { mode: 'config-if', pat: EXIT_PAT, next: 'config', pr: 'R2(config)#', adv: true, msg: '✓ g0/0 → 172.25.2.2/30 UP' },
    ],
  },
  {
    id: 6,
    router: 'R2',
    name: 'R2 — g0/1 (→R3) 172.25.2.5/30 (ฝั่ง EIGRP)',
    short: 'g0/1 →R3',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# interface g0/1', desc: 'ฝั่ง R3 (โซนที่จะใช้ EIGRP): 172.25.2.5/30 — เส้น R2—R3 จะเขียว' },
    hints: [
      { cmd: 'R2(config)# interface g0/1', desc: 'ฝั่ง R3: 172.25.2.5/30 — เส้น R2—R3 จะเขียว' },
      { cmd: 'R2(config-if)# ip address 172.25.2.5 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R2(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R2(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/1\nip address 172.25.2.5 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('1'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('172.25.2.5', '255.255.255.252'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to up' },
      {
        mode: 'config-if',
        pat: EXIT_PAT,
        next: 'config',
        pr: 'R2(config)#',
        adv: true,
        msg: '✓ g0/1 → 172.25.2.5/30 UP\n  เส้น R2—R3 เขียวแล้วครับ — สลับไปตั้ง IP ของ R3 ต่อได้เลยครับ',
      },
    ],
  },
  {
    id: 7,
    router: 'R3',
    name: 'R3 — enable & configure terminal',
    short: 'R3 enable',
    mode: 'exec',
    prompt: 'Router>',
    cmdHint: { cmd: 'Router> enable', desc: 'สลับไปทำ R3 — enable แล้ว configure terminal' },
    hints: [
      { cmd: 'Router> enable', desc: 'สลับไปทำ R3 — เข้าสู่ Privileged EXEC' },
      { cmd: 'Router# configure terminal', desc: 'เข้าสู่ Global Configuration mode' },
    ],
    answer: 'enable\nconfigure terminal',
    commands: [
      { mode: 'exec', pat: ENABLE_PAT, next: 'exec-priv', pr: 'Router#', adv: false, msg: '' },
      { mode: 'exec-priv', pat: CONFT_PAT, next: 'config', pr: 'Router(config)#', adv: true, msg: 'Enter configuration commands, one per line.\nRouter(config)#' },
    ],
  },
  {
    id: 23,
    router: 'R3',
    name: 'R3 — ตั้งชื่อ hostname',
    short: 'hostname R3',
    mode: 'config',
    prompt: 'Router(config)#',
    cmdHint: { cmd: 'Router(config)# hostname R3', desc: 'ตั้งชื่ออุปกรณ์เป็น R3' },
    hints: [{ cmd: 'Router(config)# hostname R3', desc: 'ตั้งชื่ออุปกรณ์เป็น R3' }],
    answer: 'hostname R3',
    commands: [{ mode: 'config', pat: hostnamePat('R3'), next: 'config', pr: 'R3(config)#', adv: true, msg: '✓ Hostname เปลี่ยนเป็น R3 แล้วครับ' }],
  },
  {
    id: 8,
    router: 'R3',
    name: 'R3 — g0/0 (←R2) 172.25.2.6/30 (ฝั่ง EIGRP)',
    short: 'g0/0 ←R2',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# interface g0/0', desc: 'ฝั่ง R2 (โซน EIGRP): 172.25.2.6/30' },
    hints: [
      { cmd: 'R3(config)# interface g0/0', desc: 'ฝั่ง R2: 172.25.2.6/30' },
      { cmd: 'R3(config-if)# ip address 172.25.2.6 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R3(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R3(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/0\nip address 172.25.2.6 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('0'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('172.25.2.6', '255.255.255.252'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to up' },
      { mode: 'config-if', pat: EXIT_PAT, next: 'config', pr: 'R3(config)#', adv: true, msg: '✓ g0/0 → 172.25.2.6/30 UP' },
    ],
  },
  {
    id: 9,
    router: 'R3',
    name: 'R3 — g0/1 LAN 172.25.3.1/24',
    short: 'g0/1 LAN',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# interface g0/1', desc: 'LAN ฝั่ง PC-C: 172.25.3.1/24 — เส้น R3—PC-C จะเขียว' },
    hints: [
      { cmd: 'R3(config)# interface g0/1', desc: 'LAN ฝั่ง PC-C: 172.25.3.1/24 — เส้น R3—PC-C จะเขียว' },
      { cmd: 'R3(config-if)# ip address 172.25.3.1 255.255.255.0', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R3(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R3(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/1\nip address 172.25.3.1 255.255.255.0\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('1'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('172.25.3.1', '255.255.255.0'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to up' },
      {
        mode: 'config-if',
        pat: EXIT_PAT,
        next: 'config',
        pr: 'R3(config)#',
        adv: true,
        msg: '✓ g0/1 → 172.25.3.1/24 UP\n  ต่อไปตั้งค่า PC-C ให้ครบตามหลักการก่อนครับ',
      },
    ],
  },
  {
    id: 201,
    router: 'PC-C',
    type: 'pcconfig',
    name: 'PC-C — ตั้งค่า IP / Subnet / Gateway',
    short: 'PC-C config',
    mode: 'pcconfig',
    prompt: '(คลิก PC-C)',
    expected: { ip: '172.25.3.10', mask: '255.255.255.0', gateway: '172.25.3.1' },
    cmdHint: { cmd: '(คลิกที่ไอคอน PC-C บนแผนภาพด้านบน)', desc: 'กำหนด IP/Subnet/Gateway ให้ PC-C ผ่านหน้าต่างตั้งค่า' },
  },

  // ── เฟส 2: ตั้งค่า OSPF บน R1 (ฝั่งซ้ายของ R2) — R1 ทำก่อน จึงยังไม่มี Neighbor ──
  {
    id: 10,
    router: 'R1',
    name: 'R1 — เปิดใช้งาน OSPF (Process ID 1)',
    short: 'OSPF setup',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# router ospf 1', desc: 'เข้าสู่โหมดตั้งค่า OSPF — เลข Process ID (1) มีผลแค่ภายใน Router เครื่องนี้' },
    hints: [
      { cmd: 'R1(config)# router ospf 1', desc: 'เข้าสู่โหมดตั้งค่า OSPF ด้วย Process ID 1' },
      { cmd: 'R1(config-router)# network 172.25.1.0 0.0.0.255 area 0', desc: 'ประกาศ network ฝั่ง PC-A ด้วย wildcard mask — วง LAN นี้เป็น /24 ให้หา inverse เอง พร้อม Area 0' },
      { cmd: 'R1(config-router)# network 172.25.2.0 0.0.0.3 area 0', desc: 'ประกาศ network ฝั่ง R2 ด้วย wildcard mask — ลิงก์นี้เป็น /30 ให้หา inverse เอง พร้อม Area 0' },
    ],
    answer: 'router ospf 1\nnetwork 172.25.1.0 0.0.0.255 area 0\nnetwork 172.25.2.0 0.0.0.3 area 0',
    commands: [
      { mode: 'config', pat: routerOspfPat('1'), next: 'config-router', pr: 'R1(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: networkAreaPat('172.25.1.0', '0.0.0.255', '0'), next: 'config-router', pr: 'R1(config-router)#', adv: false, msg: '' },
      {
        mode: 'config-router',
        pat: networkAreaPat('172.25.2.0', '0.0.0.3', '0'),
        next: 'config',
        pr: 'R1(config)#',
        adv: true,
        msg: '✓ เปิด OSPF (Process ID 1) บน R1 แล้วครับ — ประกาศ network ทั้ง 2 ฝั่งใน Area 0',
      },
    ],
  },
  {
    id: 11,
    router: 'R1',
    name: 'R1 — ตรวจสอบด้วย show ip protocols (Checkpoint)',
    short: 'show protocols',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# do show ip protocols', desc: 'ตรวจสอบว่า OSPF process กำลังทำงานอยู่ก่อน save (R1 ทำก่อน R2 จึงยังไม่มี Neighbor ให้ดู)' },
    answer: 'do show ip protocols',
    commands: [
      {
        mode: 'config',
        pat: SHOW_IP_PROTOCOLS_PAT,
        next: 'config',
        pr: 'R1(config)#',
        adv: true,
        msg: 'Routing Protocol is "ospf 1"\n  Router ID 172.25.2.1\n  Number of areas in this router is 1. 1 normal 0 stub 0 nssa\n  Routing for Networks:\n    172.25.1.0 0.0.0.255 area 0\n    172.25.2.0 0.0.0.3 area 0\n  Distance: (default is 110)\n\n✓ OSPF process กำลังทำงานอยู่ครับ — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },
  {
    id: 12,
    router: 'R1',
    name: 'R1 — end & write memory',
    short: 'save R1',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# end  →  write memory', desc: 'บันทึก config R1' },
    hints: [
      { cmd: 'R1(config)# end', desc: 'ออกจาก config mode (end หรือ exit ก็ได้)' },
      { cmd: 'R1# write memory', desc: 'บันทึก config R1 ที่ตั้งค่าไว้ให้ถาวร' },
    ],
    answer: 'end\nwrite memory',
    commands: [
      { mode: 'config', pat: END_OR_EXIT_PAT, next: 'exec-priv', pr: 'R1#', adv: false, msg: 'R1#' },
      { mode: 'exec-priv', pat: writeMemPat(), next: 'exec-priv', pr: 'R1#', adv: true, msg: 'Building configuration...\n[OK]\n✓ R1 config บันทึกแล้วครับ — สลับไปทำ R3 ต่อครับ' },
    ],
  },

  // ── เฟส 2 (ต่อ): ตั้งค่า EIGRP บน R3 (ฝั่งขวาของ R2) — R3 ทำก่อน จึงยังไม่มี Neighbor ──
  {
    id: 13,
    router: 'R3',
    name: 'R3 — เปิดใช้งาน EIGRP (AS 100)',
    short: 'EIGRP setup',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# router eigrp 100', desc: 'เข้าสู่โหมดตั้งค่า EIGRP บน Autonomous System 100' },
    hints: [
      { cmd: 'R3(config)# router eigrp 100', desc: 'เข้าสู่โหมดตั้งค่า EIGRP บน Autonomous System 100 (ต้องตรงกับ R2 เสมอ ต่างจาก OSPF Process ID)' },
      { cmd: 'R3(config-router)# network 172.25.2.4 0.0.0.3', desc: 'ประกาศ network ฝั่ง R2 ด้วย wildcard mask — ลิงก์นี้เป็น /30 ให้หา inverse เอง' },
      { cmd: 'R3(config-router)# network 172.25.3.0 0.0.0.255', desc: 'ประกาศ network ฝั่ง PC-C ด้วย wildcard mask — วง LAN นี้เป็น /24 ให้หา inverse เอง' },
      { cmd: 'R3(config-router)# no auto-summary', desc: 'ปิดการสรุป subnet อัตโนมัติที่ classful boundary' },
    ],
    answer: 'router eigrp 100\nnetwork 172.25.2.4 0.0.0.3\nnetwork 172.25.3.0 0.0.0.255\nno auto-summary',
    commands: [
      { mode: 'config', pat: routerEigrpPat('100'), next: 'config-router', pr: 'R3(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: networkWildcardPat('172.25.2.4', '0.0.0.3'), next: 'config-router', pr: 'R3(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: networkWildcardPat('172.25.3.0', '0.0.0.255'), next: 'config-router', pr: 'R3(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: NOAUTOSUM_PAT, next: 'config', pr: 'R3(config)#', adv: true, msg: '✓ เปิด EIGRP (AS 100) บน R3 แล้วครับ — ประกาศ network ทั้ง 2 ฝั่งพร้อมปิด auto-summary' },
    ],
  },
  {
    id: 14,
    router: 'R3',
    name: 'R3 — ตรวจสอบด้วย show ip protocols (Checkpoint)',
    short: 'show protocols',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# do show ip protocols', desc: 'ตรวจสอบว่า EIGRP process กำลังทำงานอยู่ก่อน save (R3 ทำก่อน R2 จึงยังไม่มี Neighbor ให้ดู)' },
    answer: 'do show ip protocols',
    commands: [
      {
        mode: 'config',
        pat: SHOW_IP_PROTOCOLS_PAT,
        next: 'config',
        pr: 'R3(config)#',
        adv: true,
        msg: 'Routing Protocol is "eigrp 100"\n  EIGRP-IPv4 Protocol for AS(100)\n    Automatic Summarization: disabled\n    Routing for Networks:\n      172.25.2.4/30\n      172.25.3.0/24\n    Distance: internal 90 external 170\n\n✓ EIGRP process กำลังทำงานอยู่ครับ — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },
  {
    id: 15,
    router: 'R3',
    name: 'R3 — end & write memory',
    short: 'save R3',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# end  →  write memory', desc: 'บันทึก config R3 ที่ตั้งค่าไว้ให้ถาวร' },
    hints: [
      { cmd: 'R3(config)# end', desc: 'ออกจาก config mode (end หรือ exit ก็ได้)' },
      { cmd: 'R3# write memory', desc: 'บันทึก config R3 ที่ตั้งค่าไว้ให้ถาวร' },
    ],
    answer: 'end\nwrite memory',
    commands: [
      { mode: 'config', pat: END_OR_EXIT_PAT, next: 'exec-priv', pr: 'R3#', adv: false, msg: 'R3#' },
      { mode: 'exec-priv', pat: writeMemPat(), next: 'exec-priv', pr: 'R3#', adv: true, msg: 'Building configuration...\n[OK]\n✓ R3 config บันทึกแล้วครับ — สลับไปทำ R2 ต่อครับ' },
    ],
  },

  // ── เฟส 3: R2 เปิดทั้ง OSPF และ EIGRP (ตอนนี้ Neighbor จะขึ้นทันทีทั้งสองฝั่ง เพราะ R1/R3 ตั้งไว้ก่อนแล้ว) ──
  {
    id: 16,
    router: 'R2',
    name: 'R2 — เปิดใช้งาน OSPF (Process ID 2, ฝั่ง R1)',
    short: 'OSPF setup',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: {
      cmd: 'R2(config)# router ospf 2',
      desc: 'เข้าสู่โหมดตั้งค่า OSPF ด้วย Process ID 2 (ไม่ต้องตรงกับ R1 ที่ใช้ 1 — Locally Significant) — ประกาศเฉพาะฝั่งที่ต่อกับ R1 เท่านั้น',
    },
    hints: [
      { cmd: 'R2(config)# router ospf 2', desc: 'เข้าสู่โหมดตั้งค่า OSPF — คนละ Process ID กับ R1 ก็ได้' },
      {
        cmd: 'R2(config-router)# network 172.25.2.0 0.0.0.3 area 0',
        desc: 'ประกาศเฉพาะ interface ฝั่ง R1 ด้วย wildcard mask — ลิงก์นี้เป็น /30 ให้หา inverse เอง พร้อม Area 0 — ฝั่ง R3 เป็น EIGRP ไม่เกี่ยวกับ OSPF',
      },
    ],
    answer: 'router ospf 2\nnetwork 172.25.2.0 0.0.0.3 area 0',
    commands: [
      { mode: 'config', pat: routerOspfPat('2'), next: 'config-router', pr: 'R2(config-router)#', adv: false, msg: '' },
      {
        mode: 'config-router',
        pat: networkAreaPat('172.25.2.0', '0.0.0.3', '0'),
        next: 'config',
        pr: 'R2(config)#',
        adv: true,
        msg: '✓ เปิด OSPF (Process ID 2) บน R2 แล้วครับ — ประกาศเฉพาะฝั่ง R1',
      },
    ],
  },
  {
    id: 17,
    router: 'R2',
    name: 'R2 — ตรวจสอบ Neighbor ด้วย show ip ospf neighbor (Checkpoint)',
    short: 'show ospf nb',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# do show ip ospf neighbor', desc: 'ตรวจสอบว่า R2 เจอ Neighbor (R1) ผ่าน OSPF แล้ว — R1 config ไว้ก่อนแล้ว จึงควรเห็น Neighbor ทันที' },
    answer: 'do show ip ospf neighbor',
    commands: [
      {
        mode: 'config',
        pat: SHOW_OSPF_NEIGHBOR_PAT,
        next: 'config',
        pr: 'R2(config)#',
        adv: true,
        msg: 'Neighbor ID     Pri   State           Dead Time   Address         Interface\n172.25.2.1        1   FULL/BDR        00:00:35    172.25.2.1      GigabitEthernet0/0\n\n✓ เห็น Neighbor R1 (Router ID 172.25.2.1) ผ่าน OSPF แล้วครับ — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },
  {
    id: 18,
    router: 'R2',
    name: 'R2 — เปิดใช้งาน EIGRP (AS 100, ฝั่ง R3)',
    short: 'EIGRP setup',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: {
      cmd: 'R2(config)# router eigrp 100',
      desc: 'เข้าสู่โหมดตั้งค่า EIGRP บน Autonomous System 100 (ต้องตรงกับ R3) — ประกาศเฉพาะฝั่งที่ต่อกับ R3 เท่านั้น',
    },
    hints: [
      { cmd: 'R2(config)# router eigrp 100', desc: 'เข้าสู่โหมดตั้งค่า EIGRP — AS Number ต้องตรงกับ R3 (100) เสมอ' },
      {
        cmd: 'R2(config-router)# network 172.25.2.4 0.0.0.3',
        desc: 'ประกาศเฉพาะ interface ฝั่ง R3 ด้วย wildcard mask — ลิงก์นี้เป็น /30 ให้หา inverse เอง — ฝั่ง R1 เป็น OSPF ไม่เกี่ยวกับ EIGRP',
      },
      { cmd: 'R2(config-router)# no auto-summary', desc: 'ปิดการสรุป subnet อัตโนมัติที่ classful boundary' },
    ],
    answer: 'router eigrp 100\nnetwork 172.25.2.4 0.0.0.3\nno auto-summary',
    commands: [
      { mode: 'config', pat: routerEigrpPat('100'), next: 'config-router', pr: 'R2(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: networkWildcardPat('172.25.2.4', '0.0.0.3'), next: 'config-router', pr: 'R2(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: NOAUTOSUM_PAT, next: 'config', pr: 'R2(config)#', adv: true, msg: '✓ เปิด EIGRP (AS 100) บน R2 แล้วครับ — ประกาศเฉพาะฝั่ง R3' },
    ],
  },
  {
    id: 19,
    router: 'R2',
    name: 'R2 — ตรวจสอบ Neighbor ด้วย show ip eigrp neighbors (Checkpoint)',
    short: 'show eigrp nb',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# do show ip eigrp neighbors', desc: 'ตรวจสอบว่า R2 เจอ Neighbor (R3) ผ่าน EIGRP แล้ว — R3 config ไว้ก่อนแล้ว จึงควรเห็น Neighbor ทันที' },
    answer: 'do show ip eigrp neighbors',
    commands: [
      {
        mode: 'config',
        pat: SHOW_EIGRP_NEIGHBORS_PAT,
        next: 'config',
        pr: 'R2(config)#',
        adv: true,
        msg: 'EIGRP-IPv4 Neighbors for AS(100)\nH   Address         Interface    Hold Uptime   SRTT   RTO  Q  Seq\n0   172.25.2.6      Gi0/1        13   00:00:05  1     200  0  3\n\n✓ เห็น Neighbor R3 (172.25.2.6) ผ่าน EIGRP แล้วครับ ตอนนี้ R2 คุยได้ทั้ง OSPF และ EIGRP พร้อมกันแล้ว — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },

  // ── เฟส 4: จุดสำคัญของ Lab นี้ — ตรวจสอบ "ก่อน" Redistribute แล้วค่อยแก้ปัญหา ──
  {
    id: 100,
    router: 'R1',
    name: 'R1 — ตรวจสอบก่อน Redistribute (show ip route)',
    short: 'route ก่อน redist',
    mode: 'exec-priv',
    prompt: 'R1#',
    cmdHint: {
      cmd: 'R1# show ip route',
      desc: 'สังเกตให้ดี: R1 ยังไม่เห็น network 172.25.3.0/24 (ของ PC-C) เลย ทั้งที่ R2 (Neighbor ของเรา) ต่อกับมันโดยตรง — เพราะ R2 ยังไม่ได้ Redistribute เส้นทางจาก EIGRP เข้ามาใน OSPF',
    },
    answer: 'show ip route',
    commands: [
      {
        mode: 'exec-priv',
        pat: SHOW_IP_ROUTE_PAT,
        next: 'exec-priv',
        pr: 'R1#',
        adv: true,
        msg: 'Codes: L - local, C - connected, O - OSPF\n\nC    172.25.1.0/24 is directly connected, GigabitEthernet0/0\nC    172.25.2.0/30 is directly connected, GigabitEthernet0/1\n\n✗ สังเกตว่ายังไม่มี network 172.25.3.0/24 (ของ PC-C) เลย ทั้งที่ R2 ต่อกับมันโดยตรงผ่าน EIGRP! เพราะ R1 รู้จักแค่โลกของ OSPF เท่านั้น ต้องให้ R2 (ASBR) redistribute เส้นทางจาก EIGRP เข้ามาใน OSPF ก่อนถึงจะเห็น — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },
  {
    id: 20,
    router: 'R2',
    name: 'R2 — Redistribute ข้าม Protocol ทั้งสองทาง',
    short: 'Redistribute',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# router ospf 2', desc: 'กลับเข้าโหมด OSPF (Process 2) เพื่อดึงเส้นทางจาก EIGRP เข้ามา' },
    hints: [
      { cmd: 'R2(config)# router ospf 2', desc: 'กลับเข้าโหมดตั้งค่า OSPF Process ID 2 ที่มีอยู่แล้ว' },
      {
        cmd: 'R2(config-router)# redistribute eigrp 100 subnets',
        desc: 'ดึงเส้นทางจาก EIGRP AS 100 เข้ามาประกาศใน OSPF — ต้องมีคำว่า "subnets" ต่อท้ายเสมอ ไม่งั้น OSPF จะดึงมาแค่ major network แบบ classful เท่านั้น (172.25.3.0/24 เป็น subnet จะถูกข้ามไปเงียบๆ)',
      },
      { cmd: 'R2(config-router)# exit', desc: 'ออกจากโหมด OSPF กลับสู่ Global Config' },
      { cmd: 'R2(config)# router eigrp 100', desc: 'เข้าโหมด EIGRP AS 100 ที่มีอยู่แล้ว เพื่อดึงเส้นทางจาก OSPF เข้ามาเช่นกัน' },
      {
        cmd: 'R2(config-router)# redistribute ospf 2 metric 10000 100 255 1 1500',
        desc: 'ดึงเส้นทางจาก OSPF Process 2 เข้ามาใน EIGRP — EIGRP ต้องระบุ Seed Metric เอง 5 ค่าตามลำดับ Bandwidth Delay Reliability Load MTU ให้พิมพ์เป็น 10000 100 255 1 1500 (ค่ามาตรฐานที่ใช้ในแล็บนี้) เพราะแปลง Metric จาก Protocol อื่นให้อัตโนมัติไม่ได้',
      },
      { cmd: 'R2(config-router)# exit', desc: 'ออกจากโหมด EIGRP กลับสู่ Global Config' },
    ],
    answer: 'router ospf 2\nredistribute eigrp 100 subnets\nexit\nrouter eigrp 100\nredistribute ospf 2 metric 10000 100 255 1 1500\nexit',
    commands: [
      { mode: 'config', pat: routerOspfPat('2'), next: 'config-router', pr: 'R2(config-router)#', adv: false, msg: '' },
      {
        mode: 'config-router',
        pat: redistributeIntoOspfPat('eigrp', '100'),
        next: 'config-router',
        pr: 'R2(config-router)#',
        adv: false,
        msg: '✓ Redistribute EIGRP เข้า OSPF แล้ว (พร้อม subnets เพื่อดึง subnet ที่ไม่ใช่ classful มาด้วย)',
      },
      { mode: 'config-router', pat: EXIT_PAT, next: 'config', pr: 'R2(config)#', adv: false, msg: '' },
      { mode: 'config', pat: routerEigrpPat('100'), next: 'config-router', pr: 'R2(config-router)#', adv: false, msg: '' },
      {
        mode: 'config-router',
        pat: redistributeIntoEigrpPat('ospf', '2', '10000', '100', '255', '1', '1500'),
        next: 'config-router',
        pr: 'R2(config-router)#',
        adv: false,
        msg: '✓ Redistribute OSPF เข้า EIGRP แล้ว (พร้อม Seed Metric เพราะ EIGRP แปลง Metric จาก Protocol อื่นเองไม่ได้)',
      },
      {
        mode: 'config-router',
        pat: EXIT_PAT,
        next: 'config',
        pr: 'R2(config)#',
        adv: true,
        msg: '✓ Redistribute ครบทั้งสองทางแล้วครับ — R1 และ R3 จะเริ่มมองเห็นเครือข่ายของอีกฝั่งได้แล้ว',
      },
    ],
  },
  {
    id: 101,
    router: 'R2',
    name: 'R2 — end & write memory',
    short: 'save R2',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# end  →  write memory', desc: 'บันทึก config R2 (รวม Redistribution) ให้ถาวร' },
    hints: [
      { cmd: 'R2(config)# end', desc: 'ออกจาก config mode (end หรือ exit ก็ได้)' },
      { cmd: 'R2# write memory', desc: 'บันทึก config R2 ที่ตั้งค่าไว้ให้ถาวร' },
    ],
    answer: 'end\nwrite memory',
    commands: [
      { mode: 'config', pat: END_OR_EXIT_PAT, next: 'exec-priv', pr: 'R2#', adv: false, msg: 'R2#' },
      { mode: 'exec-priv', pat: writeMemPat(), next: 'exec-priv', pr: 'R2#', adv: true, msg: 'Building configuration...\n[OK]\n✓ R2 config บันทึกแล้วครับ — สลับไปทำ R1 ต่อเพื่อตรวจผลลัพธ์ครับ' },
    ],
  },
  {
    id: 102,
    router: 'R1',
    name: 'R1 — ตรวจสอบหลัง Redistribute (show ip route)',
    short: 'route หลัง redist',
    mode: 'exec-priv',
    prompt: 'R1#',
    cmdHint: { cmd: 'R1# show ip route', desc: 'เช็คอีกครั้ง — คราวนี้ควรเห็น network 172.25.3.0/24 โผล่มาแล้ว ผ่านเส้นทางแบบ OSPF External (O E2)' },
    answer: 'show ip route',
    commands: [
      {
        mode: 'exec-priv',
        pat: SHOW_IP_ROUTE_PAT,
        next: 'exec-priv',
        pr: 'R1#',
        adv: true,
        msg: 'Codes: L - local, C - connected, O - OSPF, O E2 - OSPF external type 2\n\nC    172.25.1.0/24 is directly connected, GigabitEthernet0/0\nC    172.25.2.0/30 is directly connected, GigabitEthernet0/1\nO E2 172.25.3.0/24 [110/20] via 172.25.2.2, 00:00:10, GigabitEthernet0/1\n\n✓ เห็น network 172.25.3.0/24 โผล่มาเป็น O E2 (OSPF External) แล้วครับ! นี่คือผลของการ Redistribute — R2 แปลงเส้นทางจาก EIGRP ให้ R1 เข้าใจได้ผ่าน OSPF',
      },
    ],
  },
  {
    id: 103,
    router: 'PC-A',
    type: 'pcping',
    name: 'PC-A — ทดสอบ ping ไปยัง PC-C ผ่าน Command Prompt',
    short: 'ping PC-C (PC)',
    mode: 'pcping',
    prompt: '(คลิก PC-A)',
    target: { ip: '172.25.3.10', label: 'PC-C' },
    cmdHint: {
      cmd: '(คลิกที่ไอคอน PC-A บนแผนภาพด้านบน แล้วพิมพ์ ping 172.25.3.10 ในหน้า Command Prompt)',
      desc: 'ทดสอบว่า PC-A คุยกับ PC-C ได้จริงจากมุมมองผู้ใช้งานทั่วไป (ไม่ผ่าน Router) — ยืนยันว่า Redistribution ทำให้ข้ามไปมาระหว่าง 2 Protocol ได้จริง',
    },
  },
];

export const PRETEST: PretestQuestion[] = [
  {
    id: 'q1',
    type: 'mcq',
    q: 'Route Redistribution คืออะไร?',
    opts: [
      'การเพิ่ม Bandwidth ให้ Interface',
      'การสำรอง Router ID ไว้ล่วงหน้า',
      'กระบวนการแปลงและส่งต่อ Route ที่เรียนรู้จาก Routing Protocol หนึ่ง ไปประกาศใน Routing Protocol อีกตัวหนึ่ง',
      'การเข้ารหัส Routing Update',
    ],
    ans: 2,
    exp: 'Redistribution คือการที่ Router ตัวหนึ่ง (ซึ่งรัน 2 Protocol พร้อมกัน เรียกว่า ASBR — Autonomous System Boundary Router) นำ Route ที่เรียนรู้มาจาก Protocol A มาประกาศต่อใน Protocol B เพื่อให้ Network ที่ใช้คนละ Protocol กันมองเห็นเส้นทางถึงกันได้ — ในแล็บนี้ R2 ทำหน้าที่นี้ระหว่าง OSPF (ฝั่ง R1) กับ EIGRP (ฝั่ง R3)',
  },
  {
    id: 'q2',
    type: 'mcq',
    q: 'เพราะเหตุใดคำสั่ง redistribute eigrp 100 subnets ฝั่ง OSPF จึงต้องมีคำว่า "subnets" ต่อท้ายเสมอ?',
    opts: [
      'เพื่อความสวยงามของคำสั่งเท่านั้น ไม่มีผลจริง',
      'เพื่อบังคับให้ใช้ Area 0 เท่านั้น',
      'เพื่อเปลี่ยน Router ID ของ Router',
      'ถ้าไม่ใส่ subnets, OSPF จะดึงมาแค่ major network แบบ classful เท่านั้น — subnet ที่ไม่ตรง classful boundary (เช่น 172.25.3.0/24 ที่เป็นส่วนหนึ่งของ Class B เดิม) จะถูกข้ามไปเงียบๆ',
    ],
    ans: 3,
    exp: 'OSPF ค่า Default ของคำสั่ง redistribute จะดึงมาเฉพาะ Route ที่เป็น Classful Network เท่านั้น หากไม่ใส่ subnets ต่อท้าย Route ที่ถูก Subnet มาแล้ว (เกือบทุก Route ในโลกจริง) จะไม่ถูกดึงเข้ามาเลย โดยไม่มี Error แจ้งเตือนใดๆ — เป็นสาเหตุอันดับ 1 ที่ทำให้ Redistribution "ดูเหมือนไม่ทำงาน" ทั้งที่ config ถูกต้องแล้ว',
  },
  {
    id: 'q3',
    type: 'mcq',
    q: 'ทำไมคำสั่ง redistribute ospf 2 metric 10000 100 255 1 1500 ฝั่ง EIGRP ต้องระบุตัวเลข Metric เอง 5 ค่า ทั้งที่ redistribute ฝั่ง OSPF ไม่ต้องระบุ?',
    opts: [
      'เพราะ EIGRP ใช้ Composite Metric (Bandwidth, Delay, Reliability, Load, MTU) ซึ่งคำนวณจาก Protocol อื่นโดยอัตโนมัติไม่ได้ จึงต้องกำหนด Seed Metric เริ่มต้นให้เอง',
      'เพราะ EIGRP รองรับ Router น้อยกว่า OSPF',
      'เพราะเป็นข้อบังคับของ Cisco IOS เวอร์ชันใหม่เท่านั้น',
      'เพราะ EIGRP ไม่รองรับ Redistribution จริงๆ ต้องใส่ค่าหลอกไว้',
    ],
    ans: 0,
    exp: 'EIGRP ใช้ Metric แบบ Composite ที่รวม Bandwidth + Delay + Reliability + Load + MTU เข้าด้วยกัน ซึ่งเป็นค่าเฉพาะของ EIGRP เอง — เมื่อดึง Route จาก Protocol อื่น (เช่น OSPF ที่ใช้ Cost) เข้ามา EIGRP ไม่มีทางแปลงค่า Cost เป็น Composite Metric ได้เอง จึงบังคับให้ผู้ดูแลระบบกำหนด Seed Metric เริ่มต้นตรงนี้เสมอ ไม่งั้น Redistribute จะไม่สำเร็จ',
  },
  {
    id: 'q4',
    type: 'mcq',
    q: 'Route ที่ถูก Redistribute เข้ามาใน OSPF (จาก Protocol อื่น) จะปรากฏในตาราง Routing Table ด้วยรหัสใด และมี Administrative Distance เท่าไหร่ (ค่า Default)?',
    opts: [
      'O — Administrative Distance 110 เท่า OSPF ปกติ',
      'O E2 — Administrative Distance 110 เช่นกัน (ใช้ External Metric 20 เป็นค่า Default)',
      'E — Administrative Distance 90',
      'O IA — Administrative Distance 170',
    ],
    ans: 1,
    exp: 'Route ที่ถูก Redistribute เข้า OSPF จะแสดงเป็น O E2 (OSPF External Type 2) — Administrative Distance ยังคงเป็น 110 เหมือน OSPF ปกติ แต่ Metric ภายในจะแสดงเป็นค่า External Metric แบบคงที่ (Default 20) ไม่ได้บวกเพิ่มตาม Cost ของแต่ละ Hop เหมือน Route OSPF ปกติ (Type 1 ถึงจะบวกเพิ่ม)',
  },
  {
    id: 'q5',
    type: 'dragdrop',
    q: 'จับคู่คำสั่งกับหน้าที่ของมัน',
    pairs: [
      { left: 'router ospf 2 → redistribute eigrp 100 subnets', right: 'ดึง Route จาก EIGRP AS 100 เข้ามาประกาศใน OSPF (ต้องมี subnets กันตกหล่น Route ที่ไม่ใช่ Classful)' },
      { left: 'router eigrp 100 → redistribute ospf 2 metric 10000 100 255 1 1500', right: 'ดึง Route จาก OSPF Process 2 เข้ามาใน EIGRP พร้อมกำหนด Seed Metric 5 ค่าเอง' },
      { left: 'show ip route (ฝั่ง OSPF) แสดง O E2', right: 'สัญญาณว่า Route นี้มาจากการ Redistribute ไม่ใช่ OSPF ล้วนๆ' },
      { left: 'ASBR (Autonomous System Boundary Router)', right: 'Router ที่เชื่อมต่อและแลกเปลี่ยน Route ระหว่าง 2 Routing Domain ที่ต่าง Protocol กัน (ในแล็บนี้คือ R2)' },
    ],
  },
];

export const INTRO_LINES = [
  { text: '# Ch.10 Redistribution — NETLab', cls: 't-info' },
  { text: '# อ้างอิง: Cisco Networking Academy W10', cls: 't-hint' },
  { text: '# Topology: PC-A—R1—R2—R3—PC-C (OSPF ฝั่ง R1-R2, EIGRP ฝั่ง R2-R3, R2 คือ ASBR)', cls: 't-dim' },
  { text: '# R1: g0/0=172.25.1.1/24  g0/1=172.25.2.1/30', cls: 't-dim' },
  { text: '# R2: g0/0=172.25.2.2/30  g0/1=172.25.2.5/30', cls: 't-dim' },
  { text: '# R3: g0/0=172.25.2.6/30  g0/1=172.25.3.1/24', cls: 't-dim' },
  { text: '# OSPF Process 1/2 (Area 0) ↔ R2 (ASBR) ↔ EIGRP AS 100 — ต้อง Redistribute 2 ทางให้ครบ', cls: 't-dim' },
  { text: '' },
  { text: '# เริ่มที่ R1 — พิมพ์: enable', cls: 't-hint' },
];

export const WELCOME_MSG =
  'สวัสดีครับ! Ch.10 Redistribution\n\nTopology: PC-A—R1—R2—R3—PC-C โดย R1-R2 คุยกันด้วย OSPF และ R2-R3 คุยกันด้วย EIGRP — R2 ทำหน้าที่เป็น ASBR (Autonomous System Boundary Router)\nขั้นตอนแรก: ตั้งชื่อ hostname และ IP ให้ครบทุกอุปกรณ์ก่อน (รวม PC-A, PC-C ด้วย) แล้วเปิด OSPF บน R1/R2 และ EIGRP บน R2/R3 ให้ทำงานได้ก่อน จากนั้นจะเห็นว่า R1 ยังมองไม่เห็นเครือข่ายฝั่ง PC-C เลย (เพราะคนละ Protocol) จนกว่าจะสั่งให้ R2 ทำ Redistribution ทั้ง 2 ทาง รวม 29 steps (มีจุด Checkpoint ก่อน-หลัง Redistribute ให้เห็นความแตกต่างชัดเจน)\n\nทำ Pre-test ก่อนหรือข้ามไป Lab เลยก็ได้ครับ';

export const COMPLETE_CHAT_SUMMARY =
  'ยินดีด้วยครับ! Lab Ch.10 เสร็จสมบูรณ์!\n\nสรุป:\n• R1-R2 คุยกันด้วย OSPF (Area 0), R2-R3 คุยกันด้วย EIGRP (AS 100) — R2 ทำหน้าที่เป็น ASBR\n• ก่อน Redistribute: R1 มองไม่เห็น network ฝั่ง PC-C เลย แม้ R2 จะต่อกับมันโดยตรง เพราะคนละ Protocol กัน\n• สั่ง R2 ให้ redistribute eigrp 100 subnets เข้า OSPF และ redistribute ospf 2 metric ... เข้า EIGRP ทั้ง 2 ทาง\n• หลัง Redistribute: R1 เห็น network ฝั่ง PC-C เป็น O E2 (OSPF External) และ ping ไปถึง PC-C ได้สำเร็จ';
