/* NETLab — Lab 7 (RIP v2) data, ported 1:1 from
   public/labnetwork1/lab07-rip-v2/lab7.html's inline <STEPS>/<NODES>/<LINKS>/
   <PRETEST> globals. Uses real VLSM (LAN /24, WAN /30) under one major network
   172.20.0.0/16, same shared <ConfigLab/> engine as lab05/lab06. */
import {
  CONFT_PAT,
  ENABLE_PAT,
  END_OR_EXIT_PAT,
  EXIT_PAT,
  NOAUTOSUM_PAT,
  NOSHUT_PAT,
  ROUTERRIP_PAT,
  VERSION2_PAT,
  hostnamePat,
  ifpat,
  ipAddrPat,
  networkPat,
  writeMemPat,
} from '../../lib/ciscoPatterns';
import type { PretestQuestion, Step, TopoLink, TopoNode } from '../../types/configLab';

export const NODES: TopoNode[] = [
  { id: 'PC-A', x: 60, role: 'host' },
  { id: 'R1', x: 260, role: 'router' },
  { id: 'R2', x: 460, role: 'router' },
  { id: 'R3', x: 660, role: 'router' },
  { id: 'PC-C', x: 860, role: 'host' },
];

export const LINKS: TopoLink[] = [
  { from: 'PC-A', to: 'R1', subnet: '172.20.1.0/24', if1: '', if2: 'g0/0', activateOnSteps: [2, 200] },
  { from: 'R1', to: 'R2', subnet: '172.20.2.0/30', if1: 'g0/1', if2: 'g0/0', activateOnSteps: [3, 5] },
  { from: 'R2', to: 'R3', subnet: '172.20.2.4/30', if1: 'g0/1', if2: 'g0/0', activateOnSteps: [6, 8] },
  { from: 'R3', to: 'PC-C', subnet: '172.20.3.0/24', if1: 'g0/1', if2: '', activateOnSteps: [9, 201] },
];

export const NODE_IP_LABELS: Record<string, string> = {
  'PC-A': '172.20.1.10',
  R1: '172.20.1.1',
  R2: '172.20.2.5',
  R3: '172.20.3.1',
  'PC-C': '172.20.3.10',
};

export const CONFIG_ROUTER_WORDS = ['version', 'network', 'no', 'auto-summary', 'exit'];

const SHOW_IP_PROTOCOLS_PAT = /^do\s+sh(ow)?\s+ip\s+prot(o(c(o(l(s)?)?)?)?)?$/i;

export const STEPS: Step[] = [
  {
    id: 1,
    router: 'R1',
    name: 'R1 — enable & configure terminal',
    short: 'R1 enable',
    mode: 'exec',
    prompt: 'Router>',
    cmdHint: { cmd: 'Router> enable', desc: 'เข้า Privileged EXEC ก่อน แล้วพิมพ์ configure terminal' },
    hints: [
      { cmd: 'Router> enable', desc: 'เข้าสู่ Privileged EXEC mode ก่อน' },
      { cmd: 'Router# configure terminal', desc: 'เข้าสู่ Global Configuration mode' },
    ],
    answer: 'enable\nconfigure terminal',
    commands: [
      { mode: 'exec', pat: ENABLE_PAT, next: 'exec-priv', pr: 'Router#', adv: false, msg: '' },
      { mode: 'exec-priv', pat: CONFT_PAT, next: 'config', pr: 'Router(config)#', adv: true, msg: 'Enter configuration commands, one per line.\nRouter(config)#' },
    ],
  },
  {
    id: 21,
    router: 'R1',
    name: 'R1 — ตั้งชื่อ hostname',
    short: 'hostname R1',
    mode: 'config',
    prompt: 'Router(config)#',
    cmdHint: { cmd: 'Router(config)# hostname R1', desc: 'ตั้งชื่ออุปกรณ์เป็น R1 — ควรทำเป็นอย่างแรกก่อนตั้งค่าอื่น' },
    hints: [{ cmd: 'Router(config)# hostname R1', desc: 'ตั้งชื่ออุปกรณ์เป็น R1' }],
    answer: 'hostname R1',
    commands: [{ mode: 'config', pat: hostnamePat('R1'), next: 'config', pr: 'R1(config)#', adv: true, msg: '✓ Hostname เปลี่ยนเป็น R1 แล้วครับ (สังเกต prompt ที่เปลี่ยนไป)' }],
  },
  {
    id: 2,
    router: 'R1',
    name: 'R1 — g0/0 LAN 172.20.1.1/24',
    short: 'g0/0 LAN',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# interface g0/0', desc: 'LAN ฝั่ง PC-A: 172.20.1.1/24 — เส้น PC-A—R1 จะเขียว' },
    hints: [
      { cmd: 'R1(config)# interface g0/0', desc: 'LAN ฝั่ง PC-A: 172.20.1.1/24 — เส้น PC-A—R1 จะเขียว' },
      { cmd: 'R1(config-if)# ip address 172.20.1.1 255.255.255.0', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R1(config-if)# no shutdown', desc: 'เปิดใช้งาน interface (ไม่งั้นจะ down ตลอด)' },
      { cmd: 'R1(config-if)# exit', desc: 'ออกจาก interface mode กลับสู่ config mode' },
    ],
    answer: 'interface g0/0\nip address 172.20.1.1 255.255.255.0\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('0'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('172.20.1.1', '255.255.255.0'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to up' },
      { mode: 'config-if', pat: EXIT_PAT, next: 'config', pr: 'R1(config)#', adv: true, msg: '✓ g0/0 → 172.20.1.1/24 UP\n  เส้น PC-A—R1 เขียวครึ่งเดียว รอ PC-A ตั้ง IP ด้วยครับ' },
    ],
  },
  {
    id: 3,
    router: 'R1',
    name: 'R1 — g0/1 WAN 172.20.2.1/30',
    short: 'g0/1 WAN',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# interface g0/1', desc: 'WAN ฝั่ง R2: 172.20.2.1/30 (VLSM — เล็กกว่า LAN เพราะมีแค่ 2 host) — เส้น R1—R2 จะเขียว' },
    hints: [
      { cmd: 'R1(config)# interface g0/1', desc: 'WAN ฝั่ง R2: 172.20.2.1/30 — เส้น R1—R2 จะเขียว' },
      { cmd: 'R1(config-if)# ip address 172.20.2.1 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้ (ใช้ /30 แบบ VLSM สำหรับลิงก์จุดต่อจุด)' },
      { cmd: 'R1(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R1(config-if)# exit', desc: 'ออกจาก interface mode กลับสู่ config mode' },
    ],
    answer: 'interface g0/1\nip address 172.20.2.1 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('1'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('172.20.2.1', '255.255.255.252'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to up' },
      {
        mode: 'config-if',
        pat: EXIT_PAT,
        next: 'config',
        pr: 'R1(config)#',
        adv: true,
        msg: '✓ g0/1 → 172.20.2.1/30 UP\n  เส้น R1—R2 เขียวแล้วครับ — ต่อไปตั้งค่า PC-A ก่อน แล้วค่อยไปตั้ง IP ของ R2',
      },
    ],
  },
  {
    id: 200,
    router: 'PC-A',
    type: 'pcconfig',
    name: 'PC-A — ตั้งค่า IP / Subnet / Gateway',
    short: 'PC-A config',
    mode: 'pcconfig',
    prompt: '(คลิก PC-A)',
    expected: { ip: '172.20.1.10', mask: '255.255.255.0', gateway: '172.20.1.1' },
    cmdHint: { cmd: '(คลิกที่ไอคอน PC-A บนแผนภาพด้านบน)', desc: 'กำหนด IP/Subnet/Gateway ให้ PC-A ผ่านหน้าต่างตั้งค่า' },
  },
  {
    id: 4,
    router: 'R2',
    name: 'R2 — enable & configure terminal',
    short: 'R2 enable',
    mode: 'exec',
    prompt: 'Router>',
    cmdHint: { cmd: 'Router> enable', desc: 'สลับไปทำ R2 — enable แล้ว configure terminal' },
    hints: [
      { cmd: 'Router> enable', desc: 'สลับไปทำ R2 — เข้าสู่ Privileged EXEC' },
      { cmd: 'Router# configure terminal', desc: 'เข้าสู่ Global Configuration mode' },
    ],
    answer: 'enable\nconfigure terminal',
    commands: [
      { mode: 'exec', pat: ENABLE_PAT, next: 'exec-priv', pr: 'Router#', adv: false, msg: '' },
      { mode: 'exec-priv', pat: CONFT_PAT, next: 'config', pr: 'Router(config)#', adv: true, msg: 'Enter configuration commands, one per line.\nRouter(config)#' },
    ],
  },
  {
    id: 22,
    router: 'R2',
    name: 'R2 — ตั้งชื่อ hostname',
    short: 'hostname R2',
    mode: 'config',
    prompt: 'Router(config)#',
    cmdHint: { cmd: 'Router(config)# hostname R2', desc: 'ตั้งชื่ออุปกรณ์เป็น R2' },
    hints: [{ cmd: 'Router(config)# hostname R2', desc: 'ตั้งชื่ออุปกรณ์เป็น R2' }],
    answer: 'hostname R2',
    commands: [{ mode: 'config', pat: hostnamePat('R2'), next: 'config', pr: 'R2(config)#', adv: true, msg: '✓ Hostname เปลี่ยนเป็น R2 แล้วครับ' }],
  },
  {
    id: 5,
    router: 'R2',
    name: 'R2 — g0/0 (←R1) 172.20.2.2/30',
    short: 'g0/0 ←R1',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# interface g0/0', desc: 'ฝั่ง R1: 172.20.2.2/30' },
    hints: [
      { cmd: 'R2(config)# interface g0/0', desc: 'ฝั่ง R1: 172.20.2.2/30' },
      { cmd: 'R2(config-if)# ip address 172.20.2.2 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R2(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R2(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/0\nip address 172.20.2.2 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('0'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('172.20.2.2', '255.255.255.252'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to up' },
      { mode: 'config-if', pat: EXIT_PAT, next: 'config', pr: 'R2(config)#', adv: true, msg: '✓ g0/0 → 172.20.2.2/30 UP' },
    ],
  },
  {
    id: 6,
    router: 'R2',
    name: 'R2 — g0/1 (→R3) 172.20.2.5/30',
    short: 'g0/1 →R3',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# interface g0/1', desc: 'ฝั่ง R3: 172.20.2.5/30 (คนละ /30 subnet กับฝั่ง R1 แม้อยู่ major network เดียวกัน) — เส้น R2—R3 จะเขียว' },
    hints: [
      { cmd: 'R2(config)# interface g0/1', desc: 'ฝั่ง R3: 172.20.2.5/30 — เส้น R2—R3 จะเขียว' },
      { cmd: 'R2(config-if)# ip address 172.20.2.5 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R2(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R2(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/1\nip address 172.20.2.5 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('1'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('172.20.2.5', '255.255.255.252'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to up' },
      {
        mode: 'config-if',
        pat: EXIT_PAT,
        next: 'config',
        pr: 'R2(config)#',
        adv: true,
        msg: '✓ g0/1 → 172.20.2.5/30 UP\n  เส้น R2—R3 เขียวแล้วครับ — สลับไปตั้ง IP ของ R3 ต่อได้เลยครับ',
      },
    ],
  },
  {
    id: 7,
    router: 'R3',
    name: 'R3 — enable & configure terminal',
    short: 'R3 enable',
    mode: 'exec',
    prompt: 'Router>',
    cmdHint: { cmd: 'Router> enable', desc: 'สลับไปทำ R3 — enable แล้ว configure terminal' },
    hints: [
      { cmd: 'Router> enable', desc: 'สลับไปทำ R3 — เข้าสู่ Privileged EXEC' },
      { cmd: 'Router# configure terminal', desc: 'เข้าสู่ Global Configuration mode' },
    ],
    answer: 'enable\nconfigure terminal',
    commands: [
      { mode: 'exec', pat: ENABLE_PAT, next: 'exec-priv', pr: 'Router#', adv: false, msg: '' },
      { mode: 'exec-priv', pat: CONFT_PAT, next: 'config', pr: 'Router(config)#', adv: true, msg: 'Enter configuration commands, one per line.\nRouter(config)#' },
    ],
  },
  {
    id: 23,
    router: 'R3',
    name: 'R3 — ตั้งชื่อ hostname',
    short: 'hostname R3',
    mode: 'config',
    prompt: 'Router(config)#',
    cmdHint: { cmd: 'Router(config)# hostname R3', desc: 'ตั้งชื่ออุปกรณ์เป็น R3' },
    hints: [{ cmd: 'Router(config)# hostname R3', desc: 'ตั้งชื่ออุปกรณ์เป็น R3' }],
    answer: 'hostname R3',
    commands: [{ mode: 'config', pat: hostnamePat('R3'), next: 'config', pr: 'R3(config)#', adv: true, msg: '✓ Hostname เปลี่ยนเป็น R3 แล้วครับ' }],
  },
  {
    id: 8,
    router: 'R3',
    name: 'R3 — g0/0 (←R2) 172.20.2.6/30',
    short: 'g0/0 ←R2',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# interface g0/0', desc: 'ฝั่ง R2: 172.20.2.6/30' },
    hints: [
      { cmd: 'R3(config)# interface g0/0', desc: 'ฝั่ง R2: 172.20.2.6/30' },
      { cmd: 'R3(config-if)# ip address 172.20.2.6 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R3(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R3(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/0\nip address 172.20.2.6 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('0'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('172.20.2.6', '255.255.255.252'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to up' },
      { mode: 'config-if', pat: EXIT_PAT, next: 'config', pr: 'R3(config)#', adv: true, msg: '✓ g0/0 → 172.20.2.6/30 UP' },
    ],
  },
  {
    id: 9,
    router: 'R3',
    name: 'R3 — g0/1 LAN 172.20.3.1/24',
    short: 'g0/1 LAN',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# interface g0/1', desc: 'LAN ฝั่ง PC-C: 172.20.3.1/24 — เส้น R3—PC-C จะเขียว' },
    hints: [
      { cmd: 'R3(config)# interface g0/1', desc: 'LAN ฝั่ง PC-C: 172.20.3.1/24 — เส้น R3—PC-C จะเขียว' },
      { cmd: 'R3(config-if)# ip address 172.20.3.1 255.255.255.0', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R3(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R3(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/1\nip address 172.20.3.1 255.255.255.0\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('1'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('172.20.3.1', '255.255.255.0'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to up' },
      {
        mode: 'config-if',
        pat: EXIT_PAT,
        next: 'config',
        pr: 'R3(config)#',
        adv: true,
        msg: '✓ g0/1 → 172.20.3.1/24 UP\n  ต่อไปตั้งค่า PC-C ให้ครบตามหลักการก่อนครับ',
      },
    ],
  },
  {
    id: 201,
    router: 'PC-C',
    type: 'pcconfig',
    name: 'PC-C — ตั้งค่า IP / Subnet / Gateway',
    short: 'PC-C config',
    mode: 'pcconfig',
    prompt: '(คลิก PC-C)',
    expected: { ip: '172.20.3.10', mask: '255.255.255.0', gateway: '172.20.3.1' },
    cmdHint: { cmd: '(คลิกที่ไอคอน PC-C บนแผนภาพด้านบน)', desc: 'กำหนด IP/Subnet/Gateway ให้ PC-C ผ่านหน้าต่างตั้งค่า' },
  },

  // ── เฟส 2: ที่เหลือของ R3 (เปิด RIPv2, ตรวจสอบ, save) ──
  {
    id: 10,
    router: 'R3',
    name: 'R3 — เปิดใช้งาน RIPv2',
    short: 'RIP setup',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# router rip', desc: 'เข้าสู่โหมดตั้งค่า RIP' },
    hints: [
      { cmd: 'R3(config)# router rip', desc: 'เข้าสู่โหมดตั้งค่า Routing Protocol RIP' },
      { cmd: 'R3(config-router)# version 2', desc: 'บังคับใช้ RIPv2 (classless, ส่ง subnet mask ไปด้วยทุกครั้ง) — จำเป็นเพราะ Lab นี้ใช้ VLSM' },
      { cmd: 'R3(config-router)# network 172.20.0.0', desc: 'ประกาศ major network 172.20.0.0 — คำสั่ง network ยังใช้ major network เสมอไม่ว่าจะ version ไหน' },
      { cmd: 'R3(config-router)# no auto-summary', desc: 'ปิดการสรุป subnet อัตโนมัติที่ classful boundary — ต้องปิดไม่งั้น subnet /30 ที่ VLSM ไว้จะพัง' },
    ],
    answer: 'router rip\nversion 2\nnetwork 172.20.0.0\nno auto-summary',
    commands: [
      { mode: 'config', pat: ROUTERRIP_PAT, next: 'config-router', pr: 'R3(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: VERSION2_PAT, next: 'config-router', pr: 'R3(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: networkPat('172.20.0.0'), next: 'config-router', pr: 'R3(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: NOAUTOSUM_PAT, next: 'config', pr: 'R3(config)#', adv: true, msg: '✓ เปิด RIPv2 บน R3 แล้วครับ — ประกาศ network 172.20.0.0 พร้อมปิด auto-summary' },
    ],
  },
  {
    id: 11,
    router: 'R3',
    name: 'R3 — ตรวจสอบด้วย show ip protocols (Checkpoint)',
    short: 'show protocols',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# do show ip protocols', desc: 'ตรวจสอบว่า RIP process กำลังทำงานเป็น version 2 และปิด auto-summary แล้วก่อน save' },
    answer: 'do show ip protocols',
    commands: [
      {
        mode: 'config',
        pat: SHOW_IP_PROTOCOLS_PAT,
        next: 'config',
        pr: 'R3(config)#',
        adv: true,
        msg: 'Routing Protocol is "rip"\n  Sending updates every 30 seconds\n  Default version control: send version 2, receive version 2\n  Automatic network summarization is not in effect\n  Routing for Networks:\n    172.20.0.0\n  Distance: (default is 120)\n\n✓ RIP version 2 กำลังทำงานอยู่ครับ (ปิด auto-summary แล้ว) — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },
  {
    id: 12,
    router: 'R3',
    name: 'R3 — end & write memory',
    short: 'save R3',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# end  →  write memory', desc: 'บันทึก config R3 ที่ตั้งค่าไว้ให้ถาวร' },
    hints: [
      { cmd: 'R3(config)# end', desc: 'ออกจาก config mode (end หรือ exit ก็ได้)' },
      { cmd: 'R3# write memory', desc: 'บันทึก config R3 ที่ตั้งค่าไว้ให้ถาวร' },
    ],
    answer: 'end\nwrite memory',
    commands: [
      { mode: 'config', pat: END_OR_EXIT_PAT, next: 'exec-priv', pr: 'R3#', adv: false, msg: 'R3#' },
      { mode: 'exec-priv', pat: writeMemPat(), next: 'exec-priv', pr: 'R3#', adv: true, msg: 'Building configuration...\n[OK]\n✓ R3 config บันทึกแล้วครับ — สลับไปทำ R2 ต่อครับ' },
    ],
  },

  // ── เฟส 2 (ต่อ): ที่เหลือของ R2 (เปิด RIPv2, ตรวจสอบ, save) ──
  {
    id: 13,
    router: 'R2',
    name: 'R2 — เปิดใช้งาน RIPv2',
    short: 'RIP setup',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# router rip', desc: 'เข้าสู่โหมดตั้งค่า RIP' },
    hints: [
      { cmd: 'R2(config)# router rip', desc: 'เข้าสู่โหมดตั้งค่า Routing Protocol RIP' },
      { cmd: 'R2(config-router)# version 2', desc: 'บังคับใช้ RIPv2' },
      { cmd: 'R2(config-router)# network 172.20.0.0', desc: 'ประกาศ major network 172.20.0.0 — ครอบคลุมทั้ง 2 interface ของ R2' },
      { cmd: 'R2(config-router)# no auto-summary', desc: 'ปิดการสรุป subnet อัตโนมัติที่ classful boundary' },
    ],
    answer: 'router rip\nversion 2\nnetwork 172.20.0.0\nno auto-summary',
    commands: [
      { mode: 'config', pat: ROUTERRIP_PAT, next: 'config-router', pr: 'R2(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: VERSION2_PAT, next: 'config-router', pr: 'R2(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: networkPat('172.20.0.0'), next: 'config-router', pr: 'R2(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: NOAUTOSUM_PAT, next: 'config', pr: 'R2(config)#', adv: true, msg: '✓ เปิด RIPv2 บน R2 แล้วครับ — ประกาศ network 172.20.0.0 พร้อมปิด auto-summary' },
    ],
  },
  {
    id: 14,
    router: 'R2',
    name: 'R2 — ตรวจสอบด้วย show ip protocols (Checkpoint)',
    short: 'show protocols',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# do show ip protocols', desc: 'ตรวจสอบว่า RIP process กำลังทำงานเป็น version 2 ก่อน save' },
    answer: 'do show ip protocols',
    commands: [
      {
        mode: 'config',
        pat: SHOW_IP_PROTOCOLS_PAT,
        next: 'config',
        pr: 'R2(config)#',
        adv: true,
        msg: 'Routing Protocol is "rip"\n  Sending updates every 30 seconds\n  Default version control: send version 2, receive version 2\n  Automatic network summarization is not in effect\n  Routing for Networks:\n    172.20.0.0\n  Distance: (default is 120)\n\n✓ RIP version 2 กำลังทำงานอยู่ครับ (ปิด auto-summary แล้ว) — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },
  {
    id: 15,
    router: 'R2',
    name: 'R2 — end & write memory',
    short: 'save R2',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# end  →  write memory', desc: 'บันทึก config R2' },
    hints: [
      { cmd: 'R2(config)# end', desc: 'ออกจาก config mode (end หรือ exit ก็ได้)' },
      { cmd: 'R2# write memory', desc: 'บันทึก config R2 ที่ตั้งค่าไว้ให้ถาวร' },
    ],
    answer: 'end\nwrite memory',
    commands: [
      { mode: 'config', pat: END_OR_EXIT_PAT, next: 'exec-priv', pr: 'R2#', adv: false, msg: 'R2#' },
      { mode: 'exec-priv', pat: writeMemPat(), next: 'exec-priv', pr: 'R2#', adv: true, msg: 'Building configuration...\n[OK]\n✓ R2 config บันทึกแล้วครับ — สลับไปทำ R1 ต่อครับ' },
    ],
  },

  // ── เฟส 3: ที่เหลือของ R1 (เปิด RIPv2, ตรวจสอบ, save) แล้วตรวจสอบผลลัพธ์รวม ──
  {
    id: 16,
    router: 'R1',
    name: 'R1 — เปิดใช้งาน RIPv2',
    short: 'RIP setup',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# router rip', desc: 'เข้าสู่โหมดตั้งค่า RIP' },
    hints: [
      { cmd: 'R1(config)# router rip', desc: 'เข้าสู่โหมดตั้งค่า Routing Protocol RIP' },
      { cmd: 'R1(config-router)# version 2', desc: 'บังคับใช้ RIPv2' },
      { cmd: 'R1(config-router)# network 172.20.0.0', desc: 'ประกาศ major network 172.20.0.0 — ครอบคลุมทั้ง 2 interface ของ R1' },
      { cmd: 'R1(config-router)# no auto-summary', desc: 'ปิดการสรุป subnet อัตโนมัติที่ classful boundary' },
    ],
    answer: 'router rip\nversion 2\nnetwork 172.20.0.0\nno auto-summary',
    commands: [
      { mode: 'config', pat: ROUTERRIP_PAT, next: 'config-router', pr: 'R1(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: VERSION2_PAT, next: 'config-router', pr: 'R1(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: networkPat('172.20.0.0'), next: 'config-router', pr: 'R1(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: NOAUTOSUM_PAT, next: 'config', pr: 'R1(config)#', adv: true, msg: '✓ เปิด RIPv2 บน R1 แล้วครับ — ประกาศ network 172.20.0.0 พร้อมปิด auto-summary' },
    ],
  },
  {
    id: 17,
    router: 'R1',
    name: 'R1 — ตรวจสอบด้วย show ip protocols (Checkpoint)',
    short: 'show protocols',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# do show ip protocols', desc: 'ตรวจสอบว่า RIP process กำลังทำงานเป็น version 2 ก่อน save — ใช้ do นำหน้าเพื่อรันคำสั่ง show จาก config mode ได้เลยโดยไม่ต้อง exit' },
    answer: 'do show ip protocols',
    commands: [
      {
        mode: 'config',
        pat: SHOW_IP_PROTOCOLS_PAT,
        next: 'config',
        pr: 'R1(config)#',
        adv: true,
        msg: 'Routing Protocol is "rip"\n  Sending updates every 30 seconds\n  Default version control: send version 2, receive version 2\n  Automatic network summarization is not in effect\n  Routing for Networks:\n    172.20.0.0\n  Distance: (default is 120)\n\n✓ RIP version 2 กำลังทำงานอยู่ครับ (ปิด auto-summary แล้ว) — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },
  {
    id: 18,
    router: 'R1',
    name: 'R1 — end & write memory',
    short: 'save R1',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# end  →  write memory', desc: 'บันทึก config R1 ไปยัง NVRAM' },
    hints: [
      { cmd: 'R1(config)# end', desc: 'ออกจาก config mode กลับสู่ Privileged EXEC (end หรือ exit ก็ได้)' },
      { cmd: 'R1# write memory', desc: 'บันทึก config ที่ตั้งค่าไว้ให้ถาวรไปยังหน่วยความจำของ Router' },
    ],
    answer: 'end\nwrite memory',
    commands: [
      { mode: 'config', pat: END_OR_EXIT_PAT, next: 'exec-priv', pr: 'R1#', adv: false, msg: 'R1#' },
      { mode: 'exec-priv', pat: writeMemPat(), next: 'exec-priv', pr: 'R1#', adv: true, msg: 'Building configuration...\n[OK]\n✓ R1 config บันทึกแล้วครับ' },
    ],
  },
  {
    id: 19,
    router: 'R1',
    name: 'R1 — ตรวจสอบ Routing Table รวม (show ip route)',
    short: 'show route',
    mode: 'exec-priv',
    prompt: 'R1#',
    cmdHint: { cmd: 'R1# show ip route', desc: 'ดู network ที่ R1 เรียนรู้มาจาก RIPv2 โดยอัตโนมัติ — สังเกตว่าเห็น subnet /30 ที่แท้จริง ไม่ถูกสรุปรวมเหมือน RIPv1' },
    answer: 'show ip route',
    commands: [
      {
        mode: 'exec-priv',
        pat: /^sh(ow)?\s+ip\s+route$/i,
        next: 'exec-priv',
        pr: 'R1#',
        adv: true,
        msg: 'Codes: L - local, C - connected, R - RIP\n\nC    172.20.1.0/24 is directly connected, GigabitEthernet0/0\nC    172.20.2.0/30 is directly connected, GigabitEthernet0/1\nR    172.20.2.4/30 [120/1] via 172.20.2.2, 00:00:12, GigabitEthernet0/1\nR    172.20.3.0/24 [120/2] via 172.20.2.2, 00:00:12, GigabitEthernet0/1\n\n✓ เห็น subnet /30 (172.20.2.4/30) ที่แท้จริงจาก RIPv2 (R) แล้วครับ — ไม่ถูกสรุปรวมเป็น major network เหมือน RIPv1 เพราะปิด auto-summary',
      },
    ],
  },
  {
    id: 20,
    router: 'PC-A',
    type: 'pcping',
    name: 'PC-A — ทดสอบ ping ไปยัง PC-C ผ่าน Command Prompt',
    short: 'ping PC-C (PC)',
    mode: 'pcping',
    prompt: '(คลิก PC-A)',
    target: { ip: '172.20.3.10', label: 'PC-C' },
    cmdHint: {
      cmd: '(คลิกที่ไอคอน PC-A บนแผนภาพด้านบน แล้วพิมพ์ ping 172.20.3.10 ในหน้า Command Prompt)',
      desc: 'ทดสอบว่า PC-A คุยกับ PC-C ได้จริงจากมุมมองผู้ใช้งานทั่วไป (ไม่ผ่าน Router) — ยืนยันว่า RIPv2 พาไปถึงปลายทางได้จริงแม้จะใช้ VLSM',
    },
  },
];

export const PRETEST: PretestQuestion[] = [
  {
    id: 'q1',
    type: 'mcq',
    q: 'RIPv2 แตกต่างจาก RIPv1 หลักๆ อย่างไร?',
    opts: ['Metric ต่างกันโดยสิ้นเชิง', 'เป็น Classless routing protocol ส่ง Subnet Mask ไปพร้อม update ทำให้รองรับ VLSM', 'เปลี่ยนจาก Distance Vector เป็น Link-State', 'จำนวน Hop สูงสุดเพิ่มขึ้นเป็น 30'],
    ans: 1,
    exp: 'RIPv2 เป็น Classless routing protocol ที่ส่ง subnet mask ไปพร้อมกับ update ทุกครั้ง ทำให้รองรับ VLSM (Variable Length Subnet Mask) ได้ ต่างจาก RIPv1 ที่เป็น Classful ส่งแค่ major network โดยไม่มี mask',
  },
  {
    id: 'q2',
    type: 'mcq',
    q: 'คำสั่ง no auto-summary มีไว้ทำอะไร?',
    opts: ['ปิดการส่ง routing update ทั้งหมด', 'ลบ routing table ทั้งหมดทิ้ง', 'ปิดการสรุป (summarize) subnet ให้เหลือแค่ major network โดยอัตโนมัติที่ classful boundary', 'ปิดใช้งาน RIP process ทั้งหมด'],
    ans: 2,
    exp: 'ปกติ RIP จะสรุปหลาย subnet ย่อยให้เหลือแค่ major network โดยอัตโนมัติเมื่อส่งข้าม classful boundary ซึ่งจะทำให้ subnet ที่ทำ VLSM ไว้ (เช่น /30 ของ Lab นี้) พังได้ คำสั่ง no auto-summary จึงปิดพฤติกรรมนี้ ทำให้ RIPv2 ส่ง subnet ที่แท้จริงไปเสมอ',
  },
  {
    id: 'q3',
    type: 'mcq',
    q: 'RIPv2 ส่ง update ผ่านช่องทางใด ต่างจาก RIPv1?',
    opts: ['Broadcast 255.255.255.255 เหมือนเดิม', 'Broadcast ผ่าน VLAN 1 เท่านั้น', 'Unicast ส่งทีละ Router', 'Multicast ไปที่ 224.0.0.9'],
    ans: 3,
    exp: 'RIPv1 ส่ง update แบบ Broadcast (255.255.255.255) ทำให้ทุกอุปกรณ์ในเครือข่ายต้องประมวลผล ส่วน RIPv2 ส่งแบบ Multicast ไปที่ 224.0.0.9 ทำให้เฉพาะอุปกรณ์ที่รัน RIP เท่านั้นที่รับ/ประมวลผล',
  },
  {
    id: 'q4',
    type: 'dragdrop',
    q: 'จับคู่คำสั่งกับหน้าที่ของมัน',
    pairs: [
      { left: 'version 2', right: 'บังคับใช้ RIP เวอร์ชัน 2 (classless รองรับ VLSM)' },
      { left: 'no auto-summary', right: 'ปิดการสรุป subnet อัตโนมัติที่ classful boundary' },
      { left: 'network 172.20.0.0', right: 'ประกาศ major network ให้ RIP ทำงาน (ไวยากรณ์เหมือนเดิมทุก version)' },
      { left: '224.0.0.9', right: 'Multicast address ที่ RIPv2 ใช้ส่ง update' },
    ],
  },
];

export const INTRO_LINES = [
  { text: '# Ch.7 RIP v2 — NETLab', cls: 't-info' },
  { text: '# อ้างอิง: Cisco Networking Academy W7', cls: 't-hint' },
  { text: '# Topology: PC-A—R1—R2—R3—PC-C (ใช้ VLSM: LAN /24, WAN /30)', cls: 't-dim' },
  { text: '# R1: g0/0=172.20.1.1/24  g0/1=172.20.2.1/30', cls: 't-dim' },
  { text: '# R2: g0/0=172.20.2.2/30  g0/1=172.20.2.5/30', cls: 't-dim' },
  { text: '# R3: g0/0=172.20.2.6/30  g0/1=172.20.3.1/24', cls: 't-dim' },
  { text: '' },
  { text: '# เริ่มที่ R1 — พิมพ์: enable', cls: 't-hint' },
];

export const WELCOME_MSG =
  'สวัสดีครับ! Ch.7 RIP v2\n\nTopology: PC-A—R1—R2—R3—PC-C (ใช้ VLSM จริง: LAN /24, WAN /30)\nขั้นตอนแรก: ตั้งชื่อ hostname และ IP ให้ครบทุกอุปกรณ์ก่อน (รวม PC-A, PC-C ด้วย — คลิกที่ไอคอน PC บนแผนภาพเพื่อกรอก IP) แล้วค่อยเปิด RIPv2 (version 2 + no auto-summary) ให้ Router เรียนรู้เส้นทางกันเองอัตโนมัติแบบ classless รวม 25 steps (มีจุด Checkpoint ตรวจสอบด้วย show ก่อน save ทุก Router)\nแต่ละเส้นจะเขียวเมื่อทั้งสองฝั่งตั้งค่าเสร็จครับ\n\nทำ Pre-test ก่อนหรือข้ามไป Lab เลยก็ได้ครับ';

export const COMPLETE_CHAT_SUMMARY =
  'ยินดีด้วยครับ! Lab Ch.7 เสร็จสมบูรณ์!\n\nสรุป:\n• R1, R2, R3: ตั้ง IP แบบ VLSM ครบทุก interface (LAN /24, WAN /30) แล้วเปิด RIPv2 (router rip + version 2 + network 172.20.0.0 + no auto-summary)\n• Router ทั้ง 3 ตัวเรียนรู้เส้นทางกันเองอัตโนมัติแบบ classless เห็น subnet /30 ที่แท้จริง ไม่ถูกสรุปรวม\n• Ping PC-A→PC-C สำเร็จผ่าน route ที่ RIPv2 เรียนรู้เอง';
