/* NETLab — Lab 5 (Static & Default Routing) data, ported 1:1 from
   public/labnetwork1/lab05-static-route/lab5.html's inline <STEPS>/<NODES>/
   <LINKS>/<PRETEST> globals. This is the Config Lab *template* — every other
   Config Lab (4, 6-11) follows the same data-file + <ConfigLab/> shape. */
import {
  CONFT_PAT,
  ENABLE_PAT,
  END_OR_EXIT_PAT,
  EXIT_PAT,
  NOSHUT_PAT,
  hostnamePat,
  ifpat,
  ipAddrPat,
  ipRoutePat,
  writeMemPat,
} from '../../lib/ciscoPatterns';
import type { PretestQuestion, Step, TopoLink, TopoNode } from '../../types/configLab';

export const NODES: TopoNode[] = [
  { id: 'PC-A', x: 60, role: 'host' },
  { id: 'R1', x: 260, role: 'router' },
  { id: 'R2', x: 460, role: 'router' },
  { id: 'R3', x: 660, role: 'router' },
  { id: 'PC-C', x: 860, role: 'host' },
];

export const LINKS: TopoLink[] = [
  { from: 'PC-A', to: 'R1', subnet: '192.168.1.0/24', if1: '', if2: 'g0/0', activateOnSteps: [3, 200] },
  { from: 'R1', to: 'R2', subnet: '10.0.0.0/30', if1: 'g0/1', if2: 'g0/0', activateOnSteps: [4, 10] },
  { from: 'R2', to: 'R3', subnet: '10.0.1.0/30', if1: 'g0/1', if2: 'g0/0', activateOnSteps: [11, 17] },
  { from: 'R3', to: 'PC-C', subnet: '192.168.3.0/24', if1: 'g0/1', if2: '', activateOnSteps: [18, 201] },
];

export const NODE_IP_LABELS: Record<string, string> = {
  'PC-A': '192.168.1.10',
  R1: '192.168.1.1',
  R2: '10.0.0.2',
  R3: '10.0.1.2',
  'PC-C': '192.168.3.10',
};

export const STEPS: Step[] = [
  // ── เฟส 1: ตั้งชื่อ Hostname และ IP ให้ทุกอุปกรณ์ก่อน (รวม PC) แล้วค่อยลง Static Route ทีหลัง ──
  {
    id: 1,
    router: 'R1',
    name: 'R1 — enable & configure terminal',
    short: 'R1 enable',
    mode: 'exec',
    prompt: 'Router>',
    cmdHint: { cmd: 'Router> enable', desc: 'เข้า Privileged EXEC ก่อน แล้วพิมพ์ configure terminal' },
    hints: [
      { cmd: 'Router> enable', desc: 'เข้าสู่ Privileged EXEC mode ก่อน' },
      { cmd: 'Router# configure terminal', desc: 'เข้าสู่ Global Configuration mode' },
    ],
    answer: 'enable\nconfigure terminal',
    commands: [
      { mode: 'exec', pat: ENABLE_PAT, next: 'exec-priv', pr: 'Router#', adv: false, msg: '' },
      { mode: 'exec-priv', pat: CONFT_PAT, next: 'config', pr: 'Router(config)#', adv: true, msg: 'Enter configuration commands, one per line.\nRouter(config)#' },
    ],
  },
  {
    id: 2,
    router: 'R1',
    name: 'R1 — ตั้งชื่อ Hostname เป็น R1',
    short: 'hostname R1',
    mode: 'config',
    prompt: 'Router(config)#',
    cmdHint: { cmd: 'Router(config)# hostname R1', desc: 'ตั้งชื่ออุปกรณ์ก่อนเป็นอันดับแรก เพื่อให้แยกแยะได้ง่ายในเครือข่าย' },
    answer: 'hostname R1',
    commands: [{ mode: 'config', pat: hostnamePat('R1'), next: 'config', pr: 'R1(config)#', adv: true, msg: '✓ Hostname เปลี่ยนเป็น R1 แล้วครับ (สังเกต prompt ที่เปลี่ยนไป)' }],
  },
  {
    id: 3,
    router: 'R1',
    name: 'R1 — g0/0 LAN 192.168.1.1/24',
    short: 'g0/0 LAN',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# interface g0/0', desc: 'LAN ฝั่ง PC-A: 192.168.1.1/24 — เส้น PC-A—R1 จะเขียว' },
    hints: [
      { cmd: 'R1(config)# interface g0/0', desc: 'LAN ฝั่ง PC-A: 192.168.1.1/24 — เส้น PC-A—R1 จะเขียว' },
      { cmd: 'R1(config-if)# ip address 192.168.1.1 255.255.255.0', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R1(config-if)# no shutdown', desc: 'เปิดใช้งาน interface (ไม่งั้นจะ down ตลอด)' },
      { cmd: 'R1(config-if)# exit', desc: 'ออกจาก interface mode กลับสู่ config mode' },
    ],
    answer: 'interface g0/0\nip address 192.168.1.1 255.255.255.0\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('0'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('192.168.1.1', '255.255.255.0'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to up' },
      { mode: 'config-if', pat: EXIT_PAT, next: 'config', pr: 'R1(config)#', adv: true, msg: '✓ g0/0 → 192.168.1.1/24 UP\n  เส้น PC-A—R1 เขียวครึ่งเดียว รอ PC-A ตั้ง IP ด้วยครับ' },
    ],
  },
  {
    id: 4,
    router: 'R1',
    name: 'R1 — g0/1 WAN 10.0.0.1/30',
    short: 'g0/1 WAN',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# interface g0/1', desc: 'WAN ฝั่ง R2: 10.0.0.1/30 — เส้น R1—R2 จะเขียว' },
    hints: [
      { cmd: 'R1(config)# interface g0/1', desc: 'WAN ฝั่ง R2: 10.0.0.1/30 — เส้น R1—R2 จะเขียว' },
      { cmd: 'R1(config-if)# ip address 10.0.0.1 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R1(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R1(config-if)# exit', desc: 'ออกจาก interface mode กลับสู่ config mode' },
    ],
    answer: 'interface g0/1\nip address 10.0.0.1 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('1'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('10.0.0.1', '255.255.255.252'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to up' },
      {
        mode: 'config-if',
        pat: EXIT_PAT,
        next: 'config',
        pr: 'R1(config)#',
        adv: true,
        msg: '✓ g0/1 → 10.0.0.1/30 UP\n  เส้น R1—R2 เขียวแล้วครับ — ต่อไปตั้งค่า PC-A ก่อน แล้วค่อยไปตั้ง IP ของ R2',
      },
    ],
  },
  {
    id: 200,
    router: 'PC-A',
    type: 'pcconfig',
    name: 'PC-A — กำหนดค่า IP Configuration',
    short: 'PC-A IP',
    mode: 'pcconfig',
    prompt: '(คลิก PC-A)',
    cmdHint: { cmd: '(คลิกที่ไอคอน PC-A บนแผนภาพด้านบน)', desc: 'กำหนด IP Address, Subnet Mask, Default Gateway ให้ PC-A ให้ตรงกับ Topology (Gateway = IP ของ R1 g0/0)' },
    expected: { ip: '192.168.1.10', mask: '255.255.255.0', gateway: '192.168.1.1' },
  },
  {
    id: 8,
    router: 'R2',
    name: 'R2 — enable & configure terminal',
    short: 'R2 enable',
    mode: 'exec',
    prompt: 'Router>',
    cmdHint: { cmd: 'Router> enable', desc: 'สลับไปทำ R2 — enable แล้ว configure terminal' },
    hints: [
      { cmd: 'Router> enable', desc: 'สลับไปทำ R2 — เข้าสู่ Privileged EXEC' },
      { cmd: 'Router# configure terminal', desc: 'เข้าสู่ Global Configuration mode' },
    ],
    answer: 'enable\nconfigure terminal',
    commands: [
      { mode: 'exec', pat: ENABLE_PAT, next: 'exec-priv', pr: 'Router#', adv: false, msg: '' },
      { mode: 'exec-priv', pat: CONFT_PAT, next: 'config', pr: 'Router(config)#', adv: true, msg: 'Enter configuration commands, one per line.\nRouter(config)#' },
    ],
  },
  {
    id: 9,
    router: 'R2',
    name: 'R2 — ตั้งชื่อ Hostname เป็น R2',
    short: 'hostname R2',
    mode: 'config',
    prompt: 'Router(config)#',
    cmdHint: { cmd: 'Router(config)# hostname R2', desc: 'ตั้งชื่ออุปกรณ์ก่อนเป็นอันดับแรก เพื่อให้แยกแยะได้ง่ายในเครือข่าย' },
    answer: 'hostname R2',
    commands: [{ mode: 'config', pat: hostnamePat('R2'), next: 'config', pr: 'R2(config)#', adv: true, msg: '✓ Hostname เปลี่ยนเป็น R2 แล้วครับ' }],
  },
  {
    id: 10,
    router: 'R2',
    name: 'R2 — g0/0 (←R1) 10.0.0.2/30',
    short: 'g0/0 ←R1',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# interface g0/0', desc: 'ฝั่ง R1: 10.0.0.2/30' },
    hints: [
      { cmd: 'R2(config)# interface g0/0', desc: 'ฝั่ง R1: 10.0.0.2/30' },
      { cmd: 'R2(config-if)# ip address 10.0.0.2 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R2(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R2(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/0\nip address 10.0.0.2 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('0'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('10.0.0.2', '255.255.255.252'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to up' },
      { mode: 'config-if', pat: EXIT_PAT, next: 'config', pr: 'R2(config)#', adv: true, msg: '✓ g0/0 → 10.0.0.2/30 UP' },
    ],
  },
  {
    id: 11,
    router: 'R2',
    name: 'R2 — g0/1 (→R3) 10.0.1.1/30',
    short: 'g0/1 →R3',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# interface g0/1', desc: 'ฝั่ง R3: 10.0.1.1/30 — เส้น R2—R3 จะเขียว' },
    hints: [
      { cmd: 'R2(config)# interface g0/1', desc: 'ฝั่ง R3: 10.0.1.1/30 — เส้น R2—R3 จะเขียว' },
      { cmd: 'R2(config-if)# ip address 10.0.1.1 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R2(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R2(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/1\nip address 10.0.1.1 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('1'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('10.0.1.1', '255.255.255.252'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to up' },
      {
        mode: 'config-if',
        pat: EXIT_PAT,
        next: 'config',
        pr: 'R2(config)#',
        adv: true,
        msg: '✓ g0/1 → 10.0.1.1/30 UP\n  เส้น R2—R3 เขียวแล้วครับ — สลับไปตั้ง IP ของ R3 ต่อได้เลยครับ',
      },
    ],
  },
  {
    id: 15,
    router: 'R3',
    name: 'R3 — enable & configure terminal',
    short: 'R3 enable',
    mode: 'exec',
    prompt: 'Router>',
    cmdHint: { cmd: 'Router> enable', desc: 'สลับไปทำ R3 — enable แล้ว configure terminal' },
    hints: [
      { cmd: 'Router> enable', desc: 'สลับไปทำ R3 — เข้าสู่ Privileged EXEC' },
      { cmd: 'Router# configure terminal', desc: 'เข้าสู่ Global Configuration mode' },
    ],
    answer: 'enable\nconfigure terminal',
    commands: [
      { mode: 'exec', pat: ENABLE_PAT, next: 'exec-priv', pr: 'Router#', adv: false, msg: '' },
      { mode: 'exec-priv', pat: CONFT_PAT, next: 'config', pr: 'Router(config)#', adv: true, msg: 'Enter configuration commands, one per line.\nRouter(config)#' },
    ],
  },
  {
    id: 16,
    router: 'R3',
    name: 'R3 — ตั้งชื่อ Hostname เป็น R3',
    short: 'hostname R3',
    mode: 'config',
    prompt: 'Router(config)#',
    cmdHint: { cmd: 'Router(config)# hostname R3', desc: 'ตั้งชื่ออุปกรณ์ก่อนเป็นอันดับแรก เพื่อให้แยกแยะได้ง่ายในเครือข่าย' },
    answer: 'hostname R3',
    commands: [{ mode: 'config', pat: hostnamePat('R3'), next: 'config', pr: 'R3(config)#', adv: true, msg: '✓ Hostname เปลี่ยนเป็น R3 แล้วครับ' }],
  },
  {
    id: 17,
    router: 'R3',
    name: 'R3 — g0/0 (←R2) 10.0.1.2/30',
    short: 'g0/0 ←R2',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# interface g0/0', desc: 'ฝั่ง R2: 10.0.1.2/30' },
    hints: [
      { cmd: 'R3(config)# interface g0/0', desc: 'ฝั่ง R2: 10.0.1.2/30' },
      { cmd: 'R3(config-if)# ip address 10.0.1.2 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R3(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R3(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/0\nip address 10.0.1.2 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('0'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('10.0.1.2', '255.255.255.252'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to up' },
      { mode: 'config-if', pat: EXIT_PAT, next: 'config', pr: 'R3(config)#', adv: true, msg: '✓ g0/0 → 10.0.1.2/30 UP' },
    ],
  },
  {
    id: 18,
    router: 'R3',
    name: 'R3 — g0/1 LAN 192.168.3.1/24',
    short: 'g0/1 LAN',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# interface g0/1', desc: 'LAN ฝั่ง PC-C: 192.168.3.1/24 — เส้น R3—PC-C จะเขียว' },
    hints: [
      { cmd: 'R3(config)# interface g0/1', desc: 'LAN ฝั่ง PC-C: 192.168.3.1/24 — เส้น R3—PC-C จะเขียว' },
      { cmd: 'R3(config-if)# ip address 192.168.3.1 255.255.255.0', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R3(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R3(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/1\nip address 192.168.3.1 255.255.255.0\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('1'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('192.168.3.1', '255.255.255.0'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to up' },
      {
        mode: 'config-if',
        pat: EXIT_PAT,
        next: 'config',
        pr: 'R3(config)#',
        adv: true,
        msg: '✓ g0/1 → 192.168.3.1/24 UP\n  ต่อไปตั้งค่า PC-C ให้ครบตามหลักการก่อนครับ',
      },
    ],
  },
  {
    id: 201,
    router: 'PC-C',
    type: 'pcconfig',
    name: 'PC-C — กำหนดค่า IP Configuration',
    short: 'PC-C IP',
    mode: 'pcconfig',
    prompt: '(คลิก PC-C)',
    cmdHint: {
      cmd: '(คลิกที่ไอคอน PC-C บนแผนภาพด้านบน)',
      desc: 'กำหนด IP Address, Subnet Mask, Default Gateway ให้ PC-C ให้ตรงกับ Topology (Gateway = IP ของ R3 g0/1) — ตั้งชื่อ+IP ครบทุกอุปกรณ์แล้ว ต่อไปมาทำ Static Route กันครับ',
    },
    expected: { ip: '192.168.3.10', mask: '255.255.255.0', gateway: '192.168.3.1' },
  },

  // ── เฟส 2: ที่เหลือของ R3 (Static Route, ตรวจสอบ, save) ──
  {
    id: 19,
    router: 'R3',
    name: 'R3 — Static Route 192.168.1.0/24',
    short: 'Static R3',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# ip route 192.168.1.0 255.255.255.0 10.0.1.1', desc: 'Route ย้อนกลับ LAN PC-A ผ่าน R2 (next-hop 10.0.1.1)' },
    answer: 'ip route 192.168.1.0 255.255.255.0 10.0.1.1',
    commands: [
      { mode: 'config', pat: ipRoutePat('192.168.1.0', '255.255.255.0', '10.0.1.1'), next: 'config', pr: 'R3(config)#', adv: true, msg: '✓ Static Route: 192.168.1.0/24 via 10.0.1.1 (R2)' },
    ],
  },
  {
    id: 105,
    router: 'R3',
    name: 'R3 — ตรวจสอบด้วย show ip route (Checkpoint)',
    short: 'show route',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# do show ip route', desc: 'ตรวจสอบ Routing Table ก่อน save' },
    answer: 'do show ip route',
    commands: [
      {
        mode: 'config',
        pat: /^do\s+sh(ow)?\s+ip\s+route$/i,
        next: 'config',
        pr: 'R3(config)#',
        adv: true,
        msg: 'Codes: L - local, C - connected, S - static\n\nC    10.0.1.0/30 is directly connected, GigabitEthernet0/0\nC    192.168.3.0/24 is directly connected, GigabitEthernet0/1\nS    192.168.1.0/24 [1/0] via 10.0.1.1\n\n✓ เห็น static route ที่เพิ่งตั้งค่าแล้วครับ — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },
  {
    id: 106,
    router: 'R3',
    name: 'R3 — end & write memory',
    short: 'save R3',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# end  →  write memory', desc: 'บันทึก config R3 ที่ตั้งค่าไว้ให้ถาวร' },
    hints: [
      { cmd: 'R3(config)# end', desc: 'ออกจาก config mode (end หรือ exit ก็ได้)' },
      { cmd: 'R3# write memory', desc: 'บันทึก config R3 ที่ตั้งค่าไว้ให้ถาวร' },
    ],
    answer: 'end\nwrite memory',
    commands: [
      { mode: 'config', pat: END_OR_EXIT_PAT, next: 'exec-priv', pr: 'R3#', adv: false, msg: 'R3#' },
      { mode: 'exec-priv', pat: writeMemPat(), next: 'exec-priv', pr: 'R3#', adv: true, msg: 'Building configuration...\n[OK]\n✓ R3 config บันทึกแล้วครับ — สลับไปทำ R2 ต่อครับ' },
    ],
  },

  // ── เฟส 2 (ต่อ): ที่เหลือของ R2 (Static Route 2 เส้น, ตรวจสอบ, save) ──
  {
    id: 12,
    router: 'R2',
    name: 'R2 — Static Route 192.168.1.0/24',
    short: 'Static R2(1)',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# ip route 192.168.1.0 255.255.255.0 10.0.0.1', desc: 'Route ย้อนกลับไป LAN PC-A ผ่าน R1 (next-hop 10.0.0.1)' },
    answer: 'ip route 192.168.1.0 255.255.255.0 10.0.0.1',
    commands: [
      { mode: 'config', pat: ipRoutePat('192.168.1.0', '255.255.255.0', '10.0.0.1'), next: 'config', pr: 'R2(config)#', adv: true, msg: '✓ Static Route: 192.168.1.0/24 via 10.0.0.1 (R1)' },
    ],
  },
  {
    id: 13,
    router: 'R2',
    name: 'R2 — Static Route 192.168.3.0/24',
    short: 'Static R2(2)',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# ip route 192.168.3.0 255.255.255.0 10.0.1.2', desc: 'Route ไป LAN PC-C ผ่าน R3 (next-hop 10.0.1.2)' },
    answer: 'ip route 192.168.3.0 255.255.255.0 10.0.1.2',
    commands: [
      { mode: 'config', pat: ipRoutePat('192.168.3.0', '255.255.255.0', '10.0.1.2'), next: 'config', pr: 'R2(config)#', adv: true, msg: '✓ Static Route: 192.168.3.0/24 via 10.0.1.2 (R3)' },
    ],
  },
  {
    id: 101,
    router: 'R2',
    name: 'R2 — ตรวจสอบด้วย show ip route (Checkpoint)',
    short: 'show route',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# do show ip route', desc: 'ตรวจสอบ Routing Table ก่อน save' },
    answer: 'do show ip route',
    commands: [
      {
        mode: 'config',
        pat: /^do\s+sh(ow)?\s+ip\s+route$/i,
        next: 'config',
        pr: 'R2(config)#',
        adv: true,
        msg: 'Codes: L - local, C - connected, S - static\n\nC    10.0.0.0/30 is directly connected, GigabitEthernet0/0\nC    10.0.1.0/30 is directly connected, GigabitEthernet0/1\nS    192.168.1.0/24 [1/0] via 10.0.0.1\nS    192.168.3.0/24 [1/0] via 10.0.1.2\n\n✓ เห็น static route ทั้ง 2 เส้นที่เพิ่งตั้งค่าแล้วครับ — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },
  {
    id: 14,
    router: 'R2',
    name: 'R2 — end & write memory',
    short: 'save R2',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# end  →  write memory', desc: 'บันทึก config R2' },
    hints: [
      { cmd: 'R2(config)# end', desc: 'ออกจาก config mode (end หรือ exit ก็ได้)' },
      { cmd: 'R2# write memory', desc: 'บันทึก config R2 ที่ตั้งค่าไว้ให้ถาวร' },
    ],
    answer: 'end\nwrite memory',
    commands: [
      { mode: 'config', pat: END_OR_EXIT_PAT, next: 'exec-priv', pr: 'R2#', adv: false, msg: 'R2#' },
      { mode: 'exec-priv', pat: writeMemPat(), next: 'exec-priv', pr: 'R2#', adv: true, msg: 'Building configuration...\n[OK]\n✓ R2 config บันทึกแล้วครับ — สลับไปทำ R1 ต่อครับ' },
    ],
  },

  // ── เฟส 3: ที่เหลือของ R1 (Static + Default Route, ตรวจสอบ, save) แล้วตรวจสอบผลลัพธ์รวม ──
  {
    id: 5,
    router: 'R1',
    name: 'R1 — Static Route 192.168.3.0/24',
    short: 'Static R1',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# ip route 192.168.3.0 255.255.255.0 10.0.0.2', desc: 'Static Route ไป LAN PC-C ผ่าน R2 (next-hop 10.0.0.2)' },
    answer: 'ip route 192.168.3.0 255.255.255.0 10.0.0.2',
    commands: [
      { mode: 'config', pat: ipRoutePat('192.168.3.0', '255.255.255.0', '10.0.0.2'), next: 'config', pr: 'R1(config)#', adv: true, msg: '✓ Static Route: 192.168.3.0/24 via 10.0.0.2 (R2)' },
    ],
  },
  {
    id: 6,
    router: 'R1',
    name: 'R1 — Default Route 0.0.0.0/0',
    short: 'Default R1',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# ip route 0.0.0.0 0.0.0.0 10.0.0.2', desc: 'Default Route — Gateway of Last Resort ออก R2 (next-hop 10.0.0.2)' },
    answer: 'ip route 0.0.0.0 0.0.0.0 10.0.0.2',
    commands: [
      {
        mode: 'config',
        pat: ipRoutePat('0.0.0.0', '0.0.0.0', '10.0.0.2'),
        next: 'config',
        pr: 'R1(config)#',
        adv: true,
        msg: '✓ Default Route: 0.0.0.0/0 via 10.0.0.2\n  Traffic ทุกชนิดที่ไม่มีใน table จะส่งออก R2',
      },
    ],
  },
  {
    id: 100,
    router: 'R1',
    name: 'R1 — ตรวจสอบด้วย show ip route (Checkpoint)',
    short: 'show route',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# do show ip route', desc: 'ตรวจสอบ Routing Table ก่อน save — ใช้ do นำหน้าเพื่อรันคำสั่ง show จาก config mode ได้เลยโดยไม่ต้อง exit' },
    answer: 'do show ip route',
    commands: [
      {
        mode: 'config',
        pat: /^do\s+sh(ow)?\s+ip\s+route$/i,
        next: 'config',
        pr: 'R1(config)#',
        adv: true,
        msg: 'Codes: L - local, C - connected, S - static, * - candidate default\n\nGateway of last resort is 10.0.0.2 to network 0.0.0.0\n\nC    192.168.1.0/24 is directly connected, GigabitEthernet0/0\nC    10.0.0.0/30 is directly connected, GigabitEthernet0/1\nS    192.168.3.0/24 [1/0] via 10.0.0.2\nS*   0.0.0.0/0 [1/0] via 10.0.0.2\n\n✓ เห็น static route (S) และ default route (S*) ที่เพิ่งตั้งค่าแล้วครับ — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },
  {
    id: 7,
    router: 'R1',
    name: 'R1 — end & write memory',
    short: 'save R1',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# end  →  write memory', desc: 'บันทึก config R1 ไปยัง NVRAM' },
    hints: [
      { cmd: 'R1(config)# end', desc: 'ออกจาก config mode กลับสู่ Privileged EXEC (end หรือ exit ก็ได้)' },
      { cmd: 'R1# write memory', desc: 'บันทึก config ที่ตั้งค่าไว้ให้ถาวรไปยังหน่วยความจำของ Router' },
    ],
    answer: 'end\nwrite memory',
    commands: [
      { mode: 'config', pat: END_OR_EXIT_PAT, next: 'exec-priv', pr: 'R1#', adv: false, msg: 'R1#' },
      { mode: 'exec-priv', pat: writeMemPat(), next: 'exec-priv', pr: 'R1#', adv: true, msg: 'Building configuration...\n[OK]\n✓ R1 config บันทึกแล้วครับ' },
    ],
  },
  {
    id: 107,
    router: 'PC-A',
    type: 'pcping',
    name: 'PC-A — ทดสอบ ping ไปยัง PC-C ผ่าน Command Prompt',
    short: 'ping PC-C (PC)',
    mode: 'pcping',
    prompt: '(คลิก PC-A)',
    target: { ip: '192.168.3.10', label: 'PC-C' },
    cmdHint: {
      cmd: '(คลิกที่ไอคอน PC-A บนแผนภาพด้านบน แล้วพิมพ์ ping 192.168.3.10 ในหน้า Command Prompt)',
      desc: 'ทดสอบว่า PC-A คุยกับ PC-C ได้จริงจากมุมมองผู้ใช้งานทั่วไป (ไม่ผ่าน Router) — ยืนยันเส้นทางครบวงจรทั้ง 3 Router',
    },
  },
];

export const PRETEST: PretestQuestion[] = [
  {
    id: 'q1',
    type: 'mcq',
    q: 'ip route command รูปแบบที่ถูกต้องคืออะไร?',
    opts: ['ip route [next-hop] [network] [mask]', 'static route [network]/[prefix]', 'route ip [network] via [next-hop]', 'ip route [network] [mask] [next-hop]'],
    ans: 3,
    exp: 'ip route [destination-network] [subnet-mask] [next-hop-ip] เช่น ip route 192.168.3.0 255.255.255.0 10.0.0.2',
  },
  {
    id: 'q2',
    type: 'mcq',
    q: 'Default Route ใช้ network/mask อะไร?',
    opts: ['0.0.0.0 0.0.0.0', '0.0.0.0 255.255.255.0', '255.255.255.255 255.255.255.255', '192.168.0.0 0.0.0.0'],
    ans: 0,
    exp: 'Default Route ใช้ 0.0.0.0 0.0.0.0 เป็น catch-all จับ traffic ทุกชนิดที่ไม่มีใน routing table',
  },
  {
    id: 'q3',
    type: 'mcq',
    q: '/30 subnet mask (255.255.255.252) เหมาะกับอะไร?',
    opts: ['LAN ที่มี host 254 ตัว', 'WAN point-to-point link 2 Router', 'Management VLAN', 'Loopback interface'],
    ans: 1,
    exp: '255.255.255.252 (/30) ให้ IP ใช้งานได้ 2 address เหมาะกับ WAN link แบบ point-to-point ระหว่าง 2 Router ลดการสูญเสีย IP',
  },
  {
    id: 'q4',
    type: 'dragdrop',
    q: 'จับคู่ Router กับ next-hop ที่ใช้ใน Static Route',
    pairs: [
      { left: 'R1 route ไป 192.168.3.0', right: 'via 10.0.0.2 (R2 g0/0)' },
      { left: 'R2 route ไป 192.168.1.0', right: 'via 10.0.0.1 (R1 g0/1)' },
      { left: 'R2 route ไป 192.168.3.0', right: 'via 10.0.1.2 (R3 g0/0)' },
      { left: 'R3 route ไป 192.168.1.0', right: 'via 10.0.1.1 (R2 g0/1)' },
    ],
  },
];

export const INTRO_LINES = [
  { text: '# Ch.5 Static & Default Routing — NETLab', cls: 't-info' },
  { text: '# อ้างอิง: Cisco Networking Academy W5_1', cls: 't-hint' },
  { text: '# Topology: PC-A—R1—R2—R3—PC-C', cls: 't-dim' },
  { text: '# R1: g0/0=192.168.1.1/24  g0/1=10.0.0.1/30', cls: 't-dim' },
  { text: '# R2: g0/0=10.0.0.2/30     g0/1=10.0.1.1/30', cls: 't-dim' },
  { text: '# R3: g0/0=10.0.1.2/30     g0/1=192.168.3.1/24', cls: 't-dim' },
  { text: '' },
  { text: '# เริ่มที่ R1 — พิมพ์: enable', cls: 't-hint' },
];

export const WELCOME_MSG =
  'สวัสดีครับ! Ch.5 Static & Default Routing\n\nTopology: PC-A—R1—R2—R3—PC-C\nขั้นแรกตั้งชื่อ Hostname และ IP ให้ครบทุกอุปกรณ์ก่อน (รวม PC — คลิกที่ไอคอน PC บนแผนภาพเพื่อกำหนดค่า) แล้วค่อยทำ Static Route ทีหลัง รวม 26 steps (มีจุด Checkpoint ตรวจสอบด้วย show ก่อน save ทุก Router)\nแต่ละเส้นจะเขียวเมื่อทั้งสองฝั่งตั้งค่าเสร็จครบครับ\n\nทำ Pre-test ก่อนหรือข้ามไป Lab เลยก็ได้ครับ';

export const COMPLETE_CHAT_SUMMARY =
  'ยินดีด้วยครับ! Lab Ch.5 เสร็จสมบูรณ์!\n\nสรุป:\n• R1: g0/0 LAN, g0/1 WAN, Static+Default Route\n• R2: g0/0←R1, g0/1→R3, Static Route 2 เส้น\n• R3: g0/0←R2, g0/1 LAN, Static Route ย้อนกลับ\n• Ping PC-A→PC-C สำเร็จ';
