/* NETLab — Lab 8 (EIGRP) data, ported 1:1 from
   public/labnetwork1/lab08-eigrp/lab8.html's inline <STEPS>/<NODES>/<LINKS>/
   <PRETEST> globals. Same shared <ConfigLab/> engine as lab05-07; R3 is
   configured before R2/R1 so the Neighbor checkpoints on R2/R1 show a live
   EIGRP neighbor immediately (the far side is already up). */
import {
  CONFT_PAT,
  ENABLE_PAT,
  END_OR_EXIT_PAT,
  EXIT_PAT,
  NOAUTOSUM_PAT,
  NOSHUT_PAT,
  hostnamePat,
  ifpat,
  ipAddrPat,
  networkWildcardPat,
  routerEigrpPat,
  writeMemPat,
} from '../../lib/ciscoPatterns';
import type { PretestQuestion, Step, TopoLink, TopoNode } from '../../types/configLab';

export const NODES: TopoNode[] = [
  { id: 'PC-A', x: 60, role: 'host' },
  { id: 'R1', x: 260, role: 'router' },
  { id: 'R2', x: 460, role: 'router' },
  { id: 'R3', x: 660, role: 'router' },
  { id: 'PC-C', x: 860, role: 'host' },
];

export const LINKS: TopoLink[] = [
  { from: 'PC-A', to: 'R1', subnet: '10.80.1.0/24', if1: '', if2: 'g0/0', activateOnSteps: [2, 200] },
  { from: 'R1', to: 'R2', subnet: '10.80.2.0/30', if1: 'g0/1', if2: 'g0/0', activateOnSteps: [3, 5] },
  { from: 'R2', to: 'R3', subnet: '10.80.2.4/30', if1: 'g0/1', if2: 'g0/0', activateOnSteps: [6, 8] },
  { from: 'R3', to: 'PC-C', subnet: '10.80.3.0/24', if1: 'g0/1', if2: '', activateOnSteps: [9, 201] },
];

export const NODE_IP_LABELS: Record<string, string> = {
  'PC-A': '10.80.1.10',
  R1: '10.80.1.1',
  R2: '10.80.2.5',
  R3: '10.80.3.1',
  'PC-C': '10.80.3.10',
};

export const CONFIG_ROUTER_WORDS = ['network', 'no', 'auto-summary', 'exit'];

const SHOW_IP_PROTOCOLS_PAT = /^do\s+sh(ow)?\s+ip\s+prot(o(c(o(l(s)?)?)?)?)?$/i;
const SHOW_EIGRP_NEIGHBORS_PAT = /^do\s+sh(ow)?\s+ip\s+eigrp\s+neigh(b(o(r(s)?)?)?)?$/i;

export const STEPS: Step[] = [
  {
    id: 1,
    router: 'R1',
    name: 'R1 — enable & configure terminal',
    short: 'R1 enable',
    mode: 'exec',
    prompt: 'Router>',
    cmdHint: { cmd: 'Router> enable', desc: 'เข้า Privileged EXEC ก่อน แล้วพิมพ์ configure terminal' },
    hints: [
      { cmd: 'Router> enable', desc: 'เข้าสู่ Privileged EXEC mode ก่อน' },
      { cmd: 'Router# configure terminal', desc: 'เข้าสู่ Global Configuration mode' },
    ],
    answer: 'enable\nconfigure terminal',
    commands: [
      { mode: 'exec', pat: ENABLE_PAT, next: 'exec-priv', pr: 'Router#', adv: false, msg: '' },
      { mode: 'exec-priv', pat: CONFT_PAT, next: 'config', pr: 'Router(config)#', adv: true, msg: 'Enter configuration commands, one per line.\nRouter(config)#' },
    ],
  },
  {
    id: 21,
    router: 'R1',
    name: 'R1 — ตั้งชื่อ hostname',
    short: 'hostname R1',
    mode: 'config',
    prompt: 'Router(config)#',
    cmdHint: { cmd: 'Router(config)# hostname R1', desc: 'ตั้งชื่ออุปกรณ์เป็น R1 — ควรทำเป็นอย่างแรกก่อนตั้งค่าอื่น' },
    hints: [{ cmd: 'Router(config)# hostname R1', desc: 'ตั้งชื่ออุปกรณ์เป็น R1' }],
    answer: 'hostname R1',
    commands: [{ mode: 'config', pat: hostnamePat('R1'), next: 'config', pr: 'R1(config)#', adv: true, msg: '✓ Hostname เปลี่ยนเป็น R1 แล้วครับ (สังเกต prompt ที่เปลี่ยนไป)' }],
  },
  {
    id: 2,
    router: 'R1',
    name: 'R1 — g0/0 LAN 10.80.1.1/24',
    short: 'g0/0 LAN',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# interface g0/0', desc: 'LAN ฝั่ง PC-A: 10.80.1.1/24 — เส้น PC-A—R1 จะเขียว' },
    hints: [
      { cmd: 'R1(config)# interface g0/0', desc: 'LAN ฝั่ง PC-A: 10.80.1.1/24 — เส้น PC-A—R1 จะเขียว' },
      { cmd: 'R1(config-if)# ip address 10.80.1.1 255.255.255.0', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R1(config-if)# no shutdown', desc: 'เปิดใช้งาน interface (ไม่งั้นจะ down ตลอด)' },
      { cmd: 'R1(config-if)# exit', desc: 'ออกจาก interface mode กลับสู่ config mode' },
    ],
    answer: 'interface g0/0\nip address 10.80.1.1 255.255.255.0\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('0'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('10.80.1.1', '255.255.255.0'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to up' },
      { mode: 'config-if', pat: EXIT_PAT, next: 'config', pr: 'R1(config)#', adv: true, msg: '✓ g0/0 → 10.80.1.1/24 UP\n  เส้น PC-A—R1 เขียวครึ่งเดียว รอ PC-A ตั้ง IP ด้วยครับ' },
    ],
  },
  {
    id: 3,
    router: 'R1',
    name: 'R1 — g0/1 WAN 10.80.2.1/30',
    short: 'g0/1 WAN',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# interface g0/1', desc: 'WAN ฝั่ง R2: 10.80.2.1/30 — เส้น R1—R2 จะเขียว' },
    hints: [
      { cmd: 'R1(config)# interface g0/1', desc: 'WAN ฝั่ง R2: 10.80.2.1/30 — เส้น R1—R2 จะเขียว' },
      { cmd: 'R1(config-if)# ip address 10.80.2.1 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้ (VLSM /30 สำหรับลิงก์จุดต่อจุด)' },
      { cmd: 'R1(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R1(config-if)# exit', desc: 'ออกจาก interface mode กลับสู่ config mode' },
    ],
    answer: 'interface g0/1\nip address 10.80.2.1 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('1'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('10.80.2.1', '255.255.255.252'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to up' },
      {
        mode: 'config-if',
        pat: EXIT_PAT,
        next: 'config',
        pr: 'R1(config)#',
        adv: true,
        msg: '✓ g0/1 → 10.80.2.1/30 UP\n  เส้น R1—R2 เขียวแล้วครับ — ต่อไปตั้งค่า PC-A ก่อน แล้วค่อยไปตั้ง IP ของ R2',
      },
    ],
  },
  {
    id: 200,
    router: 'PC-A',
    type: 'pcconfig',
    name: 'PC-A — ตั้งค่า IP / Subnet / Gateway',
    short: 'PC-A config',
    mode: 'pcconfig',
    prompt: '(คลิก PC-A)',
    expected: { ip: '10.80.1.10', mask: '255.255.255.0', gateway: '10.80.1.1' },
    cmdHint: { cmd: '(คลิกที่ไอคอน PC-A บนแผนภาพด้านบน)', desc: 'กำหนด IP/Subnet/Gateway ให้ PC-A ผ่านหน้าต่างตั้งค่า' },
  },
  {
    id: 4,
    router: 'R2',
    name: 'R2 — enable & configure terminal',
    short: 'R2 enable',
    mode: 'exec',
    prompt: 'Router>',
    cmdHint: { cmd: 'Router> enable', desc: 'สลับไปทำ R2 — enable แล้ว configure terminal' },
    hints: [
      { cmd: 'Router> enable', desc: 'สลับไปทำ R2 — เข้าสู่ Privileged EXEC' },
      { cmd: 'Router# configure terminal', desc: 'เข้าสู่ Global Configuration mode' },
    ],
    answer: 'enable\nconfigure terminal',
    commands: [
      { mode: 'exec', pat: ENABLE_PAT, next: 'exec-priv', pr: 'Router#', adv: false, msg: '' },
      { mode: 'exec-priv', pat: CONFT_PAT, next: 'config', pr: 'Router(config)#', adv: true, msg: 'Enter configuration commands, one per line.\nRouter(config)#' },
    ],
  },
  {
    id: 22,
    router: 'R2',
    name: 'R2 — ตั้งชื่อ hostname',
    short: 'hostname R2',
    mode: 'config',
    prompt: 'Router(config)#',
    cmdHint: { cmd: 'Router(config)# hostname R2', desc: 'ตั้งชื่ออุปกรณ์เป็น R2' },
    hints: [{ cmd: 'Router(config)# hostname R2', desc: 'ตั้งชื่ออุปกรณ์เป็น R2' }],
    answer: 'hostname R2',
    commands: [{ mode: 'config', pat: hostnamePat('R2'), next: 'config', pr: 'R2(config)#', adv: true, msg: '✓ Hostname เปลี่ยนเป็น R2 แล้วครับ' }],
  },
  {
    id: 5,
    router: 'R2',
    name: 'R2 — g0/0 (←R1) 10.80.2.2/30',
    short: 'g0/0 ←R1',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# interface g0/0', desc: 'ฝั่ง R1: 10.80.2.2/30' },
    hints: [
      { cmd: 'R2(config)# interface g0/0', desc: 'ฝั่ง R1: 10.80.2.2/30' },
      { cmd: 'R2(config-if)# ip address 10.80.2.2 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R2(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R2(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/0\nip address 10.80.2.2 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('0'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('10.80.2.2', '255.255.255.252'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to up' },
      { mode: 'config-if', pat: EXIT_PAT, next: 'config', pr: 'R2(config)#', adv: true, msg: '✓ g0/0 → 10.80.2.2/30 UP' },
    ],
  },
  {
    id: 6,
    router: 'R2',
    name: 'R2 — g0/1 (→R3) 10.80.2.5/30',
    short: 'g0/1 →R3',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# interface g0/1', desc: 'ฝั่ง R3: 10.80.2.5/30 — เส้น R2—R3 จะเขียว' },
    hints: [
      { cmd: 'R2(config)# interface g0/1', desc: 'ฝั่ง R3: 10.80.2.5/30 — เส้น R2—R3 จะเขียว' },
      { cmd: 'R2(config-if)# ip address 10.80.2.5 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R2(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R2(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/1\nip address 10.80.2.5 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('1'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('10.80.2.5', '255.255.255.252'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to up' },
      {
        mode: 'config-if',
        pat: EXIT_PAT,
        next: 'config',
        pr: 'R2(config)#',
        adv: true,
        msg: '✓ g0/1 → 10.80.2.5/30 UP\n  เส้น R2—R3 เขียวแล้วครับ — สลับไปตั้ง IP ของ R3 ต่อได้เลยครับ',
      },
    ],
  },
  {
    id: 7,
    router: 'R3',
    name: 'R3 — enable & configure terminal',
    short: 'R3 enable',
    mode: 'exec',
    prompt: 'Router>',
    cmdHint: { cmd: 'Router> enable', desc: 'สลับไปทำ R3 — enable แล้ว configure terminal' },
    hints: [
      { cmd: 'Router> enable', desc: 'สลับไปทำ R3 — เข้าสู่ Privileged EXEC' },
      { cmd: 'Router# configure terminal', desc: 'เข้าสู่ Global Configuration mode' },
    ],
    answer: 'enable\nconfigure terminal',
    commands: [
      { mode: 'exec', pat: ENABLE_PAT, next: 'exec-priv', pr: 'Router#', adv: false, msg: '' },
      { mode: 'exec-priv', pat: CONFT_PAT, next: 'config', pr: 'Router(config)#', adv: true, msg: 'Enter configuration commands, one per line.\nRouter(config)#' },
    ],
  },
  {
    id: 23,
    router: 'R3',
    name: 'R3 — ตั้งชื่อ hostname',
    short: 'hostname R3',
    mode: 'config',
    prompt: 'Router(config)#',
    cmdHint: { cmd: 'Router(config)# hostname R3', desc: 'ตั้งชื่ออุปกรณ์เป็น R3' },
    hints: [{ cmd: 'Router(config)# hostname R3', desc: 'ตั้งชื่ออุปกรณ์เป็น R3' }],
    answer: 'hostname R3',
    commands: [{ mode: 'config', pat: hostnamePat('R3'), next: 'config', pr: 'R3(config)#', adv: true, msg: '✓ Hostname เปลี่ยนเป็น R3 แล้วครับ' }],
  },
  {
    id: 8,
    router: 'R3',
    name: 'R3 — g0/0 (←R2) 10.80.2.6/30',
    short: 'g0/0 ←R2',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# interface g0/0', desc: 'ฝั่ง R2: 10.80.2.6/30' },
    hints: [
      { cmd: 'R3(config)# interface g0/0', desc: 'ฝั่ง R2: 10.80.2.6/30' },
      { cmd: 'R3(config-if)# ip address 10.80.2.6 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R3(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R3(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/0\nip address 10.80.2.6 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('0'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('10.80.2.6', '255.255.255.252'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to up' },
      { mode: 'config-if', pat: EXIT_PAT, next: 'config', pr: 'R3(config)#', adv: true, msg: '✓ g0/0 → 10.80.2.6/30 UP' },
    ],
  },
  {
    id: 9,
    router: 'R3',
    name: 'R3 — g0/1 LAN 10.80.3.1/24',
    short: 'g0/1 LAN',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# interface g0/1', desc: 'LAN ฝั่ง PC-C: 10.80.3.1/24 — เส้น R3—PC-C จะเขียว' },
    hints: [
      { cmd: 'R3(config)# interface g0/1', desc: 'LAN ฝั่ง PC-C: 10.80.3.1/24 — เส้น R3—PC-C จะเขียว' },
      { cmd: 'R3(config-if)# ip address 10.80.3.1 255.255.255.0', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R3(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R3(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/1\nip address 10.80.3.1 255.255.255.0\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('1'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('10.80.3.1', '255.255.255.0'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to up' },
      {
        mode: 'config-if',
        pat: EXIT_PAT,
        next: 'config',
        pr: 'R3(config)#',
        adv: true,
        msg: '✓ g0/1 → 10.80.3.1/24 UP\n  ต่อไปตั้งค่า PC-C ให้ครบตามหลักการก่อนครับ',
      },
    ],
  },
  {
    id: 201,
    router: 'PC-C',
    type: 'pcconfig',
    name: 'PC-C — ตั้งค่า IP / Subnet / Gateway',
    short: 'PC-C config',
    mode: 'pcconfig',
    prompt: '(คลิก PC-C)',
    expected: { ip: '10.80.3.10', mask: '255.255.255.0', gateway: '10.80.3.1' },
    cmdHint: { cmd: '(คลิกที่ไอคอน PC-C บนแผนภาพด้านบน)', desc: 'กำหนด IP/Subnet/Gateway ให้ PC-C ผ่านหน้าต่างตั้งค่า' },
  },

  // ── เฟส 2: ที่เหลือของ R3 (เปิด EIGRP, ตรวจสอบ, save) — R3 ไปก่อนจึงยังไม่มี Neighbor เลย ใช้ show ip protocols ตรวจสอบแทน ──
  {
    id: 10,
    router: 'R3',
    name: 'R3 — เปิดใช้งาน EIGRP (AS 100)',
    short: 'EIGRP setup',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# router eigrp 100', desc: 'เข้าสู่โหมดตั้งค่า EIGRP บน Autonomous System 100' },
    hints: [
      { cmd: 'R3(config)# router eigrp 100', desc: 'เข้าสู่โหมดตั้งค่า EIGRP บน Autonomous System 100 (ทุก Router ต้องใช้เลข AS เดียวกัน)' },
      { cmd: 'R3(config-router)# network 10.80.2.4 0.0.0.3', desc: 'ประกาศ network ฝั่ง R2 ด้วย wildcard mask — ลิงก์นี้เป็น /30 (255.255.255.252) ให้หา inverse เอง' },
      { cmd: 'R3(config-router)# network 10.80.3.0 0.0.0.255', desc: 'ประกาศ network ฝั่ง PC-C ด้วย wildcard mask — วง LAN นี้เป็น /24 (255.255.255.0) ให้หา inverse เอง' },
      { cmd: 'R3(config-router)# no auto-summary', desc: 'ปิดการสรุป subnet อัตโนมัติที่ classful boundary — EIGRP (AS-number mode) เปิด auto-summary ไว้เป็น default เหมือน RIP' },
    ],
    answer: 'router eigrp 100\nnetwork 10.80.2.4 0.0.0.3\nnetwork 10.80.3.0 0.0.0.255\nno auto-summary',
    commands: [
      { mode: 'config', pat: routerEigrpPat('100'), next: 'config-router', pr: 'R3(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: networkWildcardPat('10.80.2.4', '0.0.0.3'), next: 'config-router', pr: 'R3(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: networkWildcardPat('10.80.3.0', '0.0.0.255'), next: 'config-router', pr: 'R3(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: NOAUTOSUM_PAT, next: 'config', pr: 'R3(config)#', adv: true, msg: '✓ เปิด EIGRP (AS 100) บน R3 แล้วครับ — ประกาศ network ทั้ง 2 ฝั่งพร้อมปิด auto-summary' },
    ],
  },
  {
    id: 11,
    router: 'R3',
    name: 'R3 — ตรวจสอบด้วย show ip protocols (Checkpoint)',
    short: 'show protocols',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# do show ip protocols', desc: 'ตรวจสอบว่า EIGRP process กำลังทำงานอยู่ก่อน save (R3 ทำก่อน จึงยังไม่มี Neighbor ให้ดู)' },
    answer: 'do show ip protocols',
    commands: [
      {
        mode: 'config',
        pat: SHOW_IP_PROTOCOLS_PAT,
        next: 'config',
        pr: 'R3(config)#',
        adv: true,
        msg: 'Routing Protocol is "eigrp 100"\n  EIGRP-IPv4 Protocol for AS(100)\n    Automatic Summarization: disabled\n    Routing for Networks:\n      10.80.2.4/30\n      10.80.3.0/24\n    Distance: internal 90 external 170\n\n✓ EIGRP process กำลังทำงานอยู่ครับ — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },
  {
    id: 12,
    router: 'R3',
    name: 'R3 — end & write memory',
    short: 'save R3',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# end  →  write memory', desc: 'บันทึก config R3 ที่ตั้งค่าไว้ให้ถาวร' },
    hints: [
      { cmd: 'R3(config)# end', desc: 'ออกจาก config mode (end หรือ exit ก็ได้)' },
      { cmd: 'R3# write memory', desc: 'บันทึก config R3 ที่ตั้งค่าไว้ให้ถาวร' },
    ],
    answer: 'end\nwrite memory',
    commands: [
      { mode: 'config', pat: END_OR_EXIT_PAT, next: 'exec-priv', pr: 'R3#', adv: false, msg: 'R3#' },
      { mode: 'exec-priv', pat: writeMemPat(), next: 'exec-priv', pr: 'R3#', adv: true, msg: 'Building configuration...\n[OK]\n✓ R3 config บันทึกแล้วครับ — สลับไปทำ R2 ต่อครับ' },
    ],
  },

  // ── เฟส 2 (ต่อ): ที่เหลือของ R2 (เปิด EIGRP, ตรวจสอบ, save) — R3 ตั้งค่าไปก่อนแล้ว พอ R2 เสร็จ Neighbor กับ R3 จะขึ้นทันที ──
  {
    id: 13,
    router: 'R2',
    name: 'R2 — เปิดใช้งาน EIGRP (AS 100)',
    short: 'EIGRP setup',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# router eigrp 100', desc: 'เข้าสู่โหมดตั้งค่า EIGRP บน Autonomous System 100' },
    hints: [
      { cmd: 'R2(config)# router eigrp 100', desc: 'เข้าสู่โหมดตั้งค่า EIGRP บน Autonomous System 100' },
      { cmd: 'R2(config-router)# network 10.80.2.0 0.0.0.3', desc: 'ประกาศ network ฝั่ง R1 ด้วย wildcard mask — ลิงก์นี้เป็น /30 ให้หา inverse เอง' },
      { cmd: 'R2(config-router)# network 10.80.2.4 0.0.0.3', desc: 'ประกาศ network ฝั่ง R3 ด้วย wildcard mask — ลิงก์นี้เป็น /30 ให้หา inverse เอง' },
      { cmd: 'R2(config-router)# no auto-summary', desc: 'ปิดการสรุป subnet อัตโนมัติที่ classful boundary' },
    ],
    answer: 'router eigrp 100\nnetwork 10.80.2.0 0.0.0.3\nnetwork 10.80.2.4 0.0.0.3\nno auto-summary',
    commands: [
      { mode: 'config', pat: routerEigrpPat('100'), next: 'config-router', pr: 'R2(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: networkWildcardPat('10.80.2.0', '0.0.0.3'), next: 'config-router', pr: 'R2(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: networkWildcardPat('10.80.2.4', '0.0.0.3'), next: 'config-router', pr: 'R2(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: NOAUTOSUM_PAT, next: 'config', pr: 'R2(config)#', adv: true, msg: '✓ เปิด EIGRP (AS 100) บน R2 แล้วครับ — ประกาศ network ทั้ง 2 ฝั่งพร้อมปิด auto-summary' },
    ],
  },
  {
    id: 14,
    router: 'R2',
    name: 'R2 — ตรวจสอบ Neighbor ด้วย show ip eigrp neighbors (Checkpoint)',
    short: 'show neighbors',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# do show ip eigrp neighbors', desc: 'ตรวจสอบว่า R2 เจอ Neighbor (R3) ผ่าน EIGRP แล้วก่อน save — R3 config ไว้ก่อนแล้ว จึงควรเห็น Neighbor ทันที' },
    answer: 'do show ip eigrp neighbors',
    commands: [
      {
        mode: 'config',
        pat: SHOW_EIGRP_NEIGHBORS_PAT,
        next: 'config',
        pr: 'R2(config)#',
        adv: true,
        msg: 'EIGRP-IPv4 Neighbors for AS(100)\nH   Address         Interface    Hold Uptime   SRTT   RTO  Q  Seq\n0   10.80.2.6       Gi0/1        13   00:00:05  1     200  0  3\n\n✓ เห็น Neighbor R3 (10.80.2.6) ผ่าน EIGRP แล้วครับ — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },
  {
    id: 15,
    router: 'R2',
    name: 'R2 — end & write memory',
    short: 'save R2',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# end  →  write memory', desc: 'บันทึก config R2' },
    hints: [
      { cmd: 'R2(config)# end', desc: 'ออกจาก config mode (end หรือ exit ก็ได้)' },
      { cmd: 'R2# write memory', desc: 'บันทึก config R2 ที่ตั้งค่าไว้ให้ถาวร' },
    ],
    answer: 'end\nwrite memory',
    commands: [
      { mode: 'config', pat: END_OR_EXIT_PAT, next: 'exec-priv', pr: 'R2#', adv: false, msg: 'R2#' },
      { mode: 'exec-priv', pat: writeMemPat(), next: 'exec-priv', pr: 'R2#', adv: true, msg: 'Building configuration...\n[OK]\n✓ R2 config บันทึกแล้วครับ — สลับไปทำ R1 ต่อครับ' },
    ],
  },

  // ── เฟส 3: ที่เหลือของ R1 (เปิด EIGRP, ตรวจสอบ, save) แล้วตรวจสอบผลลัพธ์รวม — R2 ตั้งค่าไปก่อนแล้ว พอ R1 เสร็จ Neighbor กับ R2 จะขึ้นทันที ──
  {
    id: 16,
    router: 'R1',
    name: 'R1 — เปิดใช้งาน EIGRP (AS 100)',
    short: 'EIGRP setup',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# router eigrp 100', desc: 'เข้าสู่โหมดตั้งค่า EIGRP บน Autonomous System 100' },
    hints: [
      { cmd: 'R1(config)# router eigrp 100', desc: 'เข้าสู่โหมดตั้งค่า EIGRP บน Autonomous System 100' },
      { cmd: 'R1(config-router)# network 10.80.1.0 0.0.0.255', desc: 'ประกาศ network ฝั่ง PC-A ด้วย wildcard mask — วง LAN นี้เป็น /24 ให้หา inverse เอง' },
      { cmd: 'R1(config-router)# network 10.80.2.0 0.0.0.3', desc: 'ประกาศ network ฝั่ง R2 ด้วย wildcard mask — ลิงก์นี้เป็น /30 ให้หา inverse เอง' },
      { cmd: 'R1(config-router)# no auto-summary', desc: 'ปิดการสรุป subnet อัตโนมัติที่ classful boundary' },
    ],
    answer: 'router eigrp 100\nnetwork 10.80.1.0 0.0.0.255\nnetwork 10.80.2.0 0.0.0.3\nno auto-summary',
    commands: [
      { mode: 'config', pat: routerEigrpPat('100'), next: 'config-router', pr: 'R1(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: networkWildcardPat('10.80.1.0', '0.0.0.255'), next: 'config-router', pr: 'R1(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: networkWildcardPat('10.80.2.0', '0.0.0.3'), next: 'config-router', pr: 'R1(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: NOAUTOSUM_PAT, next: 'config', pr: 'R1(config)#', adv: true, msg: '✓ เปิด EIGRP (AS 100) บน R1 แล้วครับ — ประกาศ network ทั้ง 2 ฝั่งพร้อมปิด auto-summary' },
    ],
  },
  {
    id: 17,
    router: 'R1',
    name: 'R1 — ตรวจสอบ Neighbor ด้วย show ip eigrp neighbors (Checkpoint)',
    short: 'show neighbors',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# do show ip eigrp neighbors', desc: 'ตรวจสอบว่า R1 เจอ Neighbor (R2) ผ่าน EIGRP แล้วก่อน save — ใช้ do นำหน้าเพื่อรันคำสั่ง show จาก config mode ได้เลยโดยไม่ต้อง exit' },
    answer: 'do show ip eigrp neighbors',
    commands: [
      {
        mode: 'config',
        pat: SHOW_EIGRP_NEIGHBORS_PAT,
        next: 'config',
        pr: 'R1(config)#',
        adv: true,
        msg: 'EIGRP-IPv4 Neighbors for AS(100)\nH   Address         Interface    Hold Uptime   SRTT   RTO  Q  Seq\n0   10.80.2.2       Gi0/1        11   00:00:03  1     200  0  2\n\n✓ เห็น Neighbor R2 (10.80.2.2) ผ่าน EIGRP แล้วครับ — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },
  {
    id: 18,
    router: 'R1',
    name: 'R1 — end & write memory',
    short: 'save R1',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# end  →  write memory', desc: 'บันทึก config R1 ไปยัง NVRAM' },
    hints: [
      { cmd: 'R1(config)# end', desc: 'ออกจาก config mode กลับสู่ Privileged EXEC (end หรือ exit ก็ได้)' },
      { cmd: 'R1# write memory', desc: 'บันทึก config ที่ตั้งค่าไว้ให้ถาวรไปยังหน่วยความจำของ Router' },
    ],
    answer: 'end\nwrite memory',
    commands: [
      { mode: 'config', pat: END_OR_EXIT_PAT, next: 'exec-priv', pr: 'R1#', adv: false, msg: 'R1#' },
      { mode: 'exec-priv', pat: writeMemPat(), next: 'exec-priv', pr: 'R1#', adv: true, msg: 'Building configuration...\n[OK]\n✓ R1 config บันทึกแล้วครับ' },
    ],
  },
  {
    id: 19,
    router: 'R1',
    name: 'R1 — ตรวจสอบ Routing Table รวม (show ip route)',
    short: 'show route',
    mode: 'exec-priv',
    prompt: 'R1#',
    cmdHint: { cmd: 'R1# show ip route', desc: 'ดู network ที่ R1 เรียนรู้มาจาก EIGRP โดยอัตโนมัติ (ไม่ต้องพิมพ์ ip route เองเลย) — สังเกตรหัส D (EIGRP)' },
    answer: 'show ip route',
    commands: [
      {
        mode: 'exec-priv',
        pat: /^sh(ow)?\s+ip\s+route$/i,
        next: 'exec-priv',
        pr: 'R1#',
        adv: true,
        msg: 'Codes: L - local, C - connected, D - EIGRP\n\nC    10.80.1.0/24 is directly connected, GigabitEthernet0/0\nC    10.80.2.0/30 is directly connected, GigabitEthernet0/1\nD    10.80.2.4/30 [90/30720] via 10.80.2.2, 00:00:08, GigabitEthernet0/1\nD    10.80.3.0/24 [90/33280] via 10.80.2.2, 00:00:08, GigabitEthernet0/1\n\n✓ เห็น network 10.80.2.4/30 และ 10.80.3.0/24 ที่เรียนรู้มาจาก EIGRP (D) แล้วครับ — ไม่ต้องพิมพ์ ip route เอง',
      },
    ],
  },
  {
    id: 20,
    router: 'PC-A',
    type: 'pcping',
    name: 'PC-A — ทดสอบ ping ไปยัง PC-C ผ่าน Command Prompt',
    short: 'ping PC-C (PC)',
    mode: 'pcping',
    prompt: '(คลิก PC-A)',
    target: { ip: '10.80.3.10', label: 'PC-C' },
    cmdHint: {
      cmd: '(คลิกที่ไอคอน PC-A บนแผนภาพด้านบน แล้วพิมพ์ ping 10.80.3.10 ในหน้า Command Prompt)',
      desc: 'ทดสอบว่า PC-A คุยกับ PC-C ได้จริงจากมุมมองผู้ใช้งานทั่วไป (ไม่ผ่าน Router) — ยืนยันว่า EIGRP พาไปถึงปลายทางได้จริง',
    },
  },
];

export const PRETEST: PretestQuestion[] = [
  {
    id: 'q1',
    type: 'mcq',
    q: 'EIGRP เป็น Routing Protocol ประเภทไหน?',
    opts: ['Distance Vector ล้วนๆ เหมือน RIP', 'Advanced Distance Vector (Hybrid) ผสมแนวคิด Link-State', 'Link-State ล้วนๆ เหมือน OSPF', 'Path-Vector เหมือน BGP'],
    ans: 1,
    exp: 'EIGRP เป็น Advanced Distance Vector (บางตำราเรียก Hybrid) ใช้แนวคิด Distance Vector เป็นหลัก แต่เพิ่มกลไกแบบ Link-State เช่น DUAL algorithm และ Topology Table เพื่อคำนวณเส้นทางสำรองไว้ล่วงหน้า ทำให้ Converge เร็วกว่า RIP มาก',
  },
  {
    id: 'q2',
    type: 'mcq',
    q: 'EIGRP (ค่า default) ใช้ metric คำนวณจากอะไรเป็นหลัก?',
    opts: ['Hop Count อย่างเดียวเหมือน RIP', 'Bandwidth และ Delay', 'จำนวน Router ที่ผ่านเท่านั้น', 'Cost ตาม Bandwidth แบบ OSPF'],
    ans: 1,
    exp: 'EIGRP รองรับ metric แบบ composite ได้หลายปัจจัย แต่ค่า default ที่ IOS ใช้จริงคือ Bandwidth (ค่าต่ำสุดตลอดเส้นทาง) และ Delay (ผลรวมทั้งเส้นทาง) ต่างจาก RIP ที่ใช้แค่ Hop Count เพียงอย่างเดียว',
  },
  {
    id: 'q3',
    type: 'mcq',
    q: 'คำสั่งใดใช้ประกาศ network ให้ EIGRP บน interface ที่มี IP 10.80.2.0/30?',
    opts: ['network 10.80.2.0', 'network 10.80.2.0 255.255.255.252', 'network 10.80.2.0 0.0.0.3', 'router eigrp 10.80.2.0'],
    ans: 2,
    exp: 'EIGRP แบบ classic (AS-number mode) ต้องระบุ wildcard mask (inverse mask) ต่อท้าย network เสมอ วิธีหาคือเอา 255 ลบแต่ละ Octet ของ Subnet Mask เช่น /16 (255.255.0.0) จะได้ wildcard 0.0.255.255 (ตรงข้ามบิตกับ subnet mask 255.255.255.252) ต่างจาก RIP ที่ใช้แค่ major network ไม่มี mask เลย',
  },
  {
    id: 'q4',
    type: 'dragdrop',
    q: 'จับคู่คำสั่งกับหน้าที่ของมัน',
    pairs: [
      { left: 'router eigrp 100', right: 'เข้าสู่โหมดตั้งค่า EIGRP บน Autonomous System 100' },
      { left: 'network 10.80.1.0 0.0.0.255', right: 'ประกาศ network ด้วย wildcard mask (inverse mask ของ /24)' },
      { left: 'no auto-summary', right: 'ปิดการสรุป subnet อัตโนมัติที่ classful boundary' },
      { left: 'show ip eigrp neighbors', right: 'ตรวจสอบว่า Router เพื่อนบ้านที่ทำ EIGRP ด้วยกัน (Neighbor) ขึ้นสถานะแล้ว' },
    ],
  },
];

export const INTRO_LINES = [
  { text: '# Ch.8 EIGRP — NETLab', cls: 't-info' },
  { text: '# อ้างอิง: Cisco Networking Academy W8', cls: 't-hint' },
  { text: '# Topology: PC-A—R1—R2—R3—PC-C (ใช้ VLSM: LAN /24, WAN /30)', cls: 't-dim' },
  { text: '# R1: g0/0=10.80.1.1/24  g0/1=10.80.2.1/30', cls: 't-dim' },
  { text: '# R2: g0/0=10.80.2.2/30  g0/1=10.80.2.5/30', cls: 't-dim' },
  { text: '# R3: g0/0=10.80.2.6/30  g0/1=10.80.3.1/24', cls: 't-dim' },
  { text: '# EIGRP Autonomous System: 100', cls: 't-dim' },
  { text: '' },
  { text: '# เริ่มที่ R1 — พิมพ์: enable', cls: 't-hint' },
];

export const WELCOME_MSG =
  'สวัสดีครับ! Ch.8 EIGRP\n\nTopology: PC-A—R1—R2—R3—PC-C (ใช้ VLSM: LAN /24, WAN /30)\nขั้นตอนแรก: ตั้งชื่อ hostname และ IP ให้ครบทุกอุปกรณ์ก่อน (รวม PC-A, PC-C ด้วย — คลิกที่ไอคอน PC บนแผนภาพเพื่อกรอก IP) แล้วค่อยเปิด EIGRP (AS 100 + wildcard mask + no auto-summary) ให้ Router เรียนรู้เส้นทางกันเองอัตโนมัติ รวม 25 steps (มีจุด Checkpoint ตรวจสอบด้วย show ก่อน save ทุก Router — สังเกตว่า Checkpoint ของ R2/R1 จะเห็น Neighbor ขึ้นจริง เพราะฝั่งตรงข้ามตั้งค่าไปก่อนแล้ว)\nแต่ละเส้นจะเขียวเมื่อทั้งสองฝั่งตั้งค่าเสร็จครับ\n\nทำ Pre-test ก่อนหรือข้ามไป Lab เลยก็ได้ครับ';

export const COMPLETE_CHAT_SUMMARY =
  'ยินดีด้วยครับ! Lab Ch.8 เสร็จสมบูรณ์!\n\nสรุป:\n• R1, R2, R3: ตั้ง IP แบบ VLSM ครบทุก interface (LAN /24, WAN /30) แล้วเปิด EIGRP (router eigrp 100 + network พร้อม wildcard mask + no auto-summary)\n• Router ทั้ง 3 ตัวเรียนรู้เส้นทางกันเองอัตโนมัติผ่าน DUAL algorithm เห็น Neighbor ขึ้นสถานะและ route แบบ D (EIGRP)\n• Ping PC-A→PC-C สำเร็จผ่าน route ที่ EIGRP เรียนรู้เอง';
