/* NETLab — Lab 9 (OSPF) data, ported 1:1 from
   public/labnetwork1/lab09-ospf/lab9.html's inline <STEPS>/<NODES>/<LINKS>/
   <PRETEST> globals. Single-Area OSPF (Area 0); Process ID is locally
   significant so each router uses a different one (1/2/3) on purpose. Same
   shared <ConfigLab/> engine as lab05-08. */
import {
  CONFT_PAT,
  ENABLE_PAT,
  END_OR_EXIT_PAT,
  EXIT_PAT,
  NOSHUT_PAT,
  hostnamePat,
  ifpat,
  ipAddrPat,
  networkAreaPat,
  routerOspfPat,
  writeMemPat,
} from '../../lib/ciscoPatterns';
import type { PretestQuestion, Step, TopoLink, TopoNode } from '../../types/configLab';

export const NODES: TopoNode[] = [
  { id: 'PC-A', x: 60, role: 'host' },
  { id: 'R1', x: 260, role: 'router' },
  { id: 'R2', x: 460, role: 'router' },
  { id: 'R3', x: 660, role: 'router' },
  { id: 'PC-C', x: 860, role: 'host' },
];

export const LINKS: TopoLink[] = [
  { from: 'PC-A', to: 'R1', subnet: '10.90.1.0/24', if1: '', if2: 'g0/0', activateOnSteps: [2, 200] },
  { from: 'R1', to: 'R2', subnet: '10.90.2.0/30', if1: 'g0/1', if2: 'g0/0', activateOnSteps: [3, 5] },
  { from: 'R2', to: 'R3', subnet: '10.90.2.4/30', if1: 'g0/1', if2: 'g0/0', activateOnSteps: [6, 8] },
  { from: 'R3', to: 'PC-C', subnet: '10.90.3.0/24', if1: 'g0/1', if2: '', activateOnSteps: [9, 201] },
];

export const NODE_IP_LABELS: Record<string, string> = {
  'PC-A': '10.90.1.10',
  R1: '10.90.1.1',
  R2: '10.90.2.5',
  R3: '10.90.3.1',
  'PC-C': '10.90.3.10',
};

export const CONFIG_ROUTER_WORDS = ['network', 'area', 'exit'];

const SHOW_IP_PROTOCOLS_PAT = /^do\s+sh(ow)?\s+ip\s+prot(o(c(o(l(s)?)?)?)?)?$/i;
const SHOW_OSPF_NEIGHBOR_PAT = /^do\s+sh(ow)?\s+ip\s+ospf\s+neigh(b(o(r)?)?)?$/i;

export const STEPS: Step[] = [
  {
    id: 1,
    router: 'R1',
    name: 'R1 — enable & configure terminal',
    short: 'R1 enable',
    mode: 'exec',
    prompt: 'Router>',
    cmdHint: { cmd: 'Router> enable', desc: 'เข้า Privileged EXEC ก่อน แล้วพิมพ์ configure terminal' },
    hints: [
      { cmd: 'Router> enable', desc: 'เข้าสู่ Privileged EXEC mode ก่อน' },
      { cmd: 'Router# configure terminal', desc: 'เข้าสู่ Global Configuration mode' },
    ],
    answer: 'enable\nconfigure terminal',
    commands: [
      { mode: 'exec', pat: ENABLE_PAT, next: 'exec-priv', pr: 'Router#', adv: false, msg: '' },
      { mode: 'exec-priv', pat: CONFT_PAT, next: 'config', pr: 'Router(config)#', adv: true, msg: 'Enter configuration commands, one per line.\nRouter(config)#' },
    ],
  },
  {
    id: 21,
    router: 'R1',
    name: 'R1 — ตั้งชื่อ hostname',
    short: 'hostname R1',
    mode: 'config',
    prompt: 'Router(config)#',
    cmdHint: { cmd: 'Router(config)# hostname R1', desc: 'ตั้งชื่ออุปกรณ์เป็น R1 — ควรทำเป็นอย่างแรกก่อนตั้งค่าอื่น' },
    hints: [{ cmd: 'Router(config)# hostname R1', desc: 'ตั้งชื่ออุปกรณ์เป็น R1' }],
    answer: 'hostname R1',
    commands: [{ mode: 'config', pat: hostnamePat('R1'), next: 'config', pr: 'R1(config)#', adv: true, msg: '✓ Hostname เปลี่ยนเป็น R1 แล้วครับ (สังเกต prompt ที่เปลี่ยนไป)' }],
  },
  {
    id: 2,
    router: 'R1',
    name: 'R1 — g0/0 LAN 10.90.1.1/24',
    short: 'g0/0 LAN',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# interface g0/0', desc: 'LAN ฝั่ง PC-A: 10.90.1.1/24 — เส้น PC-A—R1 จะเขียว' },
    hints: [
      { cmd: 'R1(config)# interface g0/0', desc: 'LAN ฝั่ง PC-A: 10.90.1.1/24 — เส้น PC-A—R1 จะเขียว' },
      { cmd: 'R1(config-if)# ip address 10.90.1.1 255.255.255.0', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R1(config-if)# no shutdown', desc: 'เปิดใช้งาน interface (ไม่งั้นจะ down ตลอด)' },
      { cmd: 'R1(config-if)# exit', desc: 'ออกจาก interface mode กลับสู่ config mode' },
    ],
    answer: 'interface g0/0\nip address 10.90.1.1 255.255.255.0\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('0'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('10.90.1.1', '255.255.255.0'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to up' },
      { mode: 'config-if', pat: EXIT_PAT, next: 'config', pr: 'R1(config)#', adv: true, msg: '✓ g0/0 → 10.90.1.1/24 UP\n  เส้น PC-A—R1 เขียวครึ่งเดียว รอ PC-A ตั้ง IP ด้วยครับ' },
    ],
  },
  {
    id: 3,
    router: 'R1',
    name: 'R1 — g0/1 WAN 10.90.2.1/30',
    short: 'g0/1 WAN',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# interface g0/1', desc: 'WAN ฝั่ง R2: 10.90.2.1/30 — เส้น R1—R2 จะเขียว' },
    hints: [
      { cmd: 'R1(config)# interface g0/1', desc: 'WAN ฝั่ง R2: 10.90.2.1/30 — เส้น R1—R2 จะเขียว' },
      { cmd: 'R1(config-if)# ip address 10.90.2.1 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้ (VLSM /30 สำหรับลิงก์จุดต่อจุด)' },
      { cmd: 'R1(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R1(config-if)# exit', desc: 'ออกจาก interface mode กลับสู่ config mode' },
    ],
    answer: 'interface g0/1\nip address 10.90.2.1 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('1'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('10.90.2.1', '255.255.255.252'), next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R1(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to up' },
      {
        mode: 'config-if',
        pat: EXIT_PAT,
        next: 'config',
        pr: 'R1(config)#',
        adv: true,
        msg: '✓ g0/1 → 10.90.2.1/30 UP\n  เส้น R1—R2 เขียวแล้วครับ — ต่อไปตั้งค่า PC-A ก่อน แล้วค่อยไปตั้ง IP ของ R2',
      },
    ],
  },
  {
    id: 200,
    router: 'PC-A',
    type: 'pcconfig',
    name: 'PC-A — ตั้งค่า IP / Subnet / Gateway',
    short: 'PC-A config',
    mode: 'pcconfig',
    prompt: '(คลิก PC-A)',
    expected: { ip: '10.90.1.10', mask: '255.255.255.0', gateway: '10.90.1.1' },
    cmdHint: { cmd: '(คลิกที่ไอคอน PC-A บนแผนภาพด้านบน)', desc: 'กำหนด IP/Subnet/Gateway ให้ PC-A ผ่านหน้าต่างตั้งค่า' },
  },
  {
    id: 4,
    router: 'R2',
    name: 'R2 — enable & configure terminal',
    short: 'R2 enable',
    mode: 'exec',
    prompt: 'Router>',
    cmdHint: { cmd: 'Router> enable', desc: 'สลับไปทำ R2 — enable แล้ว configure terminal' },
    hints: [
      { cmd: 'Router> enable', desc: 'สลับไปทำ R2 — เข้าสู่ Privileged EXEC' },
      { cmd: 'Router# configure terminal', desc: 'เข้าสู่ Global Configuration mode' },
    ],
    answer: 'enable\nconfigure terminal',
    commands: [
      { mode: 'exec', pat: ENABLE_PAT, next: 'exec-priv', pr: 'Router#', adv: false, msg: '' },
      { mode: 'exec-priv', pat: CONFT_PAT, next: 'config', pr: 'Router(config)#', adv: true, msg: 'Enter configuration commands, one per line.\nRouter(config)#' },
    ],
  },
  {
    id: 22,
    router: 'R2',
    name: 'R2 — ตั้งชื่อ hostname',
    short: 'hostname R2',
    mode: 'config',
    prompt: 'Router(config)#',
    cmdHint: { cmd: 'Router(config)# hostname R2', desc: 'ตั้งชื่ออุปกรณ์เป็น R2' },
    hints: [{ cmd: 'Router(config)# hostname R2', desc: 'ตั้งชื่ออุปกรณ์เป็น R2' }],
    answer: 'hostname R2',
    commands: [{ mode: 'config', pat: hostnamePat('R2'), next: 'config', pr: 'R2(config)#', adv: true, msg: '✓ Hostname เปลี่ยนเป็น R2 แล้วครับ' }],
  },
  {
    id: 5,
    router: 'R2',
    name: 'R2 — g0/0 (←R1) 10.90.2.2/30',
    short: 'g0/0 ←R1',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# interface g0/0', desc: 'ฝั่ง R1: 10.90.2.2/30' },
    hints: [
      { cmd: 'R2(config)# interface g0/0', desc: 'ฝั่ง R1: 10.90.2.2/30' },
      { cmd: 'R2(config-if)# ip address 10.90.2.2 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R2(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R2(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/0\nip address 10.90.2.2 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('0'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('10.90.2.2', '255.255.255.252'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to up' },
      { mode: 'config-if', pat: EXIT_PAT, next: 'config', pr: 'R2(config)#', adv: true, msg: '✓ g0/0 → 10.90.2.2/30 UP' },
    ],
  },
  {
    id: 6,
    router: 'R2',
    name: 'R2 — g0/1 (→R3) 10.90.2.5/30',
    short: 'g0/1 →R3',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# interface g0/1', desc: 'ฝั่ง R3: 10.90.2.5/30 — เส้น R2—R3 จะเขียว' },
    hints: [
      { cmd: 'R2(config)# interface g0/1', desc: 'ฝั่ง R3: 10.90.2.5/30 — เส้น R2—R3 จะเขียว' },
      { cmd: 'R2(config-if)# ip address 10.90.2.5 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R2(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R2(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/1\nip address 10.90.2.5 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('1'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('10.90.2.5', '255.255.255.252'), next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R2(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to up' },
      {
        mode: 'config-if',
        pat: EXIT_PAT,
        next: 'config',
        pr: 'R2(config)#',
        adv: true,
        msg: '✓ g0/1 → 10.90.2.5/30 UP\n  เส้น R2—R3 เขียวแล้วครับ — สลับไปตั้ง IP ของ R3 ต่อได้เลยครับ',
      },
    ],
  },
  {
    id: 7,
    router: 'R3',
    name: 'R3 — enable & configure terminal',
    short: 'R3 enable',
    mode: 'exec',
    prompt: 'Router>',
    cmdHint: { cmd: 'Router> enable', desc: 'สลับไปทำ R3 — enable แล้ว configure terminal' },
    hints: [
      { cmd: 'Router> enable', desc: 'สลับไปทำ R3 — เข้าสู่ Privileged EXEC' },
      { cmd: 'Router# configure terminal', desc: 'เข้าสู่ Global Configuration mode' },
    ],
    answer: 'enable\nconfigure terminal',
    commands: [
      { mode: 'exec', pat: ENABLE_PAT, next: 'exec-priv', pr: 'Router#', adv: false, msg: '' },
      { mode: 'exec-priv', pat: CONFT_PAT, next: 'config', pr: 'Router(config)#', adv: true, msg: 'Enter configuration commands, one per line.\nRouter(config)#' },
    ],
  },
  {
    id: 23,
    router: 'R3',
    name: 'R3 — ตั้งชื่อ hostname',
    short: 'hostname R3',
    mode: 'config',
    prompt: 'Router(config)#',
    cmdHint: { cmd: 'Router(config)# hostname R3', desc: 'ตั้งชื่ออุปกรณ์เป็น R3' },
    hints: [{ cmd: 'Router(config)# hostname R3', desc: 'ตั้งชื่ออุปกรณ์เป็น R3' }],
    answer: 'hostname R3',
    commands: [{ mode: 'config', pat: hostnamePat('R3'), next: 'config', pr: 'R3(config)#', adv: true, msg: '✓ Hostname เปลี่ยนเป็น R3 แล้วครับ' }],
  },
  {
    id: 8,
    router: 'R3',
    name: 'R3 — g0/0 (←R2) 10.90.2.6/30',
    short: 'g0/0 ←R2',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# interface g0/0', desc: 'ฝั่ง R2: 10.90.2.6/30' },
    hints: [
      { cmd: 'R3(config)# interface g0/0', desc: 'ฝั่ง R2: 10.90.2.6/30' },
      { cmd: 'R3(config-if)# ip address 10.90.2.6 255.255.255.252', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R3(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R3(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/0\nip address 10.90.2.6 255.255.255.252\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('0'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('10.90.2.6', '255.255.255.252'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to up' },
      { mode: 'config-if', pat: EXIT_PAT, next: 'config', pr: 'R3(config)#', adv: true, msg: '✓ g0/0 → 10.90.2.6/30 UP' },
    ],
  },
  {
    id: 9,
    router: 'R3',
    name: 'R3 — g0/1 LAN 10.90.3.1/24',
    short: 'g0/1 LAN',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# interface g0/1', desc: 'LAN ฝั่ง PC-C: 10.90.3.1/24 — เส้น R3—PC-C จะเขียว' },
    hints: [
      { cmd: 'R3(config)# interface g0/1', desc: 'LAN ฝั่ง PC-C: 10.90.3.1/24 — เส้น R3—PC-C จะเขียว' },
      { cmd: 'R3(config-if)# ip address 10.90.3.1 255.255.255.0', desc: 'กำหนด IP address ให้ interface นี้' },
      { cmd: 'R3(config-if)# no shutdown', desc: 'เปิดใช้งาน interface' },
      { cmd: 'R3(config-if)# exit', desc: 'ออกจาก interface mode' },
    ],
    answer: 'interface g0/1\nip address 10.90.3.1 255.255.255.0\nno shutdown\nexit',
    commands: [
      { mode: 'config', pat: ifpat('1'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: ipAddrPat('10.90.3.1', '255.255.255.0'), next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '' },
      { mode: 'config-if', pat: NOSHUT_PAT, next: 'config-if', pr: 'R3(config-if)#', adv: false, msg: '%LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to up' },
      {
        mode: 'config-if',
        pat: EXIT_PAT,
        next: 'config',
        pr: 'R3(config)#',
        adv: true,
        msg: '✓ g0/1 → 10.90.3.1/24 UP\n  ต่อไปตั้งค่า PC-C ให้ครบตามหลักการก่อนครับ',
      },
    ],
  },
  {
    id: 201,
    router: 'PC-C',
    type: 'pcconfig',
    name: 'PC-C — ตั้งค่า IP / Subnet / Gateway',
    short: 'PC-C config',
    mode: 'pcconfig',
    prompt: '(คลิก PC-C)',
    expected: { ip: '10.90.3.10', mask: '255.255.255.0', gateway: '10.90.3.1' },
    cmdHint: { cmd: '(คลิกที่ไอคอน PC-C บนแผนภาพด้านบน)', desc: 'กำหนด IP/Subnet/Gateway ให้ PC-C ผ่านหน้าต่างตั้งค่า' },
  },

  // ── เฟส 2: ที่เหลือของ R3 (เปิด OSPF, ตรวจสอบ, save) — R3 ไปก่อนจึงยังไม่มี Neighbor เลย ใช้ show ip protocols ตรวจสอบแทน ──
  {
    id: 10,
    router: 'R3',
    name: 'R3 — เปิดใช้งาน OSPF (Process ID 3)',
    short: 'OSPF setup',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# router ospf 3', desc: 'เข้าสู่โหมดตั้งค่า OSPF — เลข Process ID (3) เป็นแค่ตัวเลขภายในเครื่องนี้เอง ไม่ต้องตรงกับ Router อื่น' },
    hints: [
      { cmd: 'R3(config)# router ospf 3', desc: 'เข้าสู่โหมดตั้งค่า OSPF ด้วย Process ID 3 — ต่างจาก EIGRP ตรงที่เลขนี้ Router แต่ละตัวใช้คนละเลขก็ได้ (Locally Significant)' },
      { cmd: 'R3(config-router)# network 10.90.2.4 0.0.0.3 area 0', desc: 'ประกาศ network ฝั่ง R2 ด้วย wildcard mask — ลิงก์นี้เป็น /30 ให้หา inverse เอง พร้อมระบุ Area 0 (Backbone Area)' },
      { cmd: 'R3(config-router)# network 10.90.3.0 0.0.0.255 area 0', desc: 'ประกาศ network ฝั่ง PC-C ด้วย wildcard mask — วง LAN นี้เป็น /24 ให้หา inverse เอง พร้อมระบุ Area 0 เช่นกัน' },
    ],
    answer: 'router ospf 3\nnetwork 10.90.2.4 0.0.0.3 area 0\nnetwork 10.90.3.0 0.0.0.255 area 0',
    commands: [
      { mode: 'config', pat: routerOspfPat('3'), next: 'config-router', pr: 'R3(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: networkAreaPat('10.90.2.4', '0.0.0.3', '0'), next: 'config-router', pr: 'R3(config-router)#', adv: false, msg: '' },
      {
        mode: 'config-router',
        pat: networkAreaPat('10.90.3.0', '0.0.0.255', '0'),
        next: 'config',
        pr: 'R3(config)#',
        adv: true,
        msg: '✓ เปิด OSPF (Process ID 3) บน R3 แล้วครับ — ประกาศ network ทั้ง 2 ฝั่งใน Area 0',
      },
    ],
  },
  {
    id: 11,
    router: 'R3',
    name: 'R3 — ตรวจสอบด้วย show ip protocols (Checkpoint)',
    short: 'show protocols',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# do show ip protocols', desc: 'ตรวจสอบว่า OSPF process กำลังทำงานอยู่ก่อน save (R3 ทำก่อน จึงยังไม่มี Neighbor ให้ดู)' },
    answer: 'do show ip protocols',
    commands: [
      {
        mode: 'config',
        pat: SHOW_IP_PROTOCOLS_PAT,
        next: 'config',
        pr: 'R3(config)#',
        adv: true,
        msg: 'Routing Protocol is "ospf 3"\n  Router ID 10.90.3.1\n  Number of areas in this router is 1. 1 normal 0 stub 0 nssa\n  Routing for Networks:\n    10.90.2.4 0.0.0.3 area 0\n    10.90.3.0 0.0.0.255 area 0\n  Distance: (default is 110)\n\n✓ OSPF process กำลังทำงานอยู่ครับ (Router ID เลือกจาก IP interface ที่สูงสุด) — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },
  {
    id: 12,
    router: 'R3',
    name: 'R3 — end & write memory',
    short: 'save R3',
    mode: 'config',
    prompt: 'R3(config)#',
    cmdHint: { cmd: 'R3(config)# end  →  write memory', desc: 'บันทึก config R3 ที่ตั้งค่าไว้ให้ถาวร' },
    hints: [
      { cmd: 'R3(config)# end', desc: 'ออกจาก config mode (end หรือ exit ก็ได้)' },
      { cmd: 'R3# write memory', desc: 'บันทึก config R3 ที่ตั้งค่าไว้ให้ถาวร' },
    ],
    answer: 'end\nwrite memory',
    commands: [
      { mode: 'config', pat: END_OR_EXIT_PAT, next: 'exec-priv', pr: 'R3#', adv: false, msg: 'R3#' },
      { mode: 'exec-priv', pat: writeMemPat(), next: 'exec-priv', pr: 'R3#', adv: true, msg: 'Building configuration...\n[OK]\n✓ R3 config บันทึกแล้วครับ — สลับไปทำ R2 ต่อครับ' },
    ],
  },

  // ── เฟส 2 (ต่อ): ที่เหลือของ R2 (เปิด OSPF, ตรวจสอบ, save) — R3 ตั้งค่าไปก่อนแล้ว พอ R2 เสร็จ Neighbor กับ R3 จะขึ้นทันที ──
  {
    id: 13,
    router: 'R2',
    name: 'R2 — เปิดใช้งาน OSPF (Process ID 2)',
    short: 'OSPF setup',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# router ospf 2', desc: 'เข้าสู่โหมดตั้งค่า OSPF ด้วย Process ID 2 (ไม่ต้องตรงกับ R3 ที่ใช้ 3 — Locally Significant)' },
    hints: [
      { cmd: 'R2(config)# router ospf 2', desc: 'เข้าสู่โหมดตั้งค่า OSPF — Process ID ของแต่ละ Router ไม่จำเป็นต้องตรงกัน' },
      { cmd: 'R2(config-router)# network 10.90.2.0 0.0.0.3 area 0', desc: 'ประกาศ network ฝั่ง R1 ด้วย wildcard mask — ลิงก์นี้เป็น /30 ให้หา inverse เอง พร้อม Area 0' },
      { cmd: 'R2(config-router)# network 10.90.2.4 0.0.0.3 area 0', desc: 'ประกาศ network ฝั่ง R3 ด้วย wildcard mask — ลิงก์นี้เป็น /30 ให้หา inverse เอง พร้อม Area 0' },
    ],
    answer: 'router ospf 2\nnetwork 10.90.2.0 0.0.0.3 area 0\nnetwork 10.90.2.4 0.0.0.3 area 0',
    commands: [
      { mode: 'config', pat: routerOspfPat('2'), next: 'config-router', pr: 'R2(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: networkAreaPat('10.90.2.0', '0.0.0.3', '0'), next: 'config-router', pr: 'R2(config-router)#', adv: false, msg: '' },
      {
        mode: 'config-router',
        pat: networkAreaPat('10.90.2.4', '0.0.0.3', '0'),
        next: 'config',
        pr: 'R2(config)#',
        adv: true,
        msg: '✓ เปิด OSPF (Process ID 2) บน R2 แล้วครับ — ประกาศ network ทั้ง 2 ฝั่งใน Area 0',
      },
    ],
  },
  {
    id: 14,
    router: 'R2',
    name: 'R2 — ตรวจสอบ Neighbor ด้วย show ip ospf neighbor (Checkpoint)',
    short: 'show neighbor',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# do show ip ospf neighbor', desc: 'ตรวจสอบว่า R2 เจอ Neighbor (R3) ผ่าน OSPF แล้วก่อน save — R3 config ไว้ก่อนแล้ว จึงควรเห็น Neighbor ทันที' },
    answer: 'do show ip ospf neighbor',
    commands: [
      {
        mode: 'config',
        pat: SHOW_OSPF_NEIGHBOR_PAT,
        next: 'config',
        pr: 'R2(config)#',
        adv: true,
        msg: 'Neighbor ID     Pri   State           Dead Time   Address         Interface\n10.90.3.1         1   FULL/DR         00:00:38    10.90.2.6       GigabitEthernet0/1\n\n✓ เห็น Neighbor R3 (Router ID 10.90.3.1) ผ่าน OSPF แล้วครับ (DR = Router ที่ได้รับเลือกเป็น Designated Router บน Link นี้) — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },
  {
    id: 15,
    router: 'R2',
    name: 'R2 — end & write memory',
    short: 'save R2',
    mode: 'config',
    prompt: 'R2(config)#',
    cmdHint: { cmd: 'R2(config)# end  →  write memory', desc: 'บันทึก config R2' },
    hints: [
      { cmd: 'R2(config)# end', desc: 'ออกจาก config mode (end หรือ exit ก็ได้)' },
      { cmd: 'R2# write memory', desc: 'บันทึก config R2 ที่ตั้งค่าไว้ให้ถาวร' },
    ],
    answer: 'end\nwrite memory',
    commands: [
      { mode: 'config', pat: END_OR_EXIT_PAT, next: 'exec-priv', pr: 'R2#', adv: false, msg: 'R2#' },
      { mode: 'exec-priv', pat: writeMemPat(), next: 'exec-priv', pr: 'R2#', adv: true, msg: 'Building configuration...\n[OK]\n✓ R2 config บันทึกแล้วครับ — สลับไปทำ R1 ต่อครับ' },
    ],
  },

  // ── เฟส 3: ที่เหลือของ R1 (เปิด OSPF, ตรวจสอบ, save) แล้วตรวจสอบผลลัพธ์รวม — R2 ตั้งค่าไปก่อนแล้ว พอ R1 เสร็จ Neighbor กับ R2 จะขึ้นทันที ──
  {
    id: 16,
    router: 'R1',
    name: 'R1 — เปิดใช้งาน OSPF (Process ID 1)',
    short: 'OSPF setup',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# router ospf 1', desc: 'เข้าสู่โหมดตั้งค่า OSPF ด้วย Process ID 1' },
    hints: [
      { cmd: 'R1(config)# router ospf 1', desc: 'เข้าสู่โหมดตั้งค่า OSPF ด้วย Process ID 1 (คนละเลขกับ R2/R3 ก็ได้)' },
      { cmd: 'R1(config-router)# network 10.90.1.0 0.0.0.255 area 0', desc: 'ประกาศ network ฝั่ง PC-A ด้วย wildcard mask — วง LAN นี้เป็น /24 ให้หา inverse เอง พร้อม Area 0' },
      { cmd: 'R1(config-router)# network 10.90.2.0 0.0.0.3 area 0', desc: 'ประกาศ network ฝั่ง R2 ด้วย wildcard mask — ลิงก์นี้เป็น /30 ให้หา inverse เอง พร้อม Area 0' },
    ],
    answer: 'router ospf 1\nnetwork 10.90.1.0 0.0.0.255 area 0\nnetwork 10.90.2.0 0.0.0.3 area 0',
    commands: [
      { mode: 'config', pat: routerOspfPat('1'), next: 'config-router', pr: 'R1(config-router)#', adv: false, msg: '' },
      { mode: 'config-router', pat: networkAreaPat('10.90.1.0', '0.0.0.255', '0'), next: 'config-router', pr: 'R1(config-router)#', adv: false, msg: '' },
      {
        mode: 'config-router',
        pat: networkAreaPat('10.90.2.0', '0.0.0.3', '0'),
        next: 'config',
        pr: 'R1(config)#',
        adv: true,
        msg: '✓ เปิด OSPF (Process ID 1) บน R1 แล้วครับ — ประกาศ network ทั้ง 2 ฝั่งใน Area 0',
      },
    ],
  },
  {
    id: 17,
    router: 'R1',
    name: 'R1 — ตรวจสอบ Neighbor ด้วย show ip ospf neighbor (Checkpoint)',
    short: 'show neighbor',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# do show ip ospf neighbor', desc: 'ตรวจสอบว่า R1 เจอ Neighbor (R2) ผ่าน OSPF แล้วก่อน save — ใช้ do นำหน้าเพื่อรันคำสั่ง show จาก config mode ได้เลยโดยไม่ต้อง exit' },
    answer: 'do show ip ospf neighbor',
    commands: [
      {
        mode: 'config',
        pat: SHOW_OSPF_NEIGHBOR_PAT,
        next: 'config',
        pr: 'R1(config)#',
        adv: true,
        msg: 'Neighbor ID     Pri   State           Dead Time   Address         Interface\n10.90.2.5         1   FULL/DR         00:00:32    10.90.2.2       GigabitEthernet0/1\n\n✓ เห็น Neighbor R2 (Router ID 10.90.2.5) ผ่าน OSPF แล้วครับ — บันทึกความคืบหน้าไว้แล้ว',
      },
    ],
  },
  {
    id: 18,
    router: 'R1',
    name: 'R1 — end & write memory',
    short: 'save R1',
    mode: 'config',
    prompt: 'R1(config)#',
    cmdHint: { cmd: 'R1(config)# end  →  write memory', desc: 'บันทึก config R1 ไปยัง NVRAM' },
    hints: [
      { cmd: 'R1(config)# end', desc: 'ออกจาก config mode กลับสู่ Privileged EXEC (end หรือ exit ก็ได้)' },
      { cmd: 'R1# write memory', desc: 'บันทึก config ที่ตั้งค่าไว้ให้ถาวรไปยังหน่วยความจำของ Router' },
    ],
    answer: 'end\nwrite memory',
    commands: [
      { mode: 'config', pat: END_OR_EXIT_PAT, next: 'exec-priv', pr: 'R1#', adv: false, msg: 'R1#' },
      { mode: 'exec-priv', pat: writeMemPat(), next: 'exec-priv', pr: 'R1#', adv: true, msg: 'Building configuration...\n[OK]\n✓ R1 config บันทึกแล้วครับ' },
    ],
  },
  {
    id: 19,
    router: 'R1',
    name: 'R1 — ตรวจสอบ Routing Table รวม (show ip route)',
    short: 'show route',
    mode: 'exec-priv',
    prompt: 'R1#',
    cmdHint: { cmd: 'R1# show ip route', desc: 'ดู network ที่ R1 เรียนรู้มาจาก OSPF โดยอัตโนมัติ (ไม่ต้องพิมพ์ ip route เองเลย) — สังเกตรหัส O (OSPF)' },
    answer: 'show ip route',
    commands: [
      {
        mode: 'exec-priv',
        pat: /^sh(ow)?\s+ip\s+route$/i,
        next: 'exec-priv',
        pr: 'R1#',
        adv: true,
        msg: 'Codes: L - local, C - connected, O - OSPF\n\nC    10.90.1.0/24 is directly connected, GigabitEthernet0/0\nC    10.90.2.0/30 is directly connected, GigabitEthernet0/1\nO    10.90.2.4/30 [110/2] via 10.90.2.2, 00:00:15, GigabitEthernet0/1\nO    10.90.3.0/24 [110/3] via 10.90.2.2, 00:00:15, GigabitEthernet0/1\n\n✓ เห็น network 10.90.2.4/30 และ 10.90.3.0/24 ที่เรียนรู้มาจาก OSPF (O) แล้วครับ — ไม่ต้องพิมพ์ ip route เอง',
      },
    ],
  },
  {
    id: 20,
    router: 'PC-A',
    type: 'pcping',
    name: 'PC-A — ทดสอบ ping ไปยัง PC-C ผ่าน Command Prompt',
    short: 'ping PC-C (PC)',
    mode: 'pcping',
    prompt: '(คลิก PC-A)',
    target: { ip: '10.90.3.10', label: 'PC-C' },
    cmdHint: {
      cmd: '(คลิกที่ไอคอน PC-A บนแผนภาพด้านบน แล้วพิมพ์ ping 10.90.3.10 ในหน้า Command Prompt)',
      desc: 'ทดสอบว่า PC-A คุยกับ PC-C ได้จริงจากมุมมองผู้ใช้งานทั่วไป (ไม่ผ่าน Router) — ยืนยันว่า OSPF พาไปถึงปลายทางได้จริง',
    },
  },
];

export const PRETEST: PretestQuestion[] = [
  {
    id: 'q1',
    type: 'mcq',
    q: 'OSPF เป็น Routing Protocol ประเภทไหน?',
    opts: ['Distance Vector เหมือน RIP', 'Advanced Distance Vector เหมือน EIGRP', 'Path-Vector เหมือน BGP', 'Link-State ล้วนๆ'],
    ans: 3,
    exp: 'OSPF เป็น Link-State Protocol แท้ๆ — แต่ละ Router สร้างแผนที่ทั้ง Network ขึ้นมาเอง (Topology Database) แล้วคำนวณเส้นทางที่ดีที่สุดด้วยอัลกอริทึม Dijkstra (SPF) ต่างจาก Distance Vector (RIP) ที่รู้แค่ "ทางไหนใกล้กว่า" จากเพื่อนบ้านบอกมา',
  },
  {
    id: 'q2',
    type: 'mcq',
    q: 'OSPF ใช้ metric ที่เรียกว่าอะไร และคำนวณจากอะไร?',
    opts: ['Cost — คำนวณจาก Bandwidth ของ Interface', 'Hop Count — จำนวน Router ที่ผ่าน', 'Bandwidth และ Delay รวมกัน', 'จำนวน Area ที่ผ่าน'],
    ans: 0,
    exp: 'OSPF ใช้ Cost เป็น metric โดย Cisco คำนวณจากสูตร Reference Bandwidth (default 100 Mbps) หาร ด้วย Bandwidth จริงของ Interface นั้น — Interface ที่ Bandwidth สูงกว่าจะมี Cost ต่ำกว่า และถูกเลือกเป็นเส้นทางที่ดีกว่า',
  },
  {
    id: 'q3',
    type: 'mcq',
    q: 'ข้อใดถูกต้องเกี่ยวกับ Process ID ในคำสั่ง router ospf [process-id]?',
    opts: [
      'ทุก Router ต้องใช้ Process ID เดียวกัน เหมือน AS Number ของ EIGRP',
      'Process ID เป็นตัวเลขที่มีผลแค่ภายใน Router เครื่องนั้น (Locally Significant) ไม่ต้องตรงกับ Router อื่น',
      'Process ID มีผลต่อการคำนวณ Cost โดยตรง',
      'ต้องตั้ง Process ID ให้ตรงกับเลข Area เสมอ',
    ],
    ans: 1,
    exp: 'Process ID ของ OSPF เป็นค่าที่ Router ใช้แยกแยะ OSPF process หลายตัวภายในเครื่องตัวเอง (เผื่อรันหลาย instance) ไม่ได้ถูกส่งออกไปให้ Router อื่นรับรู้เลย ดังนั้น R1 ใช้ router ospf 1 ในขณะที่ R2 ใช้ router ospf 2 ก็ยังทำงานร่วมกันได้ปกติ — ต่างจาก EIGRP ที่ AS Number ต้องตรงกันทุก Router',
  },
  {
    id: 'q4',
    type: 'dragdrop',
    q: 'จับคู่คำสั่งกับหน้าที่ของมัน',
    pairs: [
      { left: 'router ospf 1', right: 'เข้าสู่โหมดตั้งค่า OSPF ด้วย Process ID ที่ระบุ (Locally Significant)' },
      { left: 'network 10.90.1.0 0.0.0.255 area 0', right: 'ประกาศ network ด้วย wildcard mask พร้อมระบุ Area ที่สังกัด' },
      { left: 'show ip ospf neighbor', right: 'ตรวจสอบสถานะ Neighbor และดูว่าใครเป็น Designated Router (DR)' },
      { left: 'show ip route', right: 'ดู Routing Table ที่มี Route รหัส O (OSPF) ที่เรียนรู้มาอัตโนมัติ' },
    ],
  },
];

export const INTRO_LINES = [
  { text: '# Ch.9 OSPF — NETLab', cls: 't-info' },
  { text: '# อ้างอิง: Cisco Networking Academy W9', cls: 't-hint' },
  { text: '# Topology: PC-A—R1—R2—R3—PC-C (ใช้ VLSM: LAN /24, WAN /30)', cls: 't-dim' },
  { text: '# R1: g0/0=10.90.1.1/24  g0/1=10.90.2.1/30', cls: 't-dim' },
  { text: '# R2: g0/0=10.90.2.2/30  g0/1=10.90.2.5/30', cls: 't-dim' },
  { text: '# R3: g0/0=10.90.2.6/30  g0/1=10.90.3.1/24', cls: 't-dim' },
  { text: '# OSPF: Single-Area, Area 0 (Backbone) — Process ID เลือกได้อิสระต่อ Router', cls: 't-dim' },
  { text: '' },
  { text: '# เริ่มที่ R1 — พิมพ์: enable', cls: 't-hint' },
];

export const WELCOME_MSG =
  'สวัสดีครับ! Ch.9 OSPF\n\nTopology: PC-A—R1—R2—R3—PC-C (ใช้ VLSM: LAN /24, WAN /30)\nขั้นตอนแรก: ตั้งชื่อ hostname และ IP ให้ครบทุกอุปกรณ์ก่อน (รวม PC-A, PC-C ด้วย — คลิกที่ไอคอน PC บนแผนภาพเพื่อกรอก IP) แล้วค่อยเปิด OSPF Single-Area (network พร้อม wildcard mask + area 0) ให้ Router เรียนรู้เส้นทางกันเองอัตโนมัติแบบ Link-State รวม 25 steps (มีจุด Checkpoint ตรวจสอบด้วย show ก่อน save ทุก Router — สังเกตว่า Checkpoint ของ R2/R1 จะเห็น Neighbor ขึ้นจริง เพราะฝั่งตรงข้ามตั้งค่าไปก่อนแล้ว)\nแต่ละเส้นจะเขียวเมื่อทั้งสองฝั่งตั้งค่าเสร็จครับ\n\nทำ Pre-test ก่อนหรือข้ามไป Lab เลยก็ได้ครับ';

export const COMPLETE_CHAT_SUMMARY =
  'ยินดีด้วยครับ! Lab Ch.9 เสร็จสมบูรณ์!\n\nสรุป:\n• R1, R2, R3: ตั้ง IP แบบ VLSM ครบทุก interface (LAN /24, WAN /30) แล้วเปิด OSPF Single-Area (router ospf ใช้ Process ID คนละเลขได้ + network พร้อม wildcard mask + area 0)\n• Router ทั้ง 3 ตัวเรียนรู้เส้นทางกันเองอัตโนมัติผ่าน Link-State (SPF) เห็น Neighbor ขึ้นสถานะ FULL/DR และ route แบบ O (OSPF)\n• Ping PC-A→PC-C สำเร็จผ่าน route ที่ OSPF เรียนรู้เอง';
